### ISSUE TITLE
Better defaults for khal list

### ISSUE THREAD

**Issue by adigitoleo** [pimutils/khal#1006]
Just started using khal recently, mostly my workflow involves using `ikhal` to set up events (this part is really nice, the interface is very intuitive) and then refresh my memory using `khal list`. However, I find the `list` command difficult to use for simple cases, and I keep having to check the docs to remember how to use it.

Some suggestions:
- Simple `khal list` should print events for one week , not just today (or make this configurable)
- Alternatively, `khal list week` could be an equivalent to `khal list today week`
- Similar for `khal list month`
- In general, it would be nice to have the start date default to 'today, now' so that things like `khal list 4d` would print events for the next four days

Most of it comes down to wanting my event list to start from 'today' by default, unless explicitly told otherwise. The docs has this:
> If END is not given, midnight of the start date is assumed. Today is used for START if it is not explicitly given. If DELTA, a (date)time range in the format I{m,h,d}, where I is an integer and m means minutes, h means hours, and d means days, is given, END is assumed to be START + DELTA. A value of eod is also accepted as DELTA and means the end of day of the start date. In addition, the DELTA week may be used to specify that the daterange should actually be the week containing the START.

Except `khal list 4d`, for example, prints an error, and `khal list 06/02/2021` prints events for 06/02/2021 **only**, so "today is used for START if not explicitly given" seems either wrong or misleading.

Anyway it's a nice little tool and this is my only gripe so far. Thanks for the hard work!

**Comment by d7415** [comment]
Hi

We could perhaps look at differentiating between a time and timedelta. This is a little more complicated than you suggest though as khal will accept a start and end time for its range.

In the meantime, you may wish to check the `timedelta` setting in https://khal.readthedocs.io/en/latest/configure.html#the-default-section as that covers your 

> (or make this configurable)

and 

> `khal list 06/02/2021` prints events for 06/02/2021 **only**

Also, re

> "today is used for START if not explicitly given" seems either wrong or misleading.

that's exactly what it's doing. In the first case you gave a "START" of `4d` which it doesn't understand. In the second case you gave a START, but no END or RANGE, so it fell back to the default from the config.

**Comment by adigitoleo** [comment]
Thanks, the timedelta setting is very helpful, apologies for missing it earlier.

And the other part also makes sense after reading it again. I guess I was confused by the implication that START can be omitted (not explicitly given), but that's only really the case if END or DELTA are also omitted, right?

I'll probably use aliases for now, as suggested. My idea, which I probably didn't articulate that well, was about this part:
> khal will accept a start and end time for its range, so if a user specifies only 2021-02-06 is that the start or end?

IMHO if only one date/delta is specified, that should be taken as END | DELTA, and today becomes START. If two dates (or one date one delta) are specified, the first one is START and the second END | DELTA. So, inverting:
```
khal list [START [END | DELTA] ]
```
to
```
khal list [ [START] END | DELTA]
```
(which is what I thought the docs were saying, but admittedly I didn't read very carefully)

**Comment by d7415** [comment]
>  that's only really the case if END or DELTA are also omitted, right?

Correct

> IMHO if only one date/delta is specified, that should be taken as END | DELTA, and today becomes START. If two dates (or one date one delta) are specified, the first one is START and the second END | DELTA. So, inverting:

I **strongly** disagree. I'd say it's far more likely that a user typing `khal list Friday` expects to see their events for Friday, not their events from today until (but not including) Friday.

**Comment by adigitoleo** [comment]
> I strongly disagree. I'd say it's far more likely that a user typing khal list Friday expects to see their events for Friday, not their events from today until (but not including) Friday.

I would think including Friday, but you have a pretty strong point there, maybe I just didn't spend enough time with khal to get used to it. Anyway the 'timedelta' setting seems to be what I was really looking for (I like to see those extra few days ahead). Thanks for indulging me with this discussion, and since it's mostly solved by me reading docs properly (oops) I'm happy for this to be closed.
