### ISSUE TITLE
Create event: How to specify delta time?

### ISSUE THREAD

**Issue by sciurius** [pimutils/khal#1011]
According to the docs, the syntax for creating an event allows specification of a start time, and end time or delta.

How must a delta time be specfied?

    khal new wed 11:00 2:00 xxx

creates an event from wednesday 11:00 till thursday 02:00

**Comment by d7415** [comment]
A time delta is specified using a suffix like `d`/`h`/`m`/`s`, `days`/`hours`/`minutes`/`seconds` or `min`/`sec`. For your example, `2h` should work. Combinations will also work, e.g. `1h15m`.

**Comment by sciurius** [comment]
Thanks!
