### ISSUE TITLE
Fix Docs on readthedocs

### ISSUE THREAD

**Issue by geier** [pimutils/khal#1017]
https://readthedocs.org/projects/khal/

**Comment by d7415** [comment]
I was meaning to ask about this regarding #1008 and #1016.

Shall I merge those and #926 to get them done and save doing it again? Or will the plan be to automate the readthedocs build/import?

**Comment by geier** [comment]
Sure, go ahead and merge those. I'll try to take care of readthedocs.

**Comment by d7415** [comment]
Merged!

**Comment by geier** [comment]
Thanks!.

Docs seem to build fine again as well.
