### ISSUE TITLE
khal list output format difficult for other programs to parse

### ISSUE THREAD

**Issue by tubaman** [pimutils/khal#1025]
khal [output format options](https://khal.readthedocs.io/en/latest/usage.html#cmdoption-format) are fantastic for humans(colorized, etc)!  However, I feel like I'm jumping through hoops to make khal's list output parsable by other programs.  For example, if I want another program to parse a list events with title, start and description, currently I'm generating a unique field separator that I can use later for splitting:

(in python)
```python
rsep = str(uuid.uuid4())
fsep = str(uuid.uuid4())
fmt = "{title}%s{start-long}%s{description}%s" % (fsep, fsep, rsep)
cmd = ['khal', 'list', '--notstarted', '--day-format', '', '--format', fmt, start, end]
```

Perhaps it would be nice to add a `--json` option to format khal's list output as a JSON array of objects?

**Comment by geier** [comment]
should be fixed with #1308
