### ISSUE TITLE
Define VALARM defaults per calendar

### ISSUE THREAD

**Issue by Petemir** [pimutils/khal#1027]
Hello,

I think it could be a useful feature to be able to define VALARM defaults on the config file. This could be a per calendar setting, or global. I could attempt to do this, perhaps [using this ](https://github.com/pimutils/khal/commit/ed31553b1fb18d28779dd63e8fd11e3e54218027) as a guide?

Thanks.

**Comment by d7415** [comment]
NB #698

**Comment by Petemir** [comment]
Duplicate of #698 .
