### ISSUE TITLE
Error with apostrophe in Summary field

### ISSUE THREAD

**Issue by bill-lancaster** [pimutils/khal#1028]
This my first post here, have read the guidlines.
When creating a new calendar item in Khal, I get 'Syntax error: Unterminated quoted string' error
I see there has been an issue with apostrophes in calendar names but can't find a reference to this problem.
Any advice would be welcome

**Comment by d7415** [comment]
It works fine for me - how are you adding the event? Which version of khal are you using?

**Comment by bill-lancaster** [comment]
Thanks, should have been more explicit,
version 0.9.10
From terminal in Kubuntu 20.04
`:~$ khal new -a 'private' 29/3/2021 1:30 'Men's Golf'`

**Comment by bill-lancaster** [comment]
Actually, I started writing through a shell to terminal in Gambas3.  Got the same error writing direct in terminal but now, instead of an error, the above code goes into interactive mode but without any prompts.

**Comment by d7415** [comment]
I guess you've figured it out as you've closed the issue, but in case anyone else finds this, you need to escape the `'` in the shell. The easiest way would be to use double quotes as the string delimiters, i.e. `khal new -a private 29/3/2021 1:30 "Men's Golf"`

**Comment by d7415** [comment]
> Actually, I started writing through a shell to terminal in Gambas3. Got the same error writing direct in terminal but now, instead of an error, the above code goes into interactive mode but without any prompts.

I'm not sure I understand what you mean here.

**Comment by bill-lancaster** [comment]
Sorry, I closed the issue by accident.
This is what terminal looka like:-
`:~$ khal new -a 'private' 29/3/2021 1:30 'Men's Golf'
> 
`
Thanks for the help, had tried several ways of escaping the apostrophe, yours is the one that works.

**Comment by bill-lancaster** [comment]
Should have been. . .
`:~$ khal new -a 'private' 29/3/2021 1:30 'Men's Golf'
> 
`

**Comment by bill-lancaster** [comment]
You can see I'm new to this! The quoted code should have finished with the character '>' but it disapears when the comment is posted!
