### ISSUE TITLE
All events display the same name

### ISSUE THREAD

**Issue by odea** [pimutils/khal#1036]
Hi,
I got a .ics files with French holidays, etc.. https://etalab.github.io/jours-feries-france-data/ics/jours_feries_metropole.ics
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20220508
DTSTAMP:20200101T000000Z
SUMMARY:8 mai
UID:00fd28dc3058aa5389abadb6a02b8b5b
END:VEVENT
BEGIN:VEVENT
DTSTART;VALUE=DATE:20250714
DTSTAMP:20200101T000000Z
SUMMARY:14 juillet
UID:93686d52c729aca3c401065e490d98fd
END:VEVENT
```
When I add it to khal, all the events has the same name (8 mai), but when I read the .ics file I can see that Summaries are differents.
My khal config :
```
[calendars]
    [[personal]]
    path = ~/.calendar/personal
    type = calendar
    color = dark cyan

    [[contact_birthdays]]
    path = ~/.calendar/contact_birthdays
    type = birthdays
    readonly = True
    color = dark green

    [[facebook]]
    path = ~/.calendar/facebook
    type = calendar
    color = dark magenta 

    [[jours_feries]]
    path = ~/.calendar/jours_feries
    type = calendar
    color = yellow

[default]
#Set calendar used for new events when no one is given
default_calendar = personal
#Color dates when containing an event
highlight_event_days = true
#Timespan of days whose events are shown in e.g. list
timedelta = 15d

[locale]
timeformat = %H:%M
dateformat = %d/%m/%Y
longdateformat = %d/%m/%Y
datetimeformat = %d/%m/%Y %H:%M
longdatetimeformat = %d/%m/%Y %H:%M
unicode_symbols = false
```
I have the same problem with facebook's events.
Is it a dateformat problem ? do I have to match dateformat  with the .ics date format ? what happens when I have different calendars with different date format ?
Thanks

**Comment by d7415** [comment]
Are you using `khal import` or adding the file directly?

khal expects events in [vdir](https://vdirsyncer.readthedocs.io/en/stable/vdir.html) format, which is one event per file. This means that if you put that file directly into a calendar directory khal won't like it, but `khal import` should be able to convert it successfully. If the file is online, you may wish to look at [vdirsyncer's http storage](https://vdirsyncer.readthedocs.io/en/stable/config.html#storage-http).

**Comment by odea** [comment]
Thanks d7415, indeed that was my mistake, I put the .ics file directly into the calendar directory, works perfect with khal import, Thanks again :)
