### ISSUE TITLE
edit of datetime range fails with error parsing range

### ISSUE THREAD

**Issue by allanwind** [pimutils/khal#1055]
(venv) allan@vent:~/src/khal$ khal new -i
summary: test
datetime range: now
timezone [EST5EDT]:
description (or "None") [None]: test
event saved
Edit?  do[n]e  [s]ummary  [d]escription  da[t]etime range  re[p]eat  [l]ocation  [c]ategories  [a]larm  [D]elete  [u]rl: t                                                                                                                    
datetime range [2021-05-26 20:28 2021-05-26 21:28]:
error parsing range

The main issue is:

1. "error parsing range"

There are a couple of minor issues.

2. The program asks for "datetime range" but I enter a single datetime.  If the ending interval is optional maybe it should be two fields/questions?  It's a bit weird that the "now" maps to 1 hour interval, while "today" is a full day event.

3. For the "datetime range" I entered the value "now", and the program converts that to a pair of timestamps.  It would be better if at least within the new -i session the value that the user entered was retain.  Alternatively, program could tell user that input x was changed to y so it's not a surprise if you want to edit it.

**Comment by d7415** [comment]
1) Yup, that's a bug. But as the result is the same as the no-bug case I don't think it's especially critical.
2) This seems to be several questions. The short answer is: it asks for a range, like with a new event. The behaviour is the same. If you don't specify the end it uses the default (which can be set in the config file). Similarly, if you only specify a date (like "today") it assumes it's all day. If you specify a time (like "now") it assumes it's not.
3) What value that the user entered? The value is a range. If you replace the range with a single value, it will use the default duration. If you provide a duration (e.g. `now 2h`) or an end date/time, it will use that. Again, the behaviour is consistent across khal. You may want to try `ikhal` if you want to treat these separately.

**Comment by allanwind** [comment]
1. What do you mean with the "But as the result is the same as the no-bug case"?  Just trying to understand.  I don't know if the bug is that you cannot edit datetime range, or if output format cannot be parsed which means that the work-around is to just reformat the input.
2a. My point was that we request a. "datetime range" as in "START < END | DELTA >" (two required arguments) but the 2nd argument is actually optional.  I was speculating that it would be more clear if asked for two fields a required start, and an optional "end or delta".  You could also change the prompt to say "start optional end or delta" (btw, ISO 8601 calls delta a "duration").
2b. "now" maps to the range (t, t + 1 hour).  "today" maps to (t@midnight at selected timezone to t @ midnight at selected timezone + 1 day).  It's the implicit hour vs day of the delta that I find a little odd. "monday" maps to the (t + days till next monday @ midnight, t + days till next monday @ midnight + 1 day).  Why is the delta a day and not a week?  "january" is silently ignored but should be next 1st january 1st at midnight + 1 month or + 1 day?
3. User enters datetime range: "now", timezone: "UTC" when creating the event but if you now want to edit it the value is "2021-05-27 05:53 2021-05-27 06:53".  It's a subtle form of data loss.

**Comment by d7415** [comment]
1) You asked it to not change. It didn't change.

>     2\. "datetime range" as in "START < END | DELTA >" (two required arguments)

Where are you finding that definition?

2b) Those are configurable.

>     2\. "january" is silently ignored but should be next 1st january 1st at midnight + 1 month or + 1 day?

Please stop using unrealistic examples.

3) That is an interesting edge case and may warrant further discussion.

**Comment by allanwind** [comment]
1. khal new --help

2b) "january" is minor defect, but I thought it was helpful to illustrate that to an end-user it's magic how the end range is determined.  I am not yet familiar with the configurable aspect but sounds like that resolves 2b.  As an end-user I also appreciate that "now" and "today" do the right thing.  I.e. 2a is more interesting (minor) issue.

**Comment by d7415** [comment]
>     The definition is in `khal new --help`.
Mine definitely shows `END | DELTA` as optional.
```
Usage: khal new [OPTIONS] [START [END | DELTA] [TIMEZONE] [SUMMARY] [::
                DESCRIPTION]]```

>     to an end-user it's magic how the end range is determined.

Not if they read the [documentation](https://khal.readthedocs.io/en/latest/usage.html#new)

>   I am not yet familiar with the configurable aspect but sounds like that resolves b.  As an end-user I also appreciate that "now" and "today" do the right thing.

https://khal.readthedocs.io/en/latest/configure.html#the-default-section

**Comment by allanwind** [comment]
> > ```
> > The definition is in `khal new --help`.
> > ```
> 
> Mine definitely shows `END | DELTA` as optional.
> 
> ```
> Usage: khal new [OPTIONS] [START [END | DELTA] [TIMEZONE] [SUMMARY] [::
>                 DESCRIPTION]] 
> ```

Right and `khal new -i` / `khal edit` just says "datetime range" which doesn't make it clear that END | DELTA is optional.  That was the point that I was trying to make.  It might be worth consider to let `khal interactive` be the only interactive interface, and then work towards new/edit/search/list being driven via options/arguments only.

> > ```
> > to an end-user it's magic how the end range is determined.
> > ```
> 
> Not if they read the [documentation](https://khal.readthedocs.io/en/latest/usage.html#new)

Yeah, it's a good point, and most users don't read the manual unless they are stuck.  Here is what it says:

>  If  no  end is given, the default length of one hour or one day (for all-day events) is used. If only a start
>        time is given the new event is assumed to be starting today. If only a time is given for the event to end on,
>        the event ends on the same day it starts on, unless that would make the event end before it has started, then
>        the next day is used as end date

Documentation is hard.   If START is "yesterday", "today" "tomorrow', "mon, "monday", "tue", "tuesday"... "sun" or "sunday" then START is replaced with the computed value to date and time is 00:00 in whatever timezone you specified and DELTA defaults to 1d.  Otherwise if START if start is "now" it is replaced with .... and DELTA defaults to 1h.  "Midnight is the transition time from one day to the next" but I don't think there is a word for today at 00:00.  This still falls apart as new -i and edit calls those 3 fields "datetime range" :-) 

And really, I don't want to be a pain, just sharing the issue that I see with "fresh" eyes.

> > I am not yet familiar with the configurable aspect but sounds like that resolves b.  As an end-user I also appreciate that "now" and "today" do the right thing.
> 
> https://khal.readthedocs.io/en/latest/configure.html#the-default-section
