### ISSUE TITLE
Feature request: Add "displayname" for calendars.

### ISSUE THREAD

**Issue by Antiquis** [pimutils/khal#1063]
I am currently using Mailfence as my email and WebDAV provider, and they store calendar events inside an "events" subdirectory. 

Vdirsyncer copies this folder structure (which is fine), but it means that I end up with four calendars that are displayed with the same name, suffixed by [n], within the Khal UI:
![Screenshot of problem](https://i.joshq.uk/u/Omlc7WbBlv.png)

The only solution that I've found to resolve this so far is to symlink the 'events' directories (that Vdirsyncer creates) to another location on the system, and to then point Khal to these symlinks, or to change the "status file" that Vdirsyncer generates to point to a different directory - either way, this is an additional manual step that I'd rather avoid.

Would it be possible to implement a "displayname" option for calendars, such that this is no longer a problem?

I have commented in an example of how this might work in [my Khal config](https://github.com/Antiquis/dotfiles/blob/main/khal/config).

Thanks for producing a great utility - I've really enjoyed using Khal so far!

**Comment by d7415** [comment]
This is already implemented. Have you [configured it in `vdirsyncer`](https://vdirsyncer.pimutils.org/en/stable/tutorial.html?highlight=metasync#metadata-synchronization)?

**Comment by Antiquis** [comment]
> This is already implemented. Have you [configured it in `vdirsyncer`](https://vdirsyncer.pimutils.org/en/stable/tutorial.html?highlight=metasync#metadata-synchronization)?

Yes I have configured this, however after running a `metasync`, and updating the values of the `displayname` files, it appears you might be adding new line characters to specified names?

![Screenshot of problem](https://i.joshq.uk/u/VHObwDNu28.png)

I can assure you that there is no new line character at the end of the content in `~/.local/share/vdirsyncer/calendars/Personal/events/displayname` (see screenshot above). I have tried setting default_calendar to `Personal`, `Personal\n` and `"Personal\n", none of which seem to be working.

It would be much better, if possible, to be able to hardcode these values into the config file to avoid these issues. Alternatively, if you know a solution to the above problem, I'd be glad to hear it.

**Comment by Antiquis** [comment]
Please re-open this request @d7415, as this is not resolved.

**Comment by d7415** [comment]
> Yes I have configured this, however after running a `metasync`, and updating the values of the `displayname` files, it appears you might be adding new line characters to specified names?

If you're having to edit them manually, you may want to speak to your provider about supporting them to save you effort, but that's not directly relevant here.

> I can assure you that there is no new line character at the end of the content in `~/.local/share/vdirsyncer/calendars/Personal/events/displayname` (see screenshot above). 

Actually your screenshot shows that there is, but khal strips them as of 0.10.3. Which version of khal are you using?

> It would be much better, if possible, to be able to hardcode these values into the config file to avoid these issues. 

I have no particular objection to this (we do it for `color`) but I don't think it's in particularly high demand.

**Comment by Antiquis** [comment]
> If you're having to edit them manually, you may want to speak to your provider about supporting them to save you effort, but that's not directly relevant here.
Thanks for this! I've contacted my provider to see if they can implement this.

> Actually your screenshot shows that there is, but khal strips them as of 0.10.3. Which version of khal are you using?
There we have my problem! It looks like the version in the Debian repository might be outdated (if I'm not mistaken). Having installed only yesterday from the standard Debian repos, I was running version 0.9.10. Upon uninstalling the package and reinstalling via `pip`, the latest version was installed. Many apologies for that - my fault entirely!

> I have no particular objection to this (we do it for `color`) but I don't think it's in particularly high demand.
No problem! If you get round to it, that would be great, but of course no worries if it's not a priority 😄 

I really appreciate your help - thank you very much.

**Comment by d7415** [comment]
> Thanks for this! I've contacted my provider to see if they can implement this.

:+1:

> from the standard Debian repos, I was running version 0.9.10. Upon uninstalling the package and reinstalling via `pip`, the latest version was installed. Many apologies for that - my fault entirely!

0.10.3 is now in testing - a new maintainer seems to have picked it up there. pip should generally be more up to date though as that's updated directly by us!

> I really appreciate your help - thank you very much.

No problem :)
