### ISSUE TITLE
how to answer `y` to all event when importing a large .ics file

### ISSUE THREAD

**Issue by bjce** [pimutils/khal#1070]
Hello

First of all many thanks to the developper and maintainers for this great piece of software

I'm trying to import a .ics file with around 200 entries with the command 

```
 khal import path/to/file.ics
```
However for each event, khal asks me the question `Do you want to import this event into `private`? [y/N]: `. Is there a way to answer `y` to all? 

many thanks in advance

**Comment by d7415** [comment]
Hi. You can use the `--batch` option.

**Comment by bjce** [comment]
@d7415 Martin Stone many thanks for your help!
