### ISSUE TITLE
How to display the hour in ikhal (+ is there a dicussion forum for basic question)

### ISSUE THREAD

**Issue by bjce** [pimutils/khal#1071]
Hello again. I'm sorry to bother the issue with a rather basic question. I want to output event with their hour time with `ikhal`. I could do it with the command:

```
khal list --format "{title} {start-time-full}"
```
I tried to modify the conf file in several ways without success:

```
[calendars]

  [[private]]
    path = /path/to/calendar/
    type = calendar
    color = dark green

[locale]
timeformat = %H:%M
dateformat = %d/%m/%Y
longdateformat = %d/%m/%Y
datetimeformat = %d/%m/%Y %H:%M
longdatetimeformat = %d/%m/%Y %H:%M

[default]
default_calendar = private
```
I tried to read the doc [here](https://khal.readthedocs.io/en/latest/usage.html#) and [there](https://khal.readthedocs.io/en/latest/configure.html) but unfortunately could not find how to implement the answer

More generally is there a dicussion forum for basic questions as this one?

Many thanks in advance

**Comment by WhyNotHugo** [comment]
> More generally is there a dicussion forum for basic questions as this one?

IMHO, issues are generally okay, but there's also IRC: https://github.com/pimutils/khal#feedback

With your settings, `ikhal` displays the times for events just fine. Can you share a screenshot of what you're seeing or what's missing?

**Comment by bjce** [comment]
Many thanks for your reply @WhyNotHugo 

Here is a screenshot of ikhal. According to screensho of [other users](https://www.dj-bauer.de/terminal-calendar-with-khal-en.html), I was expecting a time with hours and minute next to "appointment"

<img width="798" alt="Screenshot 2021-07-13 at 13 28 48" src="https://user-images.githubusercontent.com/27978044/125444467-c994eae5-d782-4050-b7d9-b969853cb2d1.png">

**Comment by WhyNotHugo** [comment]
It should be there.

Are you sure these events have date and **time**? They look like all-day events.

**Comment by d7415** [comment]
I'll have to check the import code, but the first thing I notice is that your source event doesn't have an end specified.

**Comment by bjce** [comment]
Sorry @WhyNotHugo and @d7415. I copied only the event of interest in the file event.ics. Here is the whole file event.ics (where I think all the required ends appear)

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py - http://git.io/lLljaA
BEGIN:VEVENT
DTSTART:20210716T130000Z
SUMMARY:appointment
UID:601a1c01-5c6c-491c-a943-394d9f5c5d21@601a.org
END:VEVENT
BEGIN:VEVENT
DTSTART:20210718T090000Z
SUMMARY:description3_1: appointment
UID:6b2e009f-3111-45da-9d75-41bcacf14c59@6b2e.org
END:VEVENT
BEGIN:VEVENT
DTSTART:20210717T160000Z
SUMMARY:description1_1 appointment
UID:93845ae1-977c-4d4a-bb2c-ca9fc06bd238@9384.org
END:VEVENT
BEGIN:VEVENT
DTSTART:20210719T120000Z
SUMMARY:appointment
UID:64960d7e-c67c-4900-b7e2-691affba08d1@6496.org
END:VEVENT
BEGIN:VEVENT
DTSTART:20210716T080000Z
SUMMARY:description1_2: appointment
UID:dad98333-97b8-482d-b4c1-4a5e9290c71f@dad9.org
END:VEVENT
BEGIN:VEVENT
DTSTART:20210717T140000Z
SUMMARY:description_5
UID:18fef3c0-8ce9-4775-98e1-708dd085d10e@18fe.org
END:VEVENT
END:VCALENDAR
```

**Comment by d7415** [comment]
> where I think all the required ends appear

Sorry, I wasn't clear - I meant the end of the events. They all start, they don't finish. I suspect this is part of it.

**Comment by bjce** [comment]
oh, I see... @d7415. Well actually the events I'm importing are events from taskwarrior with the due date as starting date/time but no end date/time. Indeed in that case, the best option could be instantaneous event. Do you have of what could be a next step?

**Comment by WhyNotHugo** [comment]
I imported the sample event and got the same result: a full-day event with no time.

Looks like a bug in the import code.

**Comment by d7415** [comment]
> Well actually the events I'm importing are events from taskwarrior

That makes sense.



> Looks like a bug in the import code.

Yup.

**Comment by d7415** [comment]
Looks like it's `ics_from_list` that breaks this.... I'll try to have another look later.

**Comment by d7415** [comment]
Found it. I'll draft up a PR.

**Comment by bjce** [comment]
Many thanks for editing the code so fast @d7415 ! I use `pip` in MacOS to install packages and have currently version `0.10.3`. Is there a way to try the fixes now or do I have to wait for the next release?

**Comment by d7415** [comment]
It wasn't merged yet. If you upgrade again using that method and then repeat the import it should then show the times, and the events will have a duration of one hour.
