### ISSUE TITLE
khal new adds start date as end date and end date to summary

### ISSUE THREAD

**Issue by Konfekt** [pimutils/khal#1078]
With

```
khal --version
khal, version 0.10.4

khal printformats
longdatetimeformat: 2013-12-21T21:45
datetimeformat: 2013-12-21
longdateformat: 2013-12-21
dateformat: 2013-12-21
timeformat: 21:45
```

the commands

```
khal new 2021-8-11 11:00 2021-8-11 12:00 test
khal list today
```

give output

```
00:00-11:00 2021-8-11 12:00 test
```

Expected would be

```
11:00-12:00 2021-8-11 test
```

**Comment by d7415** [comment]
> longdatetimeformat: 2013-12-21T21:45

If you change the `T` to a space this should work as you are expecting it to.

**Comment by Konfekt** [comment]
Yes that is the work around I use [here](https://github.com/pimutils/khal/pull/1079?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDIyNzYzNTYwNzU6NzE5NTU1Mw%3D%3D#pullrequestreview-727043834) but it breaks default configuration. 

But then neither does

```
khal new '2021-8-11 11:00' '2021-8-11 12:00' test 

khal list

00:00-11:00 2021-8-11 12:00 test

```

nor as [officially documented](https://khal.readthedocs.io/en/latest/usage.html) :

```
khal new 2021-8-11 18:00 24:00 Another Event :: with Alice and Bob

khal list

00:00-18:00 24:00 Another Event :: with Alice and Bob
```

Therefore this issue is not fixed.

**Comment by Konfekt** [comment]
Oh, I see, khal only accepts one single date format?

**Comment by d7415** [comment]
> Oh, I see, khal only accepts one single date format?

It accepts one of each of the formats in `khal printformats`

**Comment by Konfekt** [comment]
Yes, but only one longdatetimeformat (otherwise it complains about a doubled entry in the config file). I overread

```
The exact format of longdatetimeformat, datetimeformat, timeformat, longdateformat and dateformat can be configured in the configuration file. Valid keywords for dates are today, tomorrow, the English name of all seven weekdays and their three letter abbreviations (their next occurrence is used).
```

in the [documentation](https://khal.readthedocs.io/en/latest/usage.html) and forgot that at some point I changed the default time format to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
