### ISSUE TITLE
Feature request -- sample config file

### ISSUE THREAD

**Issue by Pankratius** [pimutils/khal#1085]
Hi, could you maybe provide a "more advanced" config file (for example one that corresponds to the screenshot on the front page of the repo?).
(Or maybe I'm just struggling to reproduce some of it :/).

**Comment by d7415** [comment]
I think that screenshot is mostly stock - What are you struggling with?
The colours come from setting a colour for your calendars (a `color` file or, ideally, `vdirsyncer metasync`)

**Comment by amandabee** [comment]
The wiki has an example and tips for searching Github for more:  https://github.com/pimutils/khal/wiki/Examples:-config

**Comment by Pankratius** [comment]
yeah sorry i was stupid thank you so much for taking the time to reply tho.
