### ISSUE TITLE
[ASK] ics validator ?

### ISSUE THREAD

**Issue by eoli3n** [pimutils/khal#1102]
I have issue with my caldav server, I would like to be able to validate ics file like with icalendar.org, but it doesn't provide an API.
Any suggestion ?

Thanks

**Comment by geier** [comment]
You can try to read it in with [icalendar](https://github.com/collective/icalendar), this is the library that khal uses. It's not guaranteed to be a valid ics file, but at least it should work with khal if icalendar doesn't complain.

**Comment by eoli3n** [comment]
Thanks
