### ISSUE TITLE
`ikhal` not respecting `{calendar}` in `agenda_event_format`

### ISSUE THREAD

**Issue by dpaetzel** [pimutils/khal#1121]
First of all: Thank you for making and maintaining `khal`. I use it everyday!

According to [the docs](https://lostpackets.de/khal/configure.html#the-view-section), setting

```
agenda_event_format = {calendar-color}{cancelled}{start-end-time-style} ({calendar}) {title} [{location}]{repeat-symbol}{reset}
```

should be respected by both `khal list` and `ikhal`. However, in `ikal`, I only get output such as this:

```
<calendary stuff>    Today (2022-04-08)
…                    8:00-15:00 () Open issue for ikhal [living room]
</calendary stuff>
```

Note the empty parentheses in the “Open issue for ikhal” event. I would've expected to have the name of the calendar there since `agenda_event_format` specifies `({calendar})` (which *does* work as expected in `khal list`).

**Comment by zaphod1234** [comment]
I can confirm that behavior. I was going to log an issue, but see you already beat me to it.

**Comment by geier** [comment]
Thanks for reporting!

Should be fixed in master.
