### ISSUE TITLE
Contact birthdays don't show up in khal

### ISSUE THREAD

**Issue by nicemicro** [pimutils/khal#1179]
I've ran into the weirdest behavior in khal.

I am running khal 0.10.5 on Arch Linux.

The events in the contact_birthdays calendar don't show up in `khal list`, `khal calendar` or `ikhal`.

My setting for the contact birthdays calendar in the config file is:
```
[[contact_birthdays]]
path = ~/.local/share/calendars/contact_birthdays
type = "birthdays"
```
I have copied one of the .ics files from the referenced path to a directory of an other calendar, and then that event showed up. I was quite convinced that I'm misconfiguring something, but commenting out the type line didn't help. Out of frustration, I have changed the name of the calendar to "suff":
```
[[stuff]]
path = ~/.local/share/calendars/contact_birthdays
type = "birthdays"
```
And suddenly, the events show up in `khal list`, `khal calendar` and `ikhal`, too.

For every other calendar, the name of the calendar doesn't matter, I renamed "work" to "antiwork", and events still show up. After that, I have changed "stuff" to "work" (the calendar previously known as "work" was "antiwork" this time), and... the birthday events disappeared. If I rename "work" to "contact_birthdays", my work events do not disappear.

I tried many different names and got some weird result. What I figured out in the end:
if I comment out to `#type = "birthdays"` part, AND also change the name of the calendar, then events show up, and keep showing up, even after uncommenting `type = "birthdays"`. What's even more interesting, is that when I then rename the calendar to something that did not work previously, events disappear, and then renaming back to the previously working name, events don't appear.

Now, the next thing I'll need to test is what happens after I reboot the system.
Edit: seems to be working (events showing up) after reboot.

**Comment by d7415** [comment]
Hi.

`type = "birthdays"` tells khal to look for .vcf (contact) files and ignore .ics files. https://khal.readthedocs.io/en/latest/configure.html?highlight=birthdays#the-calendars-section

I suspect the continued working after changing the type back is mostly due to caching, but the behaviour when it was named "stuff" seems strange.

**Comment by d7415** [comment]
Thanks for reporting back!
