### ISSUE TITLE
Change blue background

### ISSUE THREAD

**Issue by ghost** [pimutils/khal#1219]
How can I change the blue background to another color?

![image](https://user-images.githubusercontent.com/118444583/214595853-7623488f-ad5f-4406-9e7d-27d034bc14a9.png)

By reading the docs it looks like I have to change source files?

What is the right option I have to change?

**Comment by Tonus1** [comment]
Hi

Do you mean the terminal background or the input fields ?

If you launch khal in a specific virtual terminal, you could try to 
change the color profile in your command.

On Wed, Jan 25, 2023 at 06:54:38AM -0800, Punktor wrote:
>How can I change the blue background to another color?
>
>![image](https://user-images.githubusercontent.com/118444583/214595853-7623488f-ad5f-4406-9e7d-27d034bc14a9.png)
>
>By reading the docs it looks like I have to change source files?
>
>What is the right option I have to change?
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/issues/1219
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>

-- 
Regards,

Tonus

**Comment by 875d** [comment]
I mean the input fields.

The terminal background is not khal responsibility.

I did it with:

```
diff --git a/khal/ui/colors.py b/khal/ui/colors.py
index 3ed45f5..19ea655 100644
--- a/khal/ui/colors.py
+++ b/khal/ui/colors.py
@@ -43,7 +43,7 @@ dark = [
     ('dayname', 'light gray', ''),
     ('monthname', 'light gray', ''),
     ('weeknumber_right', 'light gray', ''),
-    ('edit', 'white', 'dark blue'),
+    ('edit', 'white', 'black'),
     ('alert', 'white', 'dark red'),
     ('mark', 'white', 'dark green'),
     ('frame', 'white', 'black'),
```

Altough I don't understand what the edit in line 29 does. Is it just getting overwritten by the one in line 46?

I think the documentation should be much more clear on how to change the colors.

And not also what the fields mean. It looks like the second element of the tuple is the foreground, and the third element the background.

I also don't know what are the admissible values in those fields.

It seems it won't accept "dark green" as the foreground for some reasons.

I think khal should be themed via the config file.

**Comment by tgy** [comment]
same problem here. the ikhal colors are really not great, as this light blue with grey text on top is completely unreadable. theming should indeed be done in the config

**Comment by geier** [comment]
Please see (and comment on) #1279 if you are interested in this.

**Comment by geier** [comment]
With  #1279 you could put 
```
[palette]
edit = '', '', 'bold', '#FF00FF', '#12FF14'
```
in your config file and with this beautiful setup:
<img width="682" alt="image" src="https://github.com/pimutils/khal/assets/275330/30dd7ef7-5c8e-4865-8d9b-1565dc5a9e80">

**Comment by tgy** [comment]
thanks @geier that looks pretty neat.
