### ISSUE TITLE
Get message "khal only supports python version 3.8+" but Python 3.10.6 already installed and default

### ISSUE THREAD

**Issue by corrilan** [pimutils/khal#1227]
Hello

I have successfully installed and tested khal on my Ubuntu laptop which happened to have Python 3.10.6.

I am now trying to get khal installed on a Raspberry Pi which had Python 3.7.  I encountered the message:

"khal only supports python version 3.8+. Please Upgrade." when running "sudo ./setup.py install"

I downloaded and installed Python 3.10.6 and have confirmed it is the default as "python -V" outputs "Python 3.10.6".

But I still get the message:

"khal only supports python version 3.8+. Please Upgrade."

What am I missing?

Regards

Jason

**Comment by d7415** [comment]
My first thought is that setup.py is calling a different version of python.

- How did you install the new version? Was it system-wide?
- Does `sudo python -V` give the same version number?
- Does `sudo /bin/env python3 -V` give the same version number?

**Comment by corrilan** [comment]
Installed from source package.
sudo python -V gives the newly installed version
sudo /bin/env python3 -V gives "sudo: /bin/env: command not found"

**Comment by corrilan** [comment]
I think I have sorted it now after you pointed me in the right direction, thanks.
I had to run:

sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10

I had previously run:

sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.10

**Comment by d7415** [comment]
That looks like the one!

Thanks for documenting it for the next person :)
