### ISSUE TITLE
Scheduling hooks/commands based on CalDAV events?

### ISSUE THREAD

**Issue by poisonborz** [pimutils/khal#1230]
This isn't much of a bug report or feature request, but a general question if Khal can/could do this (along with `calcurse`, it's one of the few command line calendar tools).

I'd need to schedule commands based on calendar events (specifically from a CalDAV server) - similarly to cron jobs. A command should simply execute at the start time of each event, with the event title available to the command (eg. as an argument). I previously did this via IFTT, but I'd need a selfhosted/local solution.

Would this be somehow achieveable with Khal, or is this something that could be added?

**Comment by WhyNotHugo** [comment]
Khal will only operate on local filesystem collections. If you have your events in caldav, you need to synchronized them into a local filesystem first. [vdirsyncer](https://github.com/pimutils/vdirsyncer/) does exactly that.

That said, I don't think khal can do this directly, but you can pipe khal's output to a script that does the rest of the work. E.g.: `khal list` will pipe to stdout the upcoming events like so:

```
Monday, Mon 2023-03-13
11:00-11:30 Dentist checkup (R. Fletterman)
Tuesday, Tue 2023-03-14
18:30-19:00 Violin lessons ⟳
```

Parsing that is probably **a lot** simpler than parsing the icalendar files yourself.

**Comment by WhyNotHugo** [comment]
If what you want is to show alarms for the `VALARM` component in events, then you probably want to look at https://github.com/pimutils/khal/issues/148

**Comment by WhyNotHugo** [comment]
There's also some good reference scripts in that issue.

**Comment by poisonborz** [comment]
Thanks a lot, these are good hints! (and I'm still a bit perplexed how there isn't a more readymade solution for this seemingly basic use case)
