### ISSUE TITLE
Please make new release

### ISSUE THREAD

**Issue by polyzen** [pimutils/khal#1232]
We're currently going through a rebuild to get Python 3.11 out to Arch. If trunk is in a good state, a new release would be appreciated, especially so we don't have to try to backport fixes to get the current release to pass its tests. 🚀

**Comment by WhyNotHugo** [comment]
I'm not aware of any regressions on `master`. @geier ?

**Comment by polyzen** [comment]
Cross-referencing https://bugs.archlinux.org/task/78227

**Comment by d7415** [comment]
There have been a couple of requests, and it's been a while. If I don't hear any objections I'll release 0.11.0 tomorrow.

**Comment by WhyNotHugo** [comment]
@d7415 :+1:

**Comment by d7415** [comment]
v0.11.1 is now on PyPI.
