### ISSUE TITLE
Can the Labels „Today“ and „Tomorrow“ be changed?

### ISSUE THREAD

**Issue by pk2061** [pimutils/khal#1246]
Hi,

is it possible to change the two labels „Today“ and „Tomorrow“ into a different text or another language?

In my case it would be nice to be able to change it to „Heute“ and „Morgen“ (German).

Thanks a lot for the tool and the work you put into it!

**Comment by btwe** [comment]
Not by configuration as far as I see it. See function [https://github.com/pimutils/khal/blob/master/khal/ui/__init__.py#L122](https://github.com/pimutils/khal/blob/master/khal/ui/__init__.py#L122)

**Comment by geier** [comment]
No, currently not. Help is wanted though, see https://github.com/pimutils/khal/issues/1203 if somebody wants to tackle it.
