### ISSUE TITLE
Permissive parsing of DELTA

### ISSUE THREAD

**Issue by madduck** [pimutils/khal#1285]
I often enter the DELTA using `khal add` with a leading plus, e.g. because it's how stuff works in TaskWarrior, among others. So: `khal add tomorrow 10:00 +90m Test`, but this generates an event with title "+90m Test".

My suggestion would be to swallow a leading `+` in what might be a DELTA value, and try both.

Happy to try to submit a patch.

**Comment by WhyNotHugo** [comment]
I think that this sounds pretty sensible.
