### ISSUE TITLE
[feature request] allow disabling mouse input

### ISSUE THREAD

**Issue by 07416** [pimutils/khal#1289]
from the `man` page:

>    interactive
> invokes  the  interactive version of khal, can also be invoked by calling ikhal. While ikhal can be used entirely with the keyboard, some elements respond if clicked on with a mouse (mostly by being selected).

I don't use the mouse with any application which can be used entirely with the keyboard. For instance `htop` and `fzf` have an option (a flag) to disable mouse support.

```
fzf --no-mouse
htop --no-mouse
```

**Comment by WhyNotHugo** [comment]
Does the mouse-grabbing behaviour bother in some way?

**Comment by 07416** [comment]
> Does the mouse-grabbing behaviour bother in some way?

In every program it does to some degree, yes. I mainly have mouse plugged in the first place since it or some form of pointer device is mandatory for modern web browsing and DEs (including Gnome).

Disabling the feature may also lower to overhead to a minor degree.

**Comment by tgy** [comment]
I've opened a PR to fix this.
