### ISSUE TITLE
Khal generates empty CATEGORIES: property in ics files

### ISSUE THREAD

**Issue by thibaut-ient** [pimutils/khal#1300]
**Describe the bug**
When editing an existing event, or when creating it in ikhal, the resulting .ics file contains an empty "CATEGORIES:" line.
This does not happen when using `khal new`.
This prevent the incriminated events to get synchronized to some servers using vdirsyncer

**To Reproduce**
Simply create or edit an event in ikhal and observe a "CATEGORIES:" line in the resulting file.

**Expected behavior**
ikhal shoudn't write out that line if there is no categories information?

**OS, version, khal version and how you installed it:**
khal, version 0.11.2
from Arch OS repos
Python 3.11.3
OS Archlinux

**Comment by WhyNotHugo** [comment]
As I mentioned on IRC: I did a quick read of the icalendar RFC, and it seems that CATEGORIES: must have at least one category; an empty label doesn’t seem to be valid.

I guess that servers could be lenient and allow this, but strictly speaking, the ics file is not valid.

**Comment by WhyNotHugo** [comment]
I thought this sounded familiar, we already had this issue in the past: https://github.com/pimutils/khal/issues/453

**Comment by titibandit** [comment]
Is there anything that speaks against merging that pull request?
