### ISSUE TITLE
Remove requirements.txt?

### ISSUE THREAD

**Issue by untitaker** [pimutils/khal#131]
Tox installs khal's dependencies as specified in `setup.py`. Is there a need for this file?

**Comment by geier** [comment]
actually, I have no idea if this is needed or not. I have read several
blog posts about the differences between requrirements.txt and
requirements in a config file but I don't think I ever got it (at least
I cannot remember that). If it is not actually needed, I am more than
happy to see it gone.

Quoting Markus Unterwaditzer (2014-11-27 15:20:50)
