### ISSUE TITLE
vcf birthdays not registered

### ISSUE THREAD

**Issue by vanya-robertson** [pimutils/khal#1314]
The lines:
```
[[birthdays]]
path = /home/jcrtf/.local/share/khard/
type = birthdays
readonly = True
color = light blue
```

do not make my contacts' birthdays visible in khal.

I am using khal version 0.11.2 and khard version 0.18.0. My contacts are VCARD 4.0, stored in `~/.local/share/khard/{archive,business,family,friends}`.

This has been niggling me for a while. Any help would be very much appreciated.

Thanks,
 Vanya

**Comment by geier** [comment]
Give it a try with `path = /home/jcrtf/.local/share/khard/friends/` and so on. We do not currently search subfolders.

**Comment by vanya-robertson** [comment]
Perfect. Thank you!
