### ISSUE TITLE
Can't find config in XDG_CONFIG_HOME in v0.11.2

### ISSUE THREAD

**Issue by Robert-Ernst** [pimutils/khal#1325]
I'm trying to just use the XDG_CONFIG_HOME location for the khal config file.
If I point with the  -c command at the config file in the  XDG_CONFIG_HOME location it will work.
Steps and errors are shown below:

`lsb_release -a`
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

`echo $XDG_CONFIG_HOME`
/home/xxx/.config

`khal --version`
khal, version 0.11.2

`khal list`
critical: Cannot find a config file. If you have no configuration file yet, you might want to run `khal configure`.

`khal configure`
critical: Found an existing config file at ~/.config/khal/config.
critical: If you want to create a new configuration file, please remove the old one first. Exiting.

**Comment by Robert-Ernst** [comment]
@WhyNotHugo

**Comment by WhyNotHugo** [comment]
I cannot reproduce this.

```console
> echo $XDG_CONFIG_HOME
/home/hugo/.config  
> khal list
...
> khal configure
critical: Found an existing config file at ~/.config/khal/config.
critical: If you want to create a new configuration file, please remove the old one first. Exiting.
```

What is the output of `file ~/.config/khal/config` and `ls -l ~/.config/khal/config`?

**Comment by Robert-Ernst** [comment]
As I've mentioned the config itself is working if I use the parameter with -c. But it doesn't find it via the default $XDG_CONFIG_HOME path. The change I did was from using a custom path config file to try to use the default $XDG_CONFIG_HOME path

`ls -l ~/.config/khal/config`
-rw-r--r-- 1 xxx xxx 429 Jan 11 11:05 /home/xxx/.config/khal/config

`file ~/.config/khal/config`
/home/xxx/.config/khal/config: ASCII text


cat /home/xxx/.config/khal/config
```
[calendars]

[[private]]
path = /mnt/xxx/khal/private
type = calendar

[[secondcalendar]]
path = /mnt/xxx/khal/secondcalendar
type = calendar

[locale]
timeformat = %H:%M
dateformat = %Y-%m-%d
longdateformat = %d %B %Y
datetimeformat = %d %B %Y %H:%M
longdatetimeformat = %d %B %Y %H:%M

[default]
default_calendar = private
```

@WhyNotHugo

**Comment by WhyNotHugo** [comment]
I can't reproduce the issue, and looking through the code I don't see any hints as to what could be failing.

**Comment by Tonus1** [comment]
Shot in the dark : 
Could it be you had an alias you forgot that could be interfering ?

**Comment by WhyNotHugo** [comment]
Nope.

How did you install khal?

**Comment by Robert-Ernst** [comment]
@Tonus1 That was a great shot in the dark!

I checked my aliases and in fact I configured it with the -c command with the old location of my config file. So the problem occured when I moved it from the custom location and put it into the $XDG_CONFIG_HOME path.
It's working now.

Thank you for the swift replies!
