### ISSUE TITLE
khal doesn’t seem to recognize my calendar entries

### ISSUE THREAD

**Issue by fqxp** [pimutils/khal#1355]
**Describe the bug (or incorrect usage)**
I have synchronized calendar events from my Nextcloud instance using vdirsyncer. Events do get copied into `~/.local/share/calendars/nextcloud`.

Here's an example event (I only added the `.txt` extension to be able to upload it here): [8c5638be-f5f4-4dc6-ae01-54abc4e7df0c.icf](https://github.com/user-attachments/files/15901251/8c5638be-f5f4-4dc6-ae01-54abc4e7df0c.icf.txt) which is located inside ~~`~/.local/share/calendars/nextcloud`~~`~/.local/share/calendars/nextcloud/persnlich-2`, among lots of other events.

Here’s my `~/.config/khal/config`:
```
[calendars]
  [[nextcloud]]
  path = ~/.local/share/calendars/nextcloud/persnlich-2
```

When I run `khal list now 14d` or `khal calendar now 14d` today (2024-06-19), no events are printed, although the above event is inside the range. Other dates and ranges yield the same result. No event is ever printed.

The [debug output](https://github.com/user-attachments/files/15901336/khal-list-debug.txt) seems unsuspicious to me.

**To Reproduce**
* put the above ical file in `~/.local/share/calendars/nextcloud/persnlich-2`
* run `khal list 19.06.2024 14d` (in DE locale)

**Expected behavior**
I should see the calendar events of the next 14 days.

**OS, version, khal version and how you installed it:**
 - khal, version 0.11.3
 -  installed via apt from Debian testing
 - python version: 3.11.9
 - OS: Debian testing
 - `~/.config/khal/config`: 
```
[calendars]
  [[nextcloud]]
  path = ~/.local/share/calendars/nextcloud/persnlich-2
```

**Comment by WhyNotHugo** [comment]
Based on your configuration, khal will treat `~/.local/share/calendars/nextcloud/persnlich-2` as your calendar, but in your reproductions steps you mention that you put the ical file in the parent directory.

**Comment by fqxp** [comment]
> Based on your configuration, khal will treat `~/.local/share/calendars/nextcloud/persnlich-2/` as your calendar, but in your reproductions steps you mention that you put the ical file in the parent directory.

I’m sorry, that was a mistake in my question. Fixed that in the original question.

**Comment by d7415** [comment]
It may be another typo, but does your entry have a `.icf` extension? (rather than `.ics`)

**Comment by fqxp** [comment]
> It may be another typo, but does your entry have a `.icf` extension? (rather than `.ics`)

That’s it! For some reason I used a `.icf` extension when syncing. Renamed the files and it worked. Thanks for spotting this user error!
