### ISSUE TITLE
--format: undocumented formatting options

### ISSUE THREAD

**Issue by stupidcomputer** [pimutils/khal#1359]
Hi there,

I was writing a script and I was trying to filter my events by category, so I wrote something like
```sh
$ khal list today today --format "{categories} {title}"
```
I looked at the [man page](https://man.archlinux.org/man/khal.1#format) for khal and I noticed that the `{categories}` format specifier isn't documented.
Some things I wonder:

  - Are there more undocumented --format specifiers?
  - Can we change the man page to be accurate?

I'd be more than happy to submit a PR re: this.

**Comment by WhyNotHugo** [comment]
In khal/khalendar/event.py, for the `class Event`, in function `def attributes`, starting at around line 636, you'll see dozens of lines in the form of:

    attributes["start"] = ...

If I understand the code correctly, all these are the attributes available for formatting.

**Comment by geier** [comment]
> If I understand the code correctly, all these are the attributes available for formatting.

correct.

**Comment by stupidcomputer** [comment]
Making a list here just for reference:

Formatting options we do have documented:
- [x] title
- [x] description
- [x] description-separator
- [x] uid
- [x] start
- [x] start-long
- [x] start-date
- [x] start-date-long
- [x] start-time
- [x] end
- [x] end-long
- [x] end-date
- [x] end-date-long
- [x] end-time
- [x] repeat-symbol
- [x] alarm-symbol
- [x] location
- [x] calendar
- [x] calendar-color
- [x] start-style
- [x] to-style
- [x] end-style
- [x] start-end-time-style
- [x] end-necessary
- [x] end-necessary-long
- [x] status
- [x] cancelled
- [x] organizer
- [x] url
- [x] *colors*
- [x] nl (newline)
- [x] tab
- [x] bell

Stuff that appears to be missing
- [ ] repeat-symbol
- [ ] repeat-pattern
- [ ] alarm-symbol
- [ ] status-symbol
- [ ] partstat-symbol
- [ ] all-day
- [ ] url-seperator
- [ ] categories

One of these days when I'll free I'll write a PR to merge documentation for all of these options in.

**Comment by stupidcomputer** [comment]
I just realized -- I was looking at the `usage.rst` on main and the man page on my machine: I'm running tag 0.11.3 but there were some changes merged into the man page since then that I haven't gotten, and so as a result, I don't have the update man page. Maybe time to press the release button?
