### ISSUE TITLE
Example of a config file for all cool visual effects of the example of displayed in the first main github page

### ISSUE THREAD

**Issue by bjce** [pimutils/khal#1368]
Hello

A big thank you to all the developpers/maintainers of khal which I started to use heavily for a few days as my agenda. I know it is not a bug and I am sorry to pollute the issue section but I could not find this information in the documentation. I would like to know if it is possible to have an example of the config file which enabled to display khal (in interactive mode I guess) as it is displayed in the first main github page:

https://github.com/pimutils/khal

Many thanks in advance

Best regards

![Screenshot from 2024-11-12 10-42-30](https://github.com/user-attachments/assets/645308ff-5343-4cbf-97d6-4282436556fe)

**Comment by bjce** [comment]
Hi @Tonus1. Many thanks for your comment.  Colors on the dates  would be the most interesting feature. But I would be interested in any other piece of information.

**Comment by Tonus1** [comment]
The colors are from the calendars (you can keep the server's config or change in each calendar config).

The icons depends on the font you use for the (virtual) terminal.

From the latest (git?) versions you can write a theme. 
See :
https://github.com/geier/khal_gruvbox

**Comment by bjce** [comment]
Mmh, I see. thank you for your feedback. I added the following line :
```
[view]
theme = gruvbox
```
installed the package with the command : 

```
pip install git+https://github.com/geier/khal_gruvbox@importlib
```
but got the error: 
```
critical: config error:
critical: in [view] theme: the value "gruvbox" is unacceptable.
If your configuration file used to work, please have a look at the Changelog to see what changed.
```
I guess this might be because I installed khal with `sudo apt-get install khal` (on Linux-debian distro) and not the master version. So maybe I need to wait a bit. What do you think?

**Comment by Tonus1** [comment]
Since the last release is from February and the issue where this is mentioned is from March iirc, I guess master branch is ahead from your khal version (you didn't mentioned)....

Maybe ask for new release or compile master branch from recent commit ?

**Comment by bjce** [comment]
ok thank you for your comment. My version was the default version of the apt package manager for linux mint which I uninstalled. I then installed khal in a python environnment (which installed version 0.11.3). I this environnment I then ran the commen `pip install git+https://github.com/geier/khal_gruvbox@importlib` and ran the command `ikhal` but that gave me the following error message:
```
critical: config error:
critical: in [view] theme: the value "gruvbox" is unacceptable.
```

**Comment by Tonus1** [comment]
For now the theme in [view] section can only have values `dark` and `light`.
See documentation here : [readthedocs](https://khal.readthedocs.io/en/latest/configure.html)
```
theme

    Choose a color theme for khal.

    Khal ships with two color themes, dark and light. Additionally, plugins might supply different color schemes. You can also define your own color theme in the [palette] section.

        type:

            string
        default:

            dark
```

**Comment by bjce** [comment]
Ok thank you for your feedback @Tonus1 
Is there a way to specifically color the day with the same color of an event scheduled on this day. For example: in the screenshot on the first post of the question, there is an event "Beer" at 22:00 in green. Accordingly this day is green. Is it possible to configure this?

**Comment by bjce** [comment]
Ok I just read the doc (https://khal.readthedocs.io/en/latest/configure.html#help-with-initial-configuration) more carefully. This is what worked in the config file: 

```
[default]
default_calendar = private_hour_scheduled
highlight_event_days = True

[highlight_days]
  color = dark red

```
