### ISSUE TITLE
human-friendly uids

### ISSUE THREAD

**Issue by geier** [pimutils/khal#153]
short, human-friendly uids (as an extra, not instead of their original uid) would be nice for identifying events, they could be used for, e.g. deleting an event or printing its details, search could print them etc.

example: `2015-02-03-1600-awesome-idea`

**Comment by untitaker** [comment]
The way I solved this in [mates](https://github.com/untitaker/mates.rs) is to let the user provide the filepath or an arbitrary search string (that has to yield exactly one result).
