### ISSUE TITLE
Split calendar and event editor

### ISSUE THREAD

**Issue by hobarrera** [pimutils/khal#179]
Hi,

This is more of a "discussion" ticket than an actual issue/feature request. I'd actually even like to work on this myself if I know this'll be accepted as a PR.

Currently khal is two things:

 1. A calendar/agenda.
 1. An events editor (or a vcf editor, if you will).

I'm interested in spliting these things in two different binaries (keeping them them same for now, UI-wise, and likely reusing all existing code), and have calendar.bin invoke the event-editor.bin when the user wants to edit/create an event.

From the end-user PoV, this would be almost the same, with one main difference which is what I'm aiming at: which calendar editor program to use should be configurable. My long-term interest is to write a different one (though `vim` would be an acceptable alternative, for example), and configure khal to use that, so when the user edits an event, that program can be called instead.  
This more closely follows the unix-philosophy of "do one thing and do it well" (kinda like a file browser vs file editor if you will), but also makes room for various external vcf-editors.

Mostly my aim with this issue here is to ask:

 * Would these changes would be accepted (in the form of a PR, most likely)?
 * Do you have any feedback regarding this propositon?

Thanks.

**Comment by hobarrera** [comment]
Huh, looks like this would also cover #31.

**Comment by untitaker** [comment]
I think that's a great idea, however, I'm not sure how to implement the calendar selector that's currently part of the editor.

**Comment by hobarrera** [comment]
I forgot about that, and now I recall that I had that same though last night before I fell asleep, hah.

Probably an intermediate step when creating the event, with the following flows:

For creations:

 1. Open ikhal.
 1. Select a date.
 1. Press `n`.
 1. A calendar selection menu appears.
 1. The event-editor is summoned.

For editing events, simply set a new hotkey for calendar selection (`c`?). It would show the same screen as the one shown when selecting a calendar for a new event.

This *would* actually alter the flow of event creation/modification, contrary to the my inital statement.

I'd leave the calendar selection out of the event-editor, since it should only be concerned with editing a vcf file, and calendar selection is more about where to save that file instead.

**Comment by geier** [comment]
I'm all for that "do one thing only, but do it well". But when creating or more importantly when editing an event I'd really like to see other events scheduled for that day(s). ikhal doesn't do that well at the moment either, but I think it will be more difficult with creating two different tools.

As a compromise I would like to suggest the following:

* make using an external editor optional (configurable via the config file)
* if anyone wants to use the current editor for something else we can extract it rather easily

**Comment by geier** [comment]
I'll close this in favor of #31
