### ISSUE TITLE
Parse out other events similar to 'birthday'

### ISSUE THREAD

**Issue by mathstuf** [pimutils/khal#243]
I see `X-ANNIVERSARY` tags at least. There are probably others in use too.

**Comment by d7415** [comment]
`X-ABDATE` also springs to mind - Google uses it, for example.

I'm considering having a go at this. My initial plan was to review `update_birthday()` in `khal/khalendar/backend.py` and expand it and/or copy it as applicable (then adjust tests/docs/etc as appropriate).

Does this make sense to the authors?

**Comment by geier** [comment]
@d7415 welcome! Sure, go ahead. Depending on your programming experience, you might want abstract it a bit, so that we don't need a new method for every property. Otherwise a copy of `update_birthday()` is fine, too.
