### ISSUE TITLE
Birthdays do not end on the correct day

### ISSUE THREAD

**Issue by libre-man** [pimutils/khal#244]
Birthdays that are imported from vcards are still occurring according to to _at_ after the birthday and do not start at the beginning of the birthday.

My timezone is Europe/Amsterdam and a birthday that is set at 2015-08-10 starts at 2:00 2015-08-10 and ends at 1:59 2015-08-12.

The vcard:
```
BEGIN:VCARD
VERSION:3.0
X-ANDROID-CUSTOM:vnd.android.cursor.item/nickname;[REDACTED];;;;;;;;;;;;;;
X-RADICALE-NAME:6a9f3951-72ac-4f4f-a22d-1e72a45d8931
X-PRODID:ez-vcard 0.9.6
X-DAVDROID-STARRED:1
UID:168e6df8-6f8e-4334-9cb3-1e942364f0f5
FN:[REDACTED]
N:[REDACTED]
TEL;TYPE=cell,pref:[REDACTED]
EMAIL;TYPE=work,pref:[REDACTED]
ADR;TYPE=[REDACTED]
LABEL;TYPE=[REDACTED]
URL:[REDACTED]
BDAY:2015-08-10
PHOTO;ENCODING=b;TYPE=jpeg:/[REDACTED]
PRODID:DAVdroid/0.8.2 (ez-vcard/0.9.6)
REV:20150809T222544Z
END:VCARD 
```

And the Vevent from the khal database:
```
BEGIN:VEVENT
SUMMARY:[REDACTED]
DTSTART;VALUE=DATE:20150810
DTEND;VALUE=DATE:20150811
UID:168e6df8-6f8e-4334-9cb3-1e942364f0f5.vcf
RRULE:FREQ=YEARLY
END:VEVENT
```

**Comment by geier** [comment]
if this is indeed *your* birthday: happy birthday! (just two days late) :birthday:  . I'll have a look later this week.

**Comment by geier** [comment]
could you delete your khal.db and see if the bug is still there?

**Comment by libre-man** [comment]
No it was not my birthday, but thank you.

The problem still exists after deleting khal.db

**Comment by geier** [comment]
what version of khal are you on? I cannot reproduce this currently.

**Comment by libre-man** [comment]
I'm on khal, version v0.6.1.dev83+ngb056442

On Mon, Aug 31, 2015 at 02:23:09PM -0700, Christian Geier wrote:
> what version of khal are you on? I cannot reproduce this currently.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/geier/khal/issues/244#issuecomment-136505864

-- 
Zorg dat e-mail echt privé is: onderteken en/of versleutel uw antwoord met 
OpenPGP.

**Comment by geier** [comment]
hmm, still cannot reproduce this.

**Comment by geier** [comment]
Does it show correctly for *khal agenda*?

**Comment by libre-man** [comment]
Yes khal agenda does show the birthday at the correct day.

**Comment by geier** [comment]
Ok then, I guess this is due to the idiotic way ``agenda``  and ``at`` behave at the moment. ``agenda`` (``at``) should only accept dates(datetimes), but ``at`` also accepts datetimes ATM.

**Comment by geier** [comment]
closed because nobody seems to have observed this issue since the backend has been rewritten.
