### ISSUE TITLE
Move term cursor

### ISSUE THREAD

**Issue by untitaker** [pimutils/khal#247]
Private email from a blind person:

```
Also ikhal now works. However, it's not conveninent to use with a           
braille display, as the cursor is always sitting at the bottom line.        
Could it be changed so that the cursor follows the arrow keys, e.g.         
the cursor goes from date to date with the arrows?                          
```

**Comment by geier** [comment]
I do not completely understand the question yet, because I believe the cursors is currently following the arrow keys. Do have a better understanding of the problem?

**Comment by untitaker** [comment]
I don't really know, I suppose the actual terminal cursor is hidden by urwid and instead the relevant section is highlighted.

On 17 August 2015 21:53:00 CEST, Christian Geier <notifications@github.com> wrote:
>I do not completely understand the question yet, because I believe the
>cursors is currently following the arrow keys. Do have a better
>understanding of the problem?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geier/khal/issues/247#issuecomment-131942078

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
From: Lars Bjørndal <lars@lamasti.net>
    To: Markus Unterwaditzer <markus@unterwaditzer.net>
    Subject: Re: Khal (was: Re: Vdirsyncer and DavMail)
    User-Agent: Mutt/1.5.23 (2014-03-12)

    Hei, Markus!

    On Fri, Aug 14, 2015 at 06:20:36AM +0200, Markus Unterwaditzer wrote:
    > Hello Lars,
    >
    > Glad to hear everything works now. Regarding the cursor thing, I'm not sure
    > that is easy to fix. I've filed a bug though.

    I asked at the BRLTTY community mailing list, if BRLTTY could handle
    this issue. They saied they couldn't. They also told me that khal is
    using the urwid Python module to handle the interactive interface. I
    talked to the urwid developers on irc, and they say the cursor
    tracking feature is disabled in may programs.

    I'm not sure this helps, but I thought I should mentiion it.

    Thank you and regards,

    Lars

**Comment by untitaker** [comment]
I'm cc-ing @larsbjorndal, the original author of this issue, to keep him up-to-date on progress.

**Comment by geier** [comment]
I'll look into it.

**Comment by larsbjorndal** [comment]
Hi, developers!

Markus Unterwaditzer <notifications@github.com> writes:

> I'm cc-ing @larsbjorndal, the original author of this issue, to keep
> him up-to-date on progress.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/geier/khal/issues/247#issuecomment-160201621

Have there been any progress in fixing this issue? I'm using khal a lot,
and it works perfectly from the command line. However, I'm not able to
delete events. That must be done from the interactive mode, that I cannot
access with my braille display. Hope the cursor issue could be worked on.

Thanks and regards, Lars

**Comment by geier** [comment]
Sorry that this is taking so long. I'll ask the urwid people again on how to do this and see if we can make any progress on this soon (I did a year ago, but forgot what they told me...).

Perhaps @younmoney wants to implement a `delete` command similar to the new `edit` command?

**Comment by geier** [comment]
Sorry that this is taking so long. I'll ask the urwid people again on how to do this and see if we can make any progress on this soon (I did a year ago, but forgot what they told me...).

Perhaps @younmoney wants to implement a `delete` command similar to the new `edit` command?

**Comment by larsbjorndal** [comment]
Thank you. A delete command is fine, but beeing able to navigate in
the calendar interactively would be more efficient, I think, for working with a
calendar in general.

Thanks and regards, Lars

**Comment by geier** [comment]
I've given something a try, could you perhaps clone branch `feature_show_cursor` and see if this is the kind of "cursor showing" we are talking about?

**Comment by larsbjorndal** [comment]
Hi, Christian!

Thank you for investigating!

I'm using khal/vdirsyncer from a python3 virtual environment. Is it
possible that I could try your test code using 'pip install --upgrade khal' to
test? Or do you have tips in other ways to use the code from within
the virtenv?



Thanks and regards, Lars

**Comment by larsbjorndal** [comment]
Hello, Christian!

Apologize for my novice question about how to install the branch. I
did it with 'python3 setup.py install' in the virtenv.

And to your question:

> I've given something a try, could you perhaps clone branch
> feature_show_cursor and see if this is the kind of "cursor showing" we
> are talking about?

Yes, it is! This is awesome!

Lars

**Comment by geier** [comment]
No worries about the question, sorry for the lag. If the cursor is not shown anywhere, please report back. 

While I'm not used to the blinking cursor yet, it can be probably be used to help show which part is active for everybody. I guess I'll merge this soon and deal with improvement suggestions later.

**Comment by geier** [comment]
included in current master.

**Comment by larsbjorndal** [comment]
Thank ou!

Lars

**Comment by geier** [comment]
You are welcome. Please file a new bug if it disappears again (or send me an email directly).
