### ISSUE TITLE
Feature request: Hide past events

### ISSUE THREAD

**Issue by matthiasbeyer** [pimutils/khal#272]
There should be an option to hide past events on the same day.

For example, if I had an event today until 11am, but now it is 1pm, the event should be hidden.

Should require a commandline argument or configuration file flag.

**Comment by geier** [comment]
Thank you for another good idea (which I'm very slow too implement, I know). A want to rethink how ``agenda`` and ``at`` work, and this should definitively be regarded.

**Comment by matthiasbeyer** [comment]
@geier No problem. I think that bug fixes are more critical and I really would like if these existing bugs would be fixed asap. Additional functionality is just a "nicetohave" for me.

I would contribute myself, but I'm absolutely not a python guy, so I put my effort into other libraries and tools where I can help more.

**Comment by geier** [comment]
@matthiasbeyer  do you know of any more open ones than [these](https://github.com/geier/khal/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abug)?

**Comment by matthiasbeyer** [comment]
@geier Yes and I have a friend which already fixed one locally for his machine. I will show him how to submit a PR this evening. Stay tuned.

**Comment by youngmoney** [comment]
this option is available in the new list command in master, `--notstarted` will hide all events not starting in the future
