### ISSUE TITLE
How should at and agenda work?

### ISSUE THREAD

**Issue by geier** [pimutils/khal#273]
Please post your ideas on how to improve on the current situation of ``at`` and ``agenda``. Do we need two commands? What arguments should they accept, what should they print, etc.

Also see #93 and #231.

**Comment by matthiasbeyer** [comment]
* Command: `agenda`
    * `--help`
    * `--events n` - a working version please
    * `--days n`
    * `--calendars ...` - To select which calendars are shown
    * `--not-calendars ...` - To exclude calendars
    * `--json` - To print results as JSON
    * `--grep key=value,key=value` - List for grepping in a field (for example "SUMMARY" from the ical files) for a certain value. Additionally not a list of `key=value` pairs but something with `or` and `and` logical operators
    * `--before-time` - All events which start/end before a certain daytime
    * `--after-time` - All events which start/end after a certain daytime

I like the current output of the `agenda` command, though it could use some styling, some blank lines after the events of one day, some more table-ish style, where you can see things more instantly.

---

I never used the `at` command.

**Comment by untitaker** [comment]
I also never used the at command.

I'd like to see as many UI config params as possible deprecated, and only allow configuration through CLI options.

On 3 October 2015 21:31:28 CEST, Matthias Beyer <notifications@github.com> wrote:
>* Command: `agenda`
>    * `--help`
>    * `--events n` - a working version please
>    * `--days n`
>    * `--calendars ...` - To select which calendars are shown
>    * `--not-calendars ...` - To exclude calendars
>    * `--json` - To print results as JSON
>* `--grep key=value,key=value` - List for grepping in a field (for
>example "SUMMARY" from the ical files) for a certain value.
>Additionally not a list of `key=value` pairs but something with `or`
>and `and` logical operators
>* `--before-time` - All events which start/end before a certain daytime
>  * `--after-time` - All events which start/end after a certain daytime
>
>I like the current output of the `agenda` command, though it could use
>some styling, some blank lines after the events of one day, some more
>table-ish style, where you can see things more instantly.
>
>---
>
>I never used the `at` command.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geier/khal/issues/273#issuecomment-145280985

-- 
Sent from my phone. Please excuse my brevity.

**Comment by geier** [comment]
see #325 (Option to display only the first occurrence of reoccurring events)
see #272 (Hide past events)

**Comment by youngmoney** [comment]
I think it might be time to close this as most of the work on these commands has been done and they have changed quite a bit
