### ISSUE TITLE
Reccuring events with longer periods than 1*frequency

### ISSUE THREAD

**Issue by dzoep** [pimutils/khal#289]
The required functionality is in proper support for RFC2445's 4.3.10 Recurrence Rules INTERVAL values bigger than 1.

I assume support for this would need to be added construct_event and everything related. If I am mistaken, feel free to correct me, I just dived into the code...

After adding to rrule_settings, probably it is necessary to check proper caching and add reasonable cli/tui.

CLI: my suggestion is to use format weekly/number (and similar) for representing repetition after more than one week (or other freq).

TUI: add new field next to the repeat field which would allow the user to choose number between 1 and 9 inclusive (according to the spec INTERVAL can only be one digit).

**Comment by geier** [comment]
I'm not sure if anything significant changed, but please compare with
RFC5545 (the more current RFC).

More sensible comments later.

Quoting Dominik Joe Pantůček (2015-10-19 14:05:04)

**Comment by dzoep** [comment]
Ad RFC5545, this section is unchanged (at least the parts I want to implement) - including the 1 digit limit for INTERVAL.

**Comment by geier** [comment]
Sorry it took me so long to have another look at this.

I believe in the ABNF used in the RFC ``1*DIGIT`` means "at least one digit", so an interval >9 should be allowed.

I do agree with everything else you suggest.
The current version of the recurrence editor in the TUI could use some love anyway, that is at least tell the user that the current RRULE can not be edited but only replaced (with a simpler one).

If you have any question, please do contact me.

**Comment by geier** [comment]
fixed in ikhal.
