### ISSUE TITLE
ikhal: external editor support

### ISSUE THREAD

**Issue by geier** [pimutils/khal#31]
It would be nice to have external editor support to edit an event in ikhal, like mutt
using vim.

**Comment by untitaker** [comment]
I suppose this could be done by extracting khal's event editor into its own command.

**Comment by lucc** [comment]
You could also provide a command to edit the raw ical file (copy in /tmp) in an editor (like vim) and then check it for errors and replace the original event with it.

Or you create a more human readable version of the event (maybe some yaml file) and let the user edit this in vim and then parse it back into an ical file and replace the original event with it. This is very similar to the `modify` command of [khard](https://github.com/scheibler/khard).

**Comment by hobarrera** [comment]
> I suppose this could be done by extracting khal's event editor into its own command.

IIRC, this was mentioned before, on some very old issue, and one of the problems with that was the calendar-selector. We'd have to use some specific format where the first line the the selected calendar or something alike.

The downside of this, is that users can't use dedicated ical editors (the same applies to @lucc's last suggestion).

**Comment by lucc** [comment]
If we want to edit ical files externally we *should* not change the calendar the event is stored in at the same time (I am against defining custom extensions to the ical format for this). We could use a new subcommand to khal in this case: `khal mv event old_cal new_cal` or so. 

If we use a yaml file to edit events externally we will define a structure for the yaml file in any case so we can just add a calendar field and move event based on that.

**Comment by geier** [comment]
fixed with ade64e461ef242750b0dad932beea60379fd6f29
