### ISSUE TITLE
khal: Option to display only the first occurrence of reoccurring events

### ISSUE THREAD

**Issue by Markus00000** [pimutils/khal#326]
With many reoccurring events it can become difficult to get a clear overview using `agenda` and `calendar`.

An option to only display the next occurrence of each event and/or an option to suppress the output of all reoccurring events would alleviate this.

(Remind does something similar with `-n`.)

**Comment by geier** [comment]
Sounds like a good idea!

**Comment by youngmoney** [comment]
see the list command now in master, it allows an option `--once` which will only allow each event to print once.
