### ISSUE TITLE
Giving Zenhub a try

### ISSUE THREAD

**Issue by geier** [pimutils/khal#343]
I'm going to give Zenhub.io a try and see if it adds any value. Feel free to take part in that trial!

**Comment by untitaker** [comment]
I briefly tried it but to me it adds more overhead than it saves work.

On 17 February 2016 02:00:45 CET, Christian Geier <notifications@github.com> wrote:
>I'm going to give Zenhub.io a try and see if it adds any value. Feel
>free to take part in that trial!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geier/khal/issues/343

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
Closing candidate?

**Comment by geier** [comment]
Agree
