### ISSUE TITLE
ikhal: pageup/pagedown leave traces behind

### ISSUE THREAD

**Issue by wavexx** [pimutils/khal#373]
Independently of the color scheme, when I use ikhal and immediately press pageup/down, the current selected color of the day is not cleared. If I move over it using the arrow keys it gets cleared, so it might just be some state to reset.

**Comment by untitaker** [comment]
Similarly, adding new events doesn't refresh the colors on the CalendarWalker, only when I move the cursor over the days they're refreshed.

**Comment by geier** [comment]
clicking with the mouse leaves the last focused day highlighted as
focused, too.

Quoting wavexx (2016-03-13 20:42:00)

**Comment by untitaker** [comment]
I'm currently investigating this, and I suspect that the root cause for this is that we're overriding `keypress` instead of one of the higher-level methods of `urwid.Columns`.

**Comment by geier** [comment]
closed by #379

**Comment by untitaker** [comment]
This isn't fixed by the refactor iirc

**Comment by geier** [comment]
untitaker: you are right, didn't test it properly.
