### ISSUE TITLE
`khal configure` does not work without a configuration file.

### ISSUE THREAD

**Issue by three-comrades** [pimutils/khal#384]
Starting khal without a configuration file prints:

> critical: Cannot find a config file.
> critical: If you have no configuration file yet, you might want to run `khal configure`.

Calling `khal configure` then prints:
> critical: Cannot find a config file.
> critical: If you have no configuration file yet, you might want to run `khal configure`

I would have expected a configuration wizard to be started.
Edit: This is on current master.

**Comment by geier** [comment]
Thank you for reporting this bug, I'll look into it ASAP.
