### ISSUE TITLE
Add an option to output agenda with a tiny html subset

### ISSUE THREAD

**Issue by milouse** [pimutils/khal#385]
It would ease the integration with other tools, such as awesome-wm or use it as a very simple and rough cgi script to access our agenda online.

We just need to support `<b>` and `<span color="something">` instead of ANSI escape codes.

I'll try to provide a PR fixing it.

**Comment by untitaker** [comment]
I'm strongly against adding this functionality to khal. If you really want to go this route for showing the calendar on a web interface, there exist third-party tools for converting ANSI colorcodes to HTML.

**Comment by hobarrera** [comment]
I'd suggest you look for an external application to which you can pipe khal's output that replaces ANSI codes to HTML codes if you need that.

> We just need to support <b> and <span color="something"> instead of ANSI escape codes.

That would break khal's primary usage scenario: the command line.

**Comment by milouse** [comment]
I suspected my proposal will not be accepted as it is clearly an edge use case of khal. In fact I confess I wrote this feature request as a sort of "to investigate" for me. I was trying [aha](https://github.com/theZiz/aha) and escape codes seems to be removed before passing the pipe. But I'm certainly wrong and need to better understand terminal mechanism. I need to try [HTMLFromANSI](http://search.cpan.org/~nuffin/HTML-FromANSI-2.03/lib/HTML/FromANSI.pm) perl module too. Sorry for my out of scope proposal.

**Comment by untitaker** [comment]
You need to use the --color flag for khal to preserve them.

On 25 March 2016 10:13:15 CET, "Étienne Deparis" <notifications@github.com> wrote:
>I suspected my proposal will not be accepted as it is clearly an edge
>use case of khal. In fact I confess I wrote this feature request as a
>sort of "to investigate" for me. I was trying
>[aha](https://github.com/theZiz/aha) and escape codes seems to be
>removed before passing the pipe. But I'm certainly wrong and need to
>better understand terminal mechanism. I need to try
>[HTMLFromANSI](http://search.cpan.org/~nuffin/HTML-FromANSI-2.03/lib/HTML/FromANSI.pm)
>perl module too. Sorry for my out of scope proposal.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/issues/385#issuecomment-201214039

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
Concretely, this works for me:

* `khal --color calendar | aha`
* `khal --color agenda | aha`

**Comment by milouse** [comment]
Yes, I got that. I was running "stable" version of khal, which don't seems to have --color feature. With the git version it works. Thank you for this information.
