### ISSUE TITLE
Alarms orientation

### ISSUE THREAD

**Issue by geier** [pimutils/khal#386]
Currently, when entering alarms in ikhal, positive number lead to alarms triggered *after* the event has started and it is not possible to enter negative numbers, see https://github.com/sdx23/khal/commit/481f72efcb6ff26514f98fa94a3f4adb66af61e9#commitcomment-16772716.

We have several options on how to fix the siuation:

1. just allow negative numbers (do we need some user interface elements to tell the user about this?)
2. interpret positive numbers as timedeltas before the event starts (and allow negative numbers)
3. only allow positive numbers and add a new switch deciding if the alarm is trigged before or after the event starts (and perhaps a switch if the alarm should be triggered relative to the start or end of the alarm).

Ideas, opinions?

@languitar @sdx23 (I'm mentioning you specifically because you seem to have some interest in alarms).

**Comment by languitar** [comment]
Probably a before or after switch is most usable.

**Comment by sdx23** [comment]
Actually I'm undecided on this one, as I'm not using the gui much. (2) seems as quick and easy a fix as it is clean. (3) may be more intuitive for users - though I'd guess that few would want alarms after the event time.

**Comment by three-comrades** [comment]
IMHO, the default setting for alarms should be 'before the event'. Also, of the four possible cases:

1. before the start of the event
2. before the end of the event
3. after the start of the event
4. after the end of the event

I can personally see the usefulness of 1.), 2.) and to a lesser extent 3.). I don't know when I would want to use 4.).

**Comment by geier** [comment]
I have merged a commit that allows switching between alarm before and after the (start of the) event. `before` is the default. If anyone wants to do it relative to the end, please submit a PR.
