### ISSUE TITLE
recurring event symbol not shown in xterm

### ISSUE THREAD

**Issue by lecagot** [pimutils/khal#391]
`xterm` locale is set to `utf-8`, however the symbol for recurring events is not displayed:

![2016-04-01_14 01 34](https://cloud.githubusercontent.com/assets/10200768/14206328/a9dd17d8-f812-11e5-8240-ac6c40cf4dd1.png)

Running `terminator` it works as expected:

![2016-04-01_14 00 20](https://cloud.githubusercontent.com/assets/10200768/14206332/ae7074e8-f812-11e5-8e16-68c8a0e76aa2.png)

----

The behaviour for `xterm` is set in the `.Xresources` file:

```
XTerm*locale: true
```

```bash
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Any ideas?

**Comment by hobarrera** [comment]
My guess, is that it's probably a font issue. Are both terminal emulators using the same fonts/font settings?

**Comment by untitaker** [comment]
You need an appropriate font installed. Google Noto is such a font.

**Comment by lecagot** [comment]
well, yeah. that makes sense.

have to give it a shot with another font.

thanks!

**Comment by hobarrera** [comment]
Droid Sans Mono works for my FWIW. A few other monospaces fonts should work, but it's mostly a matter of trying each one.
