### ISSUE TITLE
ikhal interface text and highlight same color

### ISSUE THREAD

**Issue by ryanmorillo** [pimutils/khal#395]
Fresh install after wiping my ~/khal directory left the same issue.  Days and Months are white on white. Haven't been able to figure out where the colors come from.  Day highlight is black on white, and selected day is black on aqua.  Help is blue on white.

**Comment by geier** [comment]
Your terminal  emulator's color scheme probably doesn't play well with the chosen theme. Try setting `theme = light` (in section [view]). If that doesn't help try editing one of the color schemes in `ui/colors.py`.

**Comment by bmarcote** [comment]
The default Dark theme scheme (khal/ui/colors.py) shows:
('dayname', 'light gray', 'white')
('monthname', 'light gray', 'white')
causing that the names of the days and months are invisible.

In my opinion, it should be changed and combine dark/light colors (e.g. dark gray, white; or the opposite) to allow the default theme to show properly the names.

**Comment by geier** [comment]
@bmarcote thank you for looking into this.

**Comment by jmoses** [comment]
The `interactive` mode for dark/today has yellow bg and white fg, and it's just this eye shattering blur.  I can't tell by the docs how to change that via config, so I just updated the `colors.py` data.

**Comment by geier** [comment]
@jmoses: sadly I can't be done via the config right now.

**Comment by geier** [comment]
as of https://github.com/pimutils/khal/pull/1279 themes can be overriden. Better defaults would still be nice, but this allows to fix specific issues such as this one.
