### ISSUE TITLE
search not sorted by date

### ISSUE THREAD

**Issue by terlar** [pimutils/khal#397]
I don't know if there is any specific sorting defined but I think it would make sense that the search is date sorted. Now it seems to be all mixed up.

```
$ khal search 'search term'                     
21/03 - 2016-03-31: search term
31/08 - 2015-09-01: search term
2015-11-27: search term
01/02 - 2016-02-16: search term
```

**Comment by geier** [comment]
They are not sorted at all at the moment. This should be an easy fix, PRs are welcome.

**Comment by terlar** [comment]
Thanks, I had it my todo, but didn't get around to it yet. :+1:

**Comment by Doshirae** [comment]
Hi.
It seems that it is resolved on `khal search` but not in the search in ikhal where it seems that is only sorted according to day and month, but not the year :/

**Comment by bepolymathe** [comment]
Yes I confirm that it would really be an improvement to be able to sort the searches in ikhal by date.

**Comment by geier** [comment]
@bepolymathe feel free to open a new issue for this.
