### ISSUE TITLE
piping output from search includes color codes

### ISSUE THREAD

**Issue by terlar** [pimutils/khal#399]
I don't know when this was introduced, but the other day I piped some content from the search and it didn't include the color codes. However I have updated khal to the latest dev version and now I noticed that when I pipe the search to different tools the escape codes are included.

Is this intentional or is this a regression. If it is intentional perhaps we should add a `--no-color` option to khal.

**Comment by benjaminfrank** [comment]
I encountered the same issue today. there is a --no-color option but it seems to have no effect when searching

**Comment by geier** [comment]
@untitaker could you take a look? One of these days I'll need to either understand click or replace it with something I do...
