### ISSUE TITLE
Two-day view in interactive mode

### ISSUE THREAD

**Issue by bmarcote** [pimutils/khal#409]
I have noticed that Khal only shows events for _n_ days in the static view (not in the interactive one). I attach an example, running the program with the same config file. ikhal on the left and khal on the right.
It would be interesting to have the _n_ days view in the interactive mode too, exactly in the same way than in the normal mode:
"Today" 
   ..{events}..
"Tomorrow"
   ...{events}...
or the day when you are pointing to a farther day.

Additionally, I do not know yet why the difference in the color/bold text in the day and month labels from one to the other mode. 

![screen-capture](https://cloud.githubusercontent.com/assets/5698957/14911105/674d5602-0df3-11e6-8f17-1acbb2362d90.png)

**Comment by untitaker** [comment]
Seems interesting, though I suppose only the selected day's
 events would be selectable?

>Additionally, I do not know yet why the difference in the color/bold text in the day and month labels from one to the other mode. 

That's just an oversight.

**Comment by geier** [comment]
I have something different in mind, right column showing a continuous list of days with events below them. If you move through the calendar, the corresponding day in the right column is highlighted. If moving through the day list, the same day in the calendar is highlighted. I hacked a proof-of-principle together this morning, check out the branch `feature_daywalker` (yes, like blade). It's still crashing pretty often (make sure to set `event_view_always_visible: False`) and most operations apart from browsing the calendar and events list fail.

**Comment by geier** [comment]
![2016-05-05-012040_652x530_scrot](https://cloud.githubusercontent.com/assets/275330/15032294/a4deaae6-125f-11e6-880d-5b7469fc78cc.png)

**Comment by bmarcote** [comment]
It looks great. Maybe the current day and the day after should be still be named as "Today" and "Tomorrow" (just to keep an easy reading).

Sorry this month it is impossible for me, but after that I plan to contribute as much as I can in the near future ;)

**Comment by geier** [comment]
should be fixed with #440
