### ISSUE TITLE
Wish list (and a bug?)

### ISSUE THREAD

**Issue by Brixy** [pimutils/khal#413]
Thanks a lot for khal.

I have been playing with it and a tiny wish list and one possible bug:
# ikhal
- export complete calendar to single .ics file (to publish as `webcal://url.com/calendar.ics`)
- support travel time (oh please!!)
- add flags for additional information
  - available description
  - available place
  - alarm
  - invite
- in event preview: use space key to view long/overflowing event descriptions
- use `$` (like in mutt) to save changes (delete events mark as deleted and redraw screen)
- `w/W`, `m/M`, `y/Y`: navigate by week, month, year
- support invitations (on a simple basis: accept invitation, export updated event and email ics file)
- mark overlapping events (respecting travel time)
# general
- OS X exports contacts (including birthdays) to a single .vcf file. It would be great, if khal supported these.
# bug?

If you import events to a single calendar using

`khal import -a home --batch file.ics`

_multiple times,_ events are gradually imported to all available calendars (e. g. `home`, `work`, `other`).

Thanks you very much!

**Comment by geier** [comment]
Hi, thanks for your suggestions! Some notes and questions on some of them below:

> # ikhal

> - export complete calendar to single .ics file (to publish as `webcal://url.com/calendar.ics`)

you can do this with vdirsyncer, I don't think we should support that in khal


> - support travel time (oh please!!)

what exactly do you mean by that? Display everything in another timezone?

> - add flags for additional information
>     - available description
>     - available place
>     - alarm
>     - invite

Ideas how that should look?

> - in event preview: use space key to view long/overflowing event descriptions

good idea

> - shortcut to copy events

this should already be possible, default is bound to <kbd>p</kbd>

> - use `$` (like in mutt) to save changes (delete events mark as deleted and redraw screen)

somewhat related to #396

> - `w/W`, `m/M`, `y/Y`: navigate by week, month, year

Unless you want to jump to the first day of the next week, the week movement can be achieved by binding w and W and up and down. Others could be usefull as well.

> - support invitations (on a simple basis: accept invitation, export updated event and email ics file)

this is already on the wishlist, see #132

> - mark overlapping events (respecting travel time)

how would you imagine this would look, can you perhaps make a mock-up? Also, some people have asked for displaying events in proportional times, see #311

> # general
> 
> - OS X exports contacts (including birthdays) to a single .vcf file. It would be great, if khal supported these.

I don't think we should support that in khal, but you should be able to do this with vdirsyncer

> # bug?
> 
> If you import events to a single calendar using
> 
> `khal import -a home --batch file.ics`
> 
> _multiple times,_ events are gradually imported to all available calendars (e. g. `home`, `work`, `other`).

Thanks, I'll look into this.

**Comment by Brixy** [comment]
Thanks for your quick reply and effort!

**Travel time**

> what exactly do you mean by that? Display everything in another timezone?

Some apps support a travel time: `X-APPLE-TRAVEL-DURATION;VALUE=DURATION:PT1H30M`.

I. g. event starting time is 1 PM and travel time is 90 mins. Without supported travel time and a “calculated” event starting time at 11:30 AM, you may not remember the originally estimated travel time and concurrently the actual event starting time. Travel time should be flexible, depending on where you are located, whereas the event starting time is fixed. (Excuse my clumsy English.)

**Flags**

> Ideas how that should look?

A simple “!” indicating that (any) other information (description, location …) are available would be sufficient. Or maybe a fashionable UTF-8 symbol.

**Overlapping events (respecting travel time)**

> how would you imagine this would look, can you perhaps make a mock-up? Also, some people have asked for displaying events in proportional times, see #311 

A visual approach would be great. But a simple _watch out symbol_ would be sufficient.

---

Ok, I’ll have a look at vdirsyncer, and yes: I fount the `p` key for copying.

---

**One more suggestion** (tell me, if I shall open individual pull requests)

It would be great, if (i)khal put a date range after multi-day events, e. g. `holidays (05.05.2016–05.05.2022` ;-)

Thanks

**Comment by untitaker** [comment]
Regarding vdirsyncer, you should be able to synchronize a `singlefile` storage with a `filesystem` storage. Unfortunately you'll need to set up one pair for each calendar.

**Comment by Brixy** [comment]
Thanks! I will definitely try vdirsyncer. Just need to upgrade my server beforehand.

**Comment by geier** [comment]
Does the user have to put in that travel-time by themselves? More or less like an alarm? 

And yes, feel free to open individual issues.

**Comment by Brixy** [comment]
> Does the user have to put in that travel-time by themselves? More or less like an alarm?

That’s exactly it. (Some pieces of software can re-calculate travel time depending on location, traffic etc.) Travel time seemed useless to me at first, but it comes in very, very handy if you are on the road a lot. Yet, I did not investigate whether it is an RFC 5545 standard.

Find a screenshot attached.

![screenshot](https://cloud.githubusercontent.com/assets/1643010/15083527/0bae9366-13ce-11e6-9bf8-069298cccc11.png)

**Comment by Brixy** [comment]
How about something like this:

```
! (🚗 10:45 [1h 30m]) 12:15-16:00: My new event
```

! = further information available (description, location …)

**Comment by geier** [comment]
Travel time support sounds like it would need some features, I don't really see belonging into khal (and I myself don't have too much interest in implementing just now).
This said, if anyone wants to work on this and reuse khal's database, `Khalendar` or something else, I will support them as good as I can (I'm mostly thinking of adding features to the database layer).

One would probably want to query for all events in the next X hours (can be doen with `Khalendar`) and check for traveltime from the current location to the event's location (can Google's Map API do this?) and then add another event in front of it or just add a VALRM. But all of this is probably still not helpful as long as there is no support for actually alarming the user (see #148).

**Comment by Brixy** [comment]
Yes, anything you described would be totally out of scope.

Personally, I use travel time only as a “static visible alarm”. That is absolutely sufficient and yet very helpful.

**Comment by geier** [comment]
I've created new issues for the individual unresolved issues, if I have forgotten anything, feel free to open additional ones.
