### ISSUE TITLE
config file is too nested on a fresh install

### ISSUE THREAD

**Issue by waynew** [pimutils/khal#417]
Just installed `khal, version 0.8.1`, and running it failed:

```
critical: parsing the config file file with the following error: Section too nested at line 1.
critical: if you recently updated khal, the config file format might have changed, in that case please consult the CHANGELOG or other documentation
```

My khal config:

```
⚘ cat ~/.config/khal/khal.conf
[[calendars]]
[private]
path = /home/wayne/.local/share/khal/calendars/private
type = calendar
[locale]
timeformat = %H:%M
dateformat = %Y-%m-%d
longdateformat = %Y-%m-%d
datetimeformat = %Y-%m-%d %H:%M
longdatetimeformat = %Y-%m-%d %H:%M%
```

**Comment by geier** [comment]
Thank you for reporting this and the other bugs. While I won't have time before next week to look into them, I believe at least this one is already fixed in master with commit 777a38555465c898de4a708e65f07423e4836afc.

**Comment by waynew** [comment]
I did roughly the same thing as scott2b:

```
pip uninstall khal
pip install --user git+https://github.com/pimutils/khal
rm ~/.config/khal/khal.conf
khal configure
mkdir -p ~/.local/share/khal/calendars/private
```
It crashed when the private directory wasn't there, which it probably shouldn't have done :stuck_out_tongue_closed_eyes:

**Comment by geier** [comment]
Should be fixed with the latest release, please reopen (or comment) if anyone gets the same bug.
