### ISSUE TITLE
`Q` for quit

### ISSUE THREAD

**Issue by wavexx** [pimutils/khal#421]
Many curses applications allow both `q` and `Q` to quit (in fact, `q` is generally with confirmation, `Q` quits immediately -- but not always).

I'm so used to type `Q` that I'd love to have it bound to quit as well.

**Comment by geier** [comment]
Good idea, at the very least make it user defined, but 'q' and 'Q' sound like sane defaults.

**Comment by geier** [comment]
fixed with 0faabdf77f30320f113c4f17904693a12098baa7
