### ISSUE TITLE
Feature Request: Interactive Mode Refresh

### ISSUE THREAD

**Issue by TheOneValen** [pimutils/khal#423]
Hi!

I love khals interactive mode. I would like to suggest a simple keybinding ('r') to get khal to reload its data.

Even better would be an automatic reload in the background.

Vdirsyncer is already called via cron, but having the option to also run vdirsyncer in the background would be nice I think.

Have a nice day!

**Comment by geier** [comment]
Hi, this really would be a good feature to have. As this is basically the same as #264 I'm closing this as a duplicate.
