### ISSUE TITLE
--format printing of all-day start and end times

### ISSUE THREAD

**Issue by geier** [pimutils/khal#430]
with --format we currently print all-day events like this (with the default format):
`31.05. 00:00-31.05. 23:59 all day`

see #426 

I'm not really happy with it for conceptional reasons:

    all-day events just do not end at 23:59, the last minute of that day is still "covered" by the event (and printing 00:00 of the following day is confusing/wrong if you only print days)
        all-day events really should not have start and end times at all

Some ideas on how to fix this off the top of my head:

    just use an empty string as the start and end time for all-day events
    use different --format options for all-day and datetime events (perhaps even floating and localized events), perhaps with a default --format options that works for all event types in combination with the previous point and than two (or three) additional ones
    use a better templating language, but it should be pretty lightweight (in terms of import templating speed, e.g., jinja2 takes much too long)

**Comment by youngmoney** [comment]
I'd say lets add an ending to the existing start/end that removes the time if its an all day event: so `--format "{title}{start-clean}{end-clean}"` would show the start/end normally for an event, but would just show the dates for an all day event. I could easily add the -clean ending to each of the current formats. This way users have the option as to weather they want the times shown (and if they are shown I say we leave them as 23:59)

**Comment by geier** [comment]
fixed with #443

**Comment by youngmoney** [comment]
I think you meant #433 (just so we have a record)

**Comment by geier** [comment]
Thanks, I meant that indeed.
