### ISSUE TITLE
Allow duplication of events from read-only calendars

### ISSUE THREAD

**Issue by pdav** [pimutils/khal#431]
Using "p" to duplicate an event from a read-only calendar (in order to copy this event from a reference calendar to my personal calendar) generates an unpleasant Python error with a stack trace.

Using "p" should directly bring the user into the event editor, in order to allow changing whatever the user wants (date, calendar or anything else). This behaviour would be consistant with the calendaring application from a well known search engine.

At least, attempting to duplicate an event into a read-only calendar (as it is implemented now, or with the suggested change) should not result in a raw Python error.

**Comment by geier** [comment]
Thank you for reporting this. While it makes me unhappy that another bug slipped by unnoticed it also makes me happy because some people seem to use our software :)

**Comment by geier** [comment]
I've "fixed" this for now with 981c36d, that is, it doesn't crash anymore but produces a warning. I'll rename the issue accordingly.

**Comment by pdav** [comment]
Tested. Thanks.

**Comment by geier** [comment]
should be fixed with #440
