### ISSUE TITLE
KeyError for a skipped date on a recurrance

### ISSUE THREAD

**Issue by gberenfield** [pimutils/khal#432]
The following event gives me this error when running khal

```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/khal/khalendar/khalendar.py", line 286, in _update_vevent
    update(event.raw, href=href, etag=etag, calendar=calendar)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 260, in update
    self._update_impl(vevent, href, calendar)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 349, in _update_impl
    dtstartend = aux.expand(vevent, href)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/aux.py", line 106, in expand
    dtstartl.remove(date)
KeyError: datetime.datetime(2011, 9, 24, 15, 50, tzinfo=<DstTzInfo 'America/New_York' EDT-1 day, 20:00:00 DST>)
warning: Skipping home/00D6A925-90F7-4663-AE13-E8BD1655EF77.ics: datetime.datetime(2011, 9, 24, 15, 50, tzinfo=<DstTzInfo 'America/New_York' EDT-1 day, 20:00:00 DST>)
warning: This event will not be available in khal.
```

The relevant ics file is below.
Great program by the way!!

```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:America/New_York
X-LIC-LOCATION:America/New_York
BEGIN:STANDARD
DTSTART:18831118T120358
RDATE;VALUE=DATE-TIME:18831118T120358
TZNAME:EST
TZOFFSETFROM:-0456
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19180331T020000
RRULE:FREQ=YEARLY;UNTIL=19190330T070000Z;BYDAY=-1SU;BYMONTH=3
TZNAME:EDT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19181027T020000
RRULE:FREQ=YEARLY;UNTIL=19191026T060000Z;BYDAY=-1SU;BYMONTH=10
TZNAME:EST
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:STANDARD
DTSTART:19200101T000000
RDATE;VALUE=DATE-TIME:19200101T000000
RDATE;VALUE=DATE-TIME:19420101T000000
RDATE;VALUE=DATE-TIME:19460101T000000
RDATE;VALUE=DATE-TIME:19670101T000000
TZNAME:EST
TZOFFSETFROM:-0500
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19200328T020000
RDATE;VALUE=DATE-TIME:19200328T020000
RDATE;VALUE=DATE-TIME:19740106T020000
RDATE;VALUE=DATE-TIME:19750223T020000
TZNAME:EDT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19201031T020000
RDATE;VALUE=DATE-TIME:19201031T020000
RDATE;VALUE=DATE-TIME:19450930T020000
TZNAME:EST
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19210424T020000
RRULE:FREQ=YEARLY;UNTIL=19410427T070000Z;BYDAY=-1SU;BYMONTH=4
TZNAME:EDT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19210925T020000
RRULE:FREQ=YEARLY;UNTIL=19410928T060000Z;BYDAY=-1SU;BYMONTH=9
TZNAME:EST
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19420209T020000
RDATE;VALUE=DATE-TIME:19420209T020000
TZNAME:EWT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19450814T190000
RDATE;VALUE=DATE-TIME:19450814T190000
TZNAME:EPT
TZOFFSETFROM:-0400
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19460428T020000
RRULE:FREQ=YEARLY;UNTIL=19660424T070000Z;BYDAY=-1SU;BYMONTH=4
TZNAME:EDT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19460929T020000
RRULE:FREQ=YEARLY;UNTIL=19540926T060000Z;BYDAY=-1SU;BYMONTH=9
TZNAME:EST
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:STANDARD
DTSTART:19551030T020000
RRULE:FREQ=YEARLY;UNTIL=19661030T060000Z;BYDAY=-1SU;BYMONTH=10
TZNAME:EST
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19670430T020000
RRULE:FREQ=YEARLY;UNTIL=19730429T070000Z;BYDAY=-1SU;BYMONTH=4
TZNAME:EDT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19671029T020000
RRULE:FREQ=YEARLY;UNTIL=20061029T060000Z;BYDAY=-1SU;BYMONTH=10
TZNAME:EST
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19760425T020000
RRULE:FREQ=YEARLY;UNTIL=19860427T070000Z;BYDAY=-1SU;BYMONTH=4
TZNAME:EDT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19870405T020000
RRULE:FREQ=YEARLY;UNTIL=20060402T070000Z;BYDAY=1SU;BYMONTH=4
TZNAME:EDT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:20070311T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
TZNAME:EDT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:20071104T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
TZNAME:EST
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20110917T174215Z
LAST-MODIFIED:20160418T203122Z
DTSTAMP:20160418T203122Z
UID:00D6A925-90F7-4663-AE13-E8BD1655EF77
SUMMARY:Soccer
RRULE:FREQ=WEEKLY;UNTIL=20111206T205000Z
EXDATE:20110924T195000Z
EXDATE:20111126T205000Z
EXDATE:20111008T195000Z
DTSTART;TZID=America/New_York:20111112T155000
DTEND;TZID=America/New_York:20111112T170000
SEQUENCE:14
DESCRIPTION:fixed?
CLASS:PRIVATE
TRANSP:OPAQUE
X-MOZ-GENERATION:3
END:VEVENT
END:VCALENDAR
```

**Comment by plega** [comment]
I have had the same problem.  Here is a sample file:

BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/London
X-LIC-LOCATION:Europe/London
BEGIN:DAYLIGHT
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19700329T010000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:19701025T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20141031T111113Z
LAST-MODIFIED:20150313T085053Z
DTSTAMP:20150313T085053Z
UID:f14d00d0-1cd6-4f45-a671-79eb4ab1db5a
SUMMARY:Project Nimby
ORGANIZER;RSVP=TRUE;ROLE=CHAIR;PARTSTAT=ACCEPTED;CN=foo@bar.com:mai
 lto:foo@bar.com
ATTENDEE;CN=Kim Naidoo;PARTSTAT=DECLINED;ROLE=REQ-PARTICIPANT:mailto:lxn
 @bar.com
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Alice Wh
 ite:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=2;CN=Flurble Hillsdon;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@ef
 iling.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Phasdfen;RECEIVE
 D-SEQUENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Alice Sidd;RECEIVED-SEQU
 ENCE=5;RECEIVED-DTSTAMP=20150205T182445Z:mailto:js@bar.com
ATTENDEE;CN=David Garth;RECEIVED-SEQUENCE=5;PARTSTAT=NEEDS-ACTION;ROLE=OPT
 -PARTICIPANT;SENT-BY="MAILTO:aon@bar.com";RECEIVED-DTSTAMP=20150205
 T182445Z;RSVP=TRUE:mailto:djb@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=5;CN=Wibble Goodhand;RECEIVED-DTSTAMP=20150226T095251Z:mailto:fo@co
 iling.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Wibble Ham;RECEIVED-SEQ
 UENCE=10;RECEIVED-DTSTAMP=20150312T162153Z:mailto:foo@bar.com
RRULE:FREQ=WEEKLY;UNTIL=20150313T090000Z
EXDATE:20141121T090000Z
EXDATE:20150206T090000Z
EXDATE:20150306T090000Z
EXDATE:20150320T090000Z
X-MOZ-LASTACK:20150313T085053Z
DTSTART;TZID=Europe/London:20141107T090000
DTEND;TZID=Europe/London:20141107T100000
CLASS:PUBLIC
LOCATION:Alice\, Ground Floor
DESCRIPTION:Project Nimby team meeting
TRANSP:OPAQUE
SEQUENCE:10
X-MOZ-GENERATION:40
END:VEVENT
BEGIN:VEVENT
CREATED:20141120T100622Z
LAST-MODIFIED:20141120T100632Z
DTSTAMP:20141120T100632Z
UID:f14d00d0-1cd6-4f45-a671-79eb4ab1db5a
SUMMARY:Project Nimby
RECURRENCE-ID:20141121T090000Z
ORGANIZER;RSVP=TRUE;ROLE=CHAIR;PARTSTAT=ACCEPTED;CN=foo@bar.com:mai
 lto:foo@bar.com
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Alice Wh
 ite:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=2;CN=Wibble Goodhand;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@ef
 ilg.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=2;CN=Flurble Hillsdon;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@b
 iling.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=2;CN=Alice Siddle;RECEIVED-DTSTAMP=20141031T111540Z:mailto:js@sdefi
 g.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=2;CN=Phin;RECEIVED-DTSTAMP=20141031T111540Z:mailto:pfoo@core
 filing.com
ATTENDEE;ROLE=OPT-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=2;CN=David Garth;RECEIVED-DTSTAMP=20141103T125639Z:mailto:djb@corefi
 ling.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=2;CN=Wibble Hamster;RECEIVED-DTSTAMP=20141114T085257Z:mailto:foo@fil
 ing.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=2;CN=Kim Naidoo;RECEIVED-DTSTAMP=20141113T230220Z:mailto:foo@coref
 iling.com
DTSTART:20141121T090000Z
DTEND:20141121T100000Z
CLASS:PUBLIC
LOCATION:Alice\, Ground Floor
DESCRIPTION:Project Nimby team meeting
TRANSP:OPAQUE
SEQUENCE:5
X-MOZ-GENERATION:12
END:VEVENT
BEGIN:VEVENT
CREATED:20141031T111113Z
LAST-MODIFIED:20141205T085302Z
DTSTAMP:20141205T085302Z
UID:f14d00d0-1cd6-4f45-a671-79eb4ab1db5a
SUMMARY:Project Nimby
RECURRENCE-ID:20141219T090000Z
ORGANIZER;RSVP=TRUE;ROLE=CHAIR;PARTSTAT=ACCEPTED;CN=foo@bar.com:mai
 lto:foo@bar.com
ATTENDEE;PARTSTAT=ACCEPTED;CN=Kim Naidoo;ROLE=REQ-PARTICIPANT:mailto:lxn
 @bar.com
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Alice Wh
 ite:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=DECLINED;CN=Wib Hamster;RECEIVED-SEQ
 UENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Wibb Goodhand;RECEIVED-S
 EQUENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Flue Hillsdon;RECEIVED-S
 EQUENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Alice Side;RECEIVED-SEQU
 ENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:js@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Phn;RECEIVED-SE
 QUENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:pfoo@bar.com
ATTENDEE;ROLE=OPT-PARTICIPANT;PARTSTAT=DECLINED;CN=David Garth;RECEIVED-SE
 QUENCE=2;RECEIVED-DTSTAMP=20141103T125639Z:mailto:djb@bar.com
X-MOZ-LASTACK:20141205T085302Z
DTSTART;TZID=Europe/London:20141219T090000
DTEND;TZID=Europe/London:20141219T100000
CLASS:PUBLIC
LOCATION:Alice\, Ground Floor
DESCRIPTION:Project Nimby team meeting
TRANSP:OPAQUE
SEQUENCE:3
X-MOZ-GENERATION:16
END:VEVENT
BEGIN:VEVENT
CREATED:20141031T111113Z
LAST-MODIFIED:20141205T085302Z
DTSTAMP:20141205T085302Z
UID:f14d00d0-1cd6-4f45-a671-79eb4ab1db5a
SUMMARY:Project Nimby
RECURRENCE-ID:20141226T090000Z
ORGANIZER;RSVP=TRUE;ROLE=CHAIR;PARTSTAT=ACCEPTED;CN=foo@bar.com:mai
 lto:foo@bar.com
ATTENDEE;PARTSTAT=ACCEPTED;CN=Kim Naidoo;ROLE=REQ-PARTICIPANT:mailto:lxn
 @bar.com
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Alice Wh
 ite:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=DECLINED;CN=Wibblster;RECEIVED-SEQ
 UENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Wibbldhand;RECEIVED-S
 EQUENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Flurbllsdon;RECEIVED-S
 EQUENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Aliceddle;RECEIVED-SEQU
 ENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:js@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Philen;RECEIVED-SE
 QUENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:pfoo@bar.com
ATTENDEE;ROLE=OPT-PARTICIPANT;PARTSTAT=DECLINED;CN=David Garth;RECEIVED-SE
 QUENCE=2;RECEIVED-DTSTAMP=20141103T125639Z:mailto:djb@bar.com
X-MOZ-LASTACK:20141205T085302Z
DTSTART;TZID=Europe/London:20141226T090000
DTEND;TZID=Europe/London:20141226T100000
CLASS:PUBLIC
LOCATION:Alice\, Ground Floor
DESCRIPTION:Project Nimby team meeting
TRANSP:OPAQUE
SEQUENCE:3
X-MOZ-GENERATION:16
END:VEVENT
BEGIN:VEVENT
CREATED:20141031T111113Z
LAST-MODIFIED:20141229T144002Z
DTSTAMP:20141229T144002Z
UID:f14d00d0-1cd6-4f45-a671-79eb4ab1db5a
SUMMARY:Project Nimby
RECURRENCE-ID:20150102T090000Z
ORGANIZER;RSVP=TRUE;ROLE=CHAIR;PARTSTAT=ACCEPTED;CN=foo@bar.com:mai
 lto:foo@bar.com
ATTENDEE;PARTSTAT=TENTATIVE;CN=Kim Naidoo;ROLE=REQ-PARTICIPANT:mailto:lx
 n@bar.com
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Alice Wh
 ite:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Wile Goodhand;RECEIVED-S
 EQUENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Flle Hillsdon;RECEIVED-S
 EQUENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Ale Siddle;RECEIVED-SEQU
 ENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:js@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Pn;RECEIVED-SE
 QUENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:pfoo@bar.com
ATTENDEE;ROLE=OPT-PARTICIPANT;PARTSTAT=DECLINED;CN=David Garth;RECEIVED-SE
 QUENCE=2;RECEIVED-DTSTAMP=20141103T125639Z:mailto:djb@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=DECLINED;CN=Wi Hamster;RECEIVED-SEQ
 UENCE=3;RECEIVED-DTSTAMP=20141218T084940Z:mailto:foo@bar.com
X-MOZ-LASTACK:20141205T085302Z
DTSTART;TZID=Europe/London:20150102T090000
DTEND;TZID=Europe/London:20150102T100000
CLASS:PUBLIC
LOCATION:Alice\, Ground Floor
DESCRIPTION:Project Nimby team meeting
TRANSP:OPAQUE
SEQUENCE:3
X-MOZ-GENERATION:16
END:VEVENT
BEGIN:VEVENT
CREATED:20141031T111113Z
LAST-MODIFIED:20150220T085710Z
DTSTAMP:20150220T085710Z
UID:f14d00d0-1cd6-4f45-a671-79eb4ab1db5a
SUMMARY:Project Nimby
RECURRENCE-ID:20150227T090000Z
ORGANIZER;RSVP=TRUE;ROLE=CHAIR;PARTSTAT=ACCEPTED;CN=foo@bar.com:mai
 lto:foo@bar.com
ATTENDEE;PARTSTAT=DECLINED;CN=Kim Naidoo;ROLE=REQ-PARTICIPANT:mailto:lxn
 @bar.com
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Alice Wh
 ite:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=2;CN=Wibble Goodhand;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@ref
 iling.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=2;CN=Flurble Hillsdon;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@ef
 iling.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQU
 ENCE=2;CN=Phien;RECEIVED-DTSTAMP=20141031T111540Z:mailto:pfoo@core
 filing.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Alicele;RECEIVED-SEQU
 ENCE=5;RECEIVED-DTSTAMP=20150205T182445Z:mailto:js@bar.com
ATTENDEE;ROLE=OPT-PARTICIPANT;PARTSTAT=DECLINED;CN=David Garth;RECEIVED-SE
 QUENCE=5;SENT-BY="MAILTO:aon@bar.com";RECEIVED-DTSTAMP=20150205T182
 445Z:mailto:djb@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Wibblter;RECEIVED-SEQ
 UENCE=5;RECEIVED-DTSTAMP=20150207T123636Z:mailto:foo@bar.com
X-MOZ-LASTACK:20150220T085709Z
DTSTART;TZID=Europe/London:20150227T090000
DTEND;TZID=Europe/London:20150227T100000
CLASS:PUBLIC
LOCATION:Alice\, Ground Floor
DESCRIPTION:Project Nimby team meeting
TRANSP:OPAQUE
SEQUENCE:5
X-MOZ-GENERATION:30
END:VEVENT
BEGIN:VEVENT
CREATED:20141031T111113Z
LAST-MODIFIED:20150313T085053Z
DTSTAMP:20150313T085053Z
UID:f14d00d0-1cd6-4f45-a671-79eb4ab1db5a
SUMMARY:Project Nimby
ATTENDEE;PARTSTAT=DECLINED;CN=Kim Naidoo;ROLE=REQ-PARTICIPANT:mailto:lxn
 @bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;CN=Alice Wh
 ite:mailto:foo@bar.com
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Flurblls
 don;RECEIVED-SEQUENCE=2;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@cef
 iling.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RECEIVED-SEQUENCE=2;CN=
 Philip Allen;RECEIVED-DTSTAMP=20141031T111540Z:mailto:foo@bar.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RECEIVED-SEQUENCE=5;CN=Ale 
 Siddle;RECEIVED-DTSTAMP=20150205T182445Z:mailto:js@bar.com
ATTENDEE;CN=David Garth;RECEIVED-SEQUENCE=5;PARTSTAT=NEEDS-ACTION;ROLE=OPT
 -PARTICIPANT;SENT-BY="MAILTO:aon@bar.com";RECEIVED-DTSTAMP=20150205
 T182445Z;RSVP=TRUE:mailto:djb@bar.com
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=WibGoodh
 and;RECEIVED-SEQUENCE=5;RECEIVED-DTSTAMP=20150226T095251Z:mailto:foo@cf
 iling.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RECEIVED-SEQUENCE=10;CN=Mar
 k Hamster;RECEIVED-DTSTAMP=20150312T162153Z:mailto:foo@bar.com
X-MOZ-LASTACK:20150313T085053Z
DTSTART;TZID=Europe/London:20141107T090000
DTEND;TZID=Europe/London:20141107T100000
CLASS:PUBLIC
LOCATION:Alice\, Ground Floor
DESCRIPTION:Project Nimby team meeting
TRANSP:OPAQUE
SEQUENCE:10
X-MOZ-GENERATION:40
ORGANIZER;RSVP=TRUE;ROLE=CHAIR;PARTSTAT=ACCEPTED;CN=foo@bar.com:mai
 lto:foo@bar.com
RECURRENCE-ID:20141107T090000Z
END:VEVENT
END:VCALENDAR

And this is the output:

Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/khal-0.8.2.dev72+nga2f384d-py3.4.egg/khal/khalendar/khalendar.py", line 286, in _update_vevent
    update(event.raw, href=href, etag=etag, calendar=calendar)
  File "/usr/lib/python3.4/site-packages/khal-0.8.2.dev72+nga2f384d-py3.4.egg/khal/khalendar/backend.py", line 260, in update
    self._update_impl(vevent, href, calendar)
  File "/usr/lib/python3.4/site-packages/khal-0.8.2.dev72+nga2f384d-py3.4.egg/khal/khalendar/backend.py", line 349, in _update_impl
    dtstartend = aux.expand(vevent, href)
  File "/usr/lib/python3.4/site-packages/khal-0.8.2.dev72+nga2f384d-py3.4.egg/khal/khalendar/aux.py", line 106, in expand
    dtstartl.remove(date)
KeyError: datetime.datetime(2015, 3, 20, 9, 0, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>)
warning: Skipping work/f14d00d0-1cd6-4f45-a671-79eb4ab1db5a.ics: datetime.datetime(2015, 3, 20, 9, 0, tzinfo=<DstTzInfo 'Europe/London' GMT0:00:00 STD>)

**Comment by geier** [comment]
Hi and thanks for reporting those. Both events excluded dates (EXDATEs) that were not actually part of the the events description, a warning is now printed instead in cases like this.

I'll need to have a look if those events are actually valid or not (in which case we should probably print a sterner warning).

**Comment by plega** [comment]
Thanks

Philip

On Mon, Jun 13, 2016 at 10:58:54AM +0100, Christian Geier wrote:
> Hi and thanks for reporting those. Both events excluded dates (EXDATEs) that were not actually part of the the events description, a warning is now printed instead in cases like this.
> 
> I'll need to have a look if those events are actually valid or not (in which case we should probably print a sterner warning).
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/pimutils/khal/issues/432#issuecomment-225538577

-- 
Philip Allen
9 Bardwell Road             
Oxford  OX2 6SU                         +44-1865-311711
United Kingdom                     plega@armitstead.com
