### ISSUE TITLE
ikhal creates empty field for LOCATION and DESCRIPTION

### ISSUE THREAD

**Issue by Brixy** [pimutils/khal#436]
Hi!

Just realized that some GUI programmes print “notes:” oder “location:”, even if no value is set.

When you create a new event using `ikhal` (unlike `khal`) without values for DESCRIPTION and/or LOCATION, in the .ics file you will find

```
DESCRIPTION:
LOCATION:
```

It would probably be better not to create these two keys, if no values exist.

Thanks.

**Comment by geier** [comment]
Probably a good idea, patches are welcome (and this should be a rather easy patch).

**Comment by geier** [comment]
closed with #504
