### ISSUE TITLE
iCal, DTSTART == DTEND

### ISSUE THREAD

**Issue by drzraf** [pimutils/khal#444]
Currently, when DTSTART == DTEND khal shows things like:

```
Today:
20:00→ : "blah foo bar"
Tomorrow:
  → 20:00: "blah foo bar"
```

Google Agenda assume that event last 1 hour.
Neither behavior is perfect and both are better than omitting the event.
But khal output seems more confusing and by assuming that event last 24h give the visual impression that 2 distinct event happens (especially if other events happens in the timespan).

Assuming up the end-of-the-day, or, like Google 1 hour, could be better trade-off.

**Comment by untitaker** [comment]
It's worth noting that DTSTART is a datetime and DTEND as well.

Khal applies that workaround where it increases DTEND by one day, but it might make sense to only increase it by one hour if we're dealing with a datetime, such that it looks the same as Google Calendar.

**Comment by geier** [comment]
Hmm, I thought we were converting events starting and ending at the same date time to all-day events on that date, but it turns out this is what we do for events with no DTEND. Not sure what the best option is, the current, but I feel that both options (making it an all-day event or an event lasting for one hour) are better than the current behavior.

**Comment by geier** [comment]
just checked the RFC: DTEND is *exclusive*, so DTSTART == DTEND really makes no sense.

**Comment by nim65s** [comment]
I have the same issue. And yes, this is probably a bug from the software that wrote the ics in the first time.
Still, falling back to a 1 hour would be really better in my use cases, or at least a way to configure this should be added in khal.
I'll probably make a PR soon if nobody is against that :)
