### ISSUE TITLE
[RFC] rename command "agenda" to "list"?

### ISSUE THREAD

**Issue by geier** [pimutils/khal#446]
How do you feel about renaming the `agenda` command to `list`?

**Comment by pdav** [comment]
One objection: output of `list` can be easily parsed by an external program, whereas output of `agenda` is less regular and more difficult to parse.

This may be solved by a simple flag to your new `agenda` command.

**Comment by geier** [comment]
The idea is that all commands that output events have a `--format`
argument, that allows the output to be parsed easily (or event turn it
into e.g. json). list and agenda are getting merged, the only
question is, what to call that command.

Quoting Pierre DAVID (2016-06-20 11:08:58)

**Comment by pdav** [comment]
Well, with the `--format` argument, I agree with your proposal.
