### ISSUE TITLE
Moving an event to another day does not remove it from the current day

### ISSUE THREAD

**Issue by pdav** [pimutils/khal#452]
With ikhal, moving an event to another day does not remove it from the list of events (in the right part) for the current day.

When selecting this event, its date is correct (it is the new date). When moving the cursor to another day, next coming back to the old day, the event is no longer displayed.

Thus, the event is correctly moved, but the event list is just not refreshed.

**Comment by geier** [comment]
Thanks for reporting this, will get (is) fixed with `feature_daywalker`.

**Comment by geier** [comment]
should be fixed with #440
