### ISSUE TITLE
khal adds empty CATEGORIES to all entries

### ISSUE THREAD

**Issue by hobarrera** [pimutils/khal#453]
As mentioned [here](https://github.com/pimutils/khal/pull/414#issuecomment-229449215), events created with khal have an empty `CATEGORIES` field (assuming no categories are added), and are rejected by fastmail.

I'm not 100% sure if the empty field is [RFC](https://tools.ietf.org/html/rfc5545#section-3.8.1.2)-compliant or not.

**Comment by pdav** [comment]
At first sight, [RFC 5545 on `CATEGORIES`](https://tools.ietf.org/html/rfc5545#section-3.8.1.2) specifies that `text` is mandatory, so fastmail is right (except on the "be conservative in what you do, be liberal in what you accept" principle).

However, [RFC 5545 on `LOCATION`](https://tools.ietf.org/html/rfc5545#section-3.8.1.7) also specifies that `text` is not optional. So, fastmail should reject empty `LOCATION` fields, as well as many other empty fields.

**Comment by hobarrera** [comment]
> (except on the "be conservative in what you do, be liberal in what you accept" principle).

Fastmail tends to be quite draconian when in comes to ical/vcard validation, regrettably. Far more than any client I've seen out there.

**Comment by geier** [comment]
fixed with 5cf351d
