### ISSUE TITLE
recurring event displays wrong time during daylight savings time

### ISSUE THREAD

**Issue by jason-speck** [pimutils/khal#46]
Hi, I have a recurring event that is every Monday at 9:30.  khal/ikhal display at at 9:30 during standard time correctly, but not during daylight savings time.  During daylight savings time, it shows the meetings as starting at 10:30.

To make sure I can see the actual contents of the event, I added a debug line in the section of backend.py where it looks at recurring events:

 logging.debug(vevent.to_ical()) 

When I sync, it outputs the following for my recurring event (atendees snipped out):

DEBUG:root:BEGIN:VEVENT
SUMMARY:Sales/FAE Call Skype
DTSTART;TZID=America/Tijuana:20131118T093000
DTEND;TZID=America/Tijuana:20131118T103000
DTSTAMP:20131118T173513Z
UID:6916DABE-8FEF-4DD1-877A-AA328999C1D7
SEQUENCE:28
CLASS:PUBLIC
RRULE:FREQ=WEEKLY;BYDAY=MO
TRANSP:OPAQUE
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
END:VEVENT

It should always appear as 9:30 regardless of whether it's standard or daylight savings time.

**Comment by Konfekt** [comment]
The issue persists with khal 10.2. Could this issue be reopened or should a new one be filed?

**Comment by Konfekt** [comment]
To confirm, this issue affects only recurring events. The times of non-recurring events are shown correctly. In my case the timezone is `Europe/Berlin`. `ikhal` used to show times correctly till the end of October; since then they are one hour ahead of the correct time (in the ICS file).
