### ISSUE TITLE
ikhal: Unable to bind ctrl + space

### ISSUE THREAD

**Issue by vleonbonnet** [pimutils/khal#460]
I have tried the following:

    mark = ctrl space
    mark = ctrl ' '
    mark = 'ctrl  '

But none seems to work.

**Comment by geier** [comment]
`mark = ctrl space` should be right. What probably happens is that your
terminal sends an ASCII NULL character. You can probably bind mark to
NULL with `mark = <0>`, not sure if this is a good idea.

Quoting Valentin Leon (2016-07-11 12:20:33)

**Comment by vleonbonnet** [comment]
I believe that binding the 'space' keyword does not do anything. In order to bind space (without Ctrl), a space (' ') character need to be inserted in the configuration file, this can be seen [here](https://github.com/pimutils/khal/blob/4c1562ee61c18c77e0411b9cf25411fb90b950d5/khal/settings/khal.spec#L109) and I have been able to test it as well.

However, when trying to bind Ctrl + ' ' I don't think that the configuration parser likes the mix of quoted + unquoted keyword.

**Comment by geier** [comment]
Yep, you are totally right. Does `ctrl  ` (two spaces) work?

Quoting Valentin Leon (2016-07-12 12:17:27)

**Comment by vleonbonnet** [comment]
Nope, it does not work.

**Comment by geier** [comment]
Did you try `mark = <0>`?

I can't test 'ctrl  ' myself as ctrl + space sends the null character on
my terminal, but `mark = 'meta  '` works for me (where meta is the "alt"
key).

Quoting Valentin Leon (2016-07-12 13:37:02)

**Comment by vleonbonnet** [comment]
Yes, `mark = <0>` correctly mapped to Ctrl+space on my terminal as well (urxvt+screen). Thanks

**Comment by geier** [comment]
You are welcome.
