### ISSUE TITLE
iOS locations break parser

### ISSUE THREAD

**Issue by 0-wiz-0** [pimutils/khal#467]
I have a couple of calendar entries that have locations added with iOS (or OS X).
These are not displayed in khal with errors like this one:

```
error: Errors occurred when parsing privat/filename.ics for the following reasons:
error: (None, 'Content line could not be parsed into parts: \'X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Wien, Österreich";X-APPLE-MAPKIT-HANDLE=$BASE64STRING;X-APPLE-RADIUS=49.91306091513493;X-APPLE-REFERENCEFRAME=1;X-TITLE=$STREETNAME:geo:$COORD1,$COORD2\': \'X-APPLE-MAPKIT-HANDLE=$BASE64STRING\' is not a valid parameter string: too many values to unpack (expected 2)')
error: This might lead to this event being show wrongly or not at all.
```

where `$BASE64STRING`, `$STREETNAME`, `$COORD1`, and `$COORD2` are
redacted.

**Comment by geier** [comment]
This is probably really an icalendar issue (either a bug or Apple sends creates some invalid ics files, again). I'll have a look and report back.

**Comment by geier** [comment]
Can you confirm that the line looks basically like this:

```
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Wien, Österreich";X-APPLE-MAPKIT-HANDLE=abcd;X-APPLE-RADIUS=49.91306091513493;X-APPLE-REFERENCEFRAME=1;X-TITLE=Hauptstraße:geo:-33.868900,151.207000 
```
Because I can import an ics file with the above line.

**Comment by 0-wiz-0** [comment]
No, there's more. Here's a complete error line from khal:
````
error: Errors occurred when parsing privat/A1527600-E1B6-4EF5-A2CC-BA8614DFEC7B.ics for the following reasons:
error: (None, 'Content line could not be parsed into parts: \'X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Kaiserliche Hofburg, 1010 Wien, Österreich";X-APPLE-MAPKIT-HANDLE=CAESxQEIrk0QnJyKy6Oq97MsGhIJFBZgr3QaSEARAAAA8PxcMEAiaAoHQXVzdHJpYRICQVQaBFdpZW4yBFdpZW46BDEwMTByE0thaXNlcmxpY2hlIEhvZmJ1cmeKARcxLiBCZXppcmssIElubmVyZSBTdGFkdIoBCEFsdHN0YWR0igEMSW5uZXJlIFN0YWR0KgtIZWxkZW5wbGF0ejITS2Fpc2VybGljaGUgSG9mYnVyZzIJMTAxMCBXaWVuMgvDlnN0ZXJyZWljaA==;X-APPLE-RADIUS=328.7978217977285;X-APPLE-REFERENCEFRAME=1;X-TITLE=Heldenplatz:geo:48.206686,16.363235\': \'X-APPLE-MAPKIT-HANDLE=CAESxQEIrk0QnJyKy6Oq97MsGhIJFBZgr3QaSEARAAAA8PxcMEAiaAoHQXVzdHJpYRICQVQaBFdpZW4yBFdpZW46BDEwMTByE0thaXNlcmxpY2hlIEhvZmJ1cmeKARcxLiBCZXppcmssIElubmVyZSBTdGFkdIoBCEFsdHN0YWR0igEMSW5uZXJlIFN0YWR0KgtIZWxkZW5wbGF0ejITS2Fpc2VybGljaGUgSG9mYnVyZzIJMTAxMCBXaWVuMgvDlnN0ZXJyZWljaA==\' is not a valid parameter string: too many values to unpack (expected 2)')
error: This might lead to this event being show wrongly or not at all.
````
Look at the quoting and the second X-APPLE-MAPKIT thing. Not sure what that's about.

**Comment by geier** [comment]
The problem seems to be the double equal signs `==`, I'll investigate.

**Comment by geier** [comment]
icalendar does not support binary data in properties, at least for me, the rest of the events should be working fine (but you will effectively remove the location if you modify and save the event with khal).

**Comment by hobarrera** [comment]
> but you will effectively remove the location if you modify and save the event with khal

We *really* should document this, since it's slightly destructive.

**Comment by geier** [comment]
agree, perhaps this event should be marked as readonly, are somehow
protected which can then be overridden

Quoting Hugo Osvaldo Barrera (2016-08-25 00:10:28)

**Comment by geier** [comment]
This should finally be fixed within icalendar, but the patch hasn't made it into a release yet. You should be able to fix this issue with ``pip install --upgrade git+https://github.com/collective/icalendar.git``.

**Comment by geier** [comment]
As a new version of icalendar was released yesterday, I'll close this bug now. Please reopen if you stumble upon it with icalendar > 3.11.4.
