### ISSUE TITLE
Khal as a ics pretty printer

### ISSUE THREAD

**Issue by dopefishh** [pimutils/khal#469]
Since khal has ics parsing and event printing it could be handy to add an option to print an ics file without importing.

`khal printics [-f] ics`

With this functionality khal can be used as a previewer in for example mutt.

In mutt you add something like this:
`auto_view text/calendar`
and in your mailcap:
`text/calendar; khal printics -f '%s'; copiousoutput;`
If necessary I can implement this myself but I thought I'd coin the idea first.

Best,

Mart

**Comment by youngmoney** [comment]
I think this is a great idea and I would certainly use it. It would be great if you would implement it and I'd be happy to help, if not I will eventually get to it

**Comment by geier** [comment]
I'm fine with this going into khal, I won't do it myself though (but I'm happy to review and help).

**Comment by fpytloun** [comment]
+1
I am currently using this one: https://github.com/terabyte/mutt-filters/blob/master/vcalendar-filter

**Comment by geier** [comment]
closed by #478
