### ISSUE TITLE
khal at broken in 0.8.2

### ISSUE THREAD

**Issue by milouse** [pimutils/khal#486]
khal at raise an error when used with a complete datetime

```
$ khal at "27/08/2016"

(works as expected)
$ khal at "09:00"

(works as expected)
$ khal at

(works as expected)
$ khal at "27/08/2016 09:00"
Traceback (most recent call last):
  File "/usr/bin/khal", line 11, in <module>
    load_entry_point('khal==0.8.2', 'console_scripts', 'khal')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/khal/cli.py", line 462, in at
    dtime, _ = aux.guessdatetimefstr(dtime_list, locale)
  File "/usr/lib/python3.5/site-packages/khal/aux.py", line 207, in guessdatetimefstr
    dtstart = fun(dtime_list, dtformat)
  File "/usr/lib/python3.5/site-packages/khal/aux.py", line 71, in datetimefstr
    dtime_list.pop(0)
IndexError: pop from empty list
```

I fix this issue by adding the following lines in /usr/lib/python3.5/site-packages/khal/aux.py at line ~71

```python
if not dtime_list:
    continue
```

The same in context (from line 57)

```python
def datetimefstr(dtime_list, dtformat):
    """
    converts a datetime (as one or several string elements of a list) to
    a datetimeobject

    removes "used" elements of list

    :returns: a datetime
    :rtype: datetime.datetime
    """
    parts = dtformat.count(' ') + 1
    dtstring = ' '.join(dtime_list[0:parts])
    dtstart = datetime.strptime(dtstring, dtformat)
    for _ in range(parts):
        if not dtime_list:
            continue
        dtime_list.pop(0)
    return dtstart
```

**Comment by milouse** [comment]
By the way, is it normal than a precise datetime return something :

```shell
$ khal at "27/08/2016 09:00"
10:00-13:00 27/08/2016: Some event
Location: blahblah
```

But not an imprecise one?

```shell
$ khal at "27/08/2016"
(nothing)
```

In this case, I would have appricated to see all the events planned that day. No?

**Comment by geier** [comment]
@milouse try `khal at 27/08/2016 09:00`, no quotes.

**Comment by geier** [comment]
> By the way, is it normal than a precise datetime return something :
> 
> ```shell
> $ khal at "27/08/2016 09:00"
> 10:00-13:00 27/08/2016: Some event
> Location: blahblah
> ```
no, this event shouldn't be found at all, please try without the quotes, otherwise this is definitively a bug.
> 
> But not an imprecise one?
> 
> ```shell
> $ khal at "27/08/2016"
> (nothing)
> ```
khal at with a day should really throw an exception, as `at` was only supposed to work with datetimes, this *is* a bug, but one that won't get fixed, because querying for events (at, agenda (now renamed to list) and calendar) got completely overhauled. You may want to try the current master for that.
> In this case, I would have appricated to see all the events planned that day. No?

**Comment by milouse** [comment]
> By the way, is it normal than a precise datetime return something :
>
>    $ khal at "27/08/2016 10:00"
>    10:00-13:00 27/08/2016: Some event
>    Location: blahblah
>
>    no, this event shouldn't be found at all, please try without the quotes, otherwise this is definitively a bug.

No, not a bug in that case: I just copy/paste too quickly my exemple. I'd typed `khal at "27/08/2016 10:00"` and not 9:00... I've fix my previous comment to make it clearer

> khal at with a day should really throw an exception, as at was only supposed to work with datetimes, this is a bug, but one that won't get fixed, because querying for events (at, agenda (now renamed to list) and calendar) got completely overhauled. You may want to try the current master for that.

Ok understood that.

**Comment by milouse** [comment]
> @milouse try khal at 27/08/2016 09:00, no quotes.

Ok, I confirm it works without quotes. I'm used to always quotes commands arguments as zsh is a bit more sensible about that (I cannot type raw ^ or *.

Following my habits, I should have type the following : `khal at '27/08/2016' '10:00'`, which works too.

I'd suggest to modify a bit the man page to indicate that `at` must be used this way:

```
at
    shows all events scheduled for a given datetime. khal at should be supplied
    with a date and time, a time (the date is then assumed to be today) or the 
    string now. at defaults to now.

    khal at [-a CALENDAR ... | -d CALENDAR ...] [[DATE] TIME | now]
```

To make it clear the space between date and time is required (two args, not only one). Are you interested by a pull request about that ?

**Comment by geier** [comment]
@milouse yes, sure improvement are always welcome. Please note, that there are two places where usage is documented, once in `cli.py` and once in `usage.rst`, you might want to look at (and improve) both. For documenting the old version, have a look at branch `v0.8.x`, for the latest one at `master`.

**Comment by youngmoney** [comment]
I do not believe this is a problem in master (though could be wrong, have not pulled in a bit). Now that at uses the list command, the string is split by whitespaces so the quotes should make no difference

**Comment by geier** [comment]
I'll close this, but feel free to send a PR regarding the documentation.

**Comment by milouse** [comment]
> I do not believe this is a problem in master (though could be wrong, have not pulled in a bit). Now that at uses the list command, the string is split by whitespaces so the quotes should make no difference

I just try today with the last 0.9.2 and the problem is still there. Thus I push the PR above.

**Comment by edi9999** [comment]
For those still having the issue, the right input seems to be in this format 

```
khal at '11.10.2018' '17:00'
```
