### ISSUE TITLE
delete events from khal

### ISSUE THREAD

**Issue by geier** [pimutils/khal#49]
suggested usage:

`khal --delete 04.15 09:00 11:30 some event`

`khal --edit 04.15 09:00 11:30 some event - new time 09:00 12:00`

(not sure how practical that really is)

**Comment by lucc** [comment]
Or the shell completion could get the uids and complete on them. Zsh can present the user with augmented completion entries so that the human readable version of the event could be displayed next to the uid. The git zsh completion presents recent commit ids in this way.

**Comment by geier** [comment]
@lucc good idea, example with zsh: `kill` <kbd>tab</kbd>

**Comment by geier** [comment]
as editing has been merged, I'll update the title.

**Comment by geier** [comment]
this can now be done with the new `edit` command.
