### ISSUE TITLE
DTSTART/DTEND has invalid or incomprehensible timezone information from Outlook appointment

### ISSUE THREAD

**Issue by waynew** [pimutils/khal#498]
I have the following appointment:

```
BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Pacific Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER:John Doe
DESCRIPTION;LANGUAGE=en-US:Wrong
UID:A15C1BDB-F417-463F-A6FA-5FBAE07805A8
SUMMARY;LANGUAGE=en-US:Broken time
DTSTART;TZID=Pacific Standard Time:20160902T123000
DTEND;TZID=Pacific Standard Time:20160902T130000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20160901T174424Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION;LANGUAGE=en-US:Phone (1.555.555.5555)
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:1234
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
BEGIN:VALARM
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT15M
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR
```

khal imports this file just fine, A-OK. It's got the right time displayed and everything.

However, as when I go to edit the description in interactive mode and *save* the appointment I get these warnings:

```
warning: DTSTART has invalid or incomprehensible timezone information in A15C1BDB-F417-463F-A6FA-5FBAE07805A8.ics in me@gmail.com
warning: DTEND has invalid or incomprehensible timezone information in A15C1BDB-F417-463F-A6FA-5FBAE07805A8.ics in me@gmail.com
```

Apparently something is wonky now that I look at it, because when I sync with my gmail calendar the time shifts to 7:30AM CDT, instead of the 2:30PM it *should* be.

Interestingly, if I edit the time of the appointment (say, change it to 2:29 PM) then save it, it gets the proper time.

Any clue what's going on here?

**Comment by geier** [comment]
What version of icalendar are you using? (It works just fine for me)

**Comment by waynew** [comment]
3.9.2

**Comment by waynew** [comment]
I upgraded my icalendar version:

```
$ pip freeze | grep icalendar
icalendar==3.10
```

But I still get the funky date behavior. I just tried adding another appointment, with similar behavior - the time gets screwed up. I even upgraded khal to 0.8.3.

**Comment by waynew** [comment]
Could it be vdirsyncer messing with the time? Actually, I don't believe it is... well, sort of. I think it's the appointment info not being normalized and then Google calendar updating the appointment which screws it up when it's synced again. I must not have really noticed what was going on?

Here's what I've done:

- save the appointment as `bogus.ics`
- khal import bogus.ics (yes, import it)
- note the time - for me it shows up as 2:30-3:00 PM, which I believe is correct
- khal search Broken
- note that the time has changed - for me it's 12:30-1:00PM.
- vdirsyncer sync
- khal search Broken
- note that the time is still the same, though also incorrect
- vdirsyncer sync
- khal search Broken

Now the time on the appointment is *way* off - 7:30-8:00 AM for me. @geier do you see this behavior, too?

**Comment by geier** [comment]
No, vdirsyncer should not be able to mess with the time. And yes, something is wrong here...

**Comment by geier** [comment]
Ok, I now understand at least one way how this can happen: import does not save the timezone specification from the original file, working on it.

**Comment by geier** [comment]
If you have the time and are up to it, please have a look at branch `fix_import_timezone` and give it a try.

Refactoring and testing is coming later, but it works for me™

**Comment by waynew** [comment]
+1 This appears to work for me, too. Excellent, and thank you!
