### ISSUE TITLE
No events

### ISSUE THREAD

**Issue by s-hell** [pimutils/khal#499]
I can't find any event in my calendar.

This is my config:
`[calendars]
[[stefan]]
path = /home/shellmann/.calendars/defaultcalendar/
readonly = True

[locale]
timeformat = %H:%M
dateformat = %d.%m.%y
longdateformat = %d.%m.%Y
datetimeformat = %d.%m.%y %H:%M
longdatetimeformat = %d.%m.%Y %H:%M`

The verbose output:

> debug: khal 0.8.3
debug: using the config file at /home/shellmann/.config/khal/khal.conf
debug: Found no or empty file `color` in /home/shellmann/.calendars/defaultcalendar/
debug: Using config:
debug: [calendars]
debug:   [[stefan]]
debug:     path: /home/shellmann/.calendars/defaultcalendar/
debug:     readonly: True
debug:     type: birthdays
debug:     color: None
debug: [locale]
debug:   timeformat: %H:%M
debug:   dateformat: %d.%m.%y
debug:   longdateformat: %d.%m.%Y
debug:   datetimeformat: %d.%m.%y %H:%M
debug:   longdatetimeformat: %d.%m.%Y %H:%M
debug:   encoding: utf-8
debug:   firstweekday: 0
debug:   unicode_symbols: True
debug:   default_timezone: Europe/Berlin
debug:   local_timezone: Europe/Berlin
debug:   weeknumbers: False
debug: [sqlite]
debug:   path: /home/shellmann/.local/share/khal/khal.db
debug: [keybindings]
debug:   up: ['up', 'k']
debug:   down: ['down', 'j']
debug:   right: ['right', 'l', ' ']
debug:   left: ['left', 'h', 'backspace']
debug:   new: ['n']
debug:   delete: ['d']
debug:   view: ['enter', 'tab']
debug:   today: ['t']
debug:   save: ['meta enter']
debug:   duplicate: ['p']
debug:   export: ['e']
debug:   mark: ['v']
debug:   other: ['o']
debug:   search: ['/']
debug: [default]
debug:   default_command: calendar
debug:   default_calendar: None
debug:   show_all_days: False
debug:   days: 2
debug:   print_new: False
debug:   highlight_event_days: False
debug: [view]
debug:   event_view_weighting: 1
debug:   event_view_always_visible: False
debug:   theme: dark
debug:   frame: False
debug:   bold_for_light_color: True
debug: [highlight_days]
debug:   method: fg
debug:   color: 
debug:   multiple: 
debug:   default_color: 
debug: created version table
debug: Updating 2b10e468-cf89-4400-af1f-b79ddc6482cd.vcf because 1472829880900319232.000000000 != None
debug: Updating d6cee8b565ad4b50b778db336285d248.vcf because 1472829880098319360.000000000 != None
debug: Updating 789d3c269451456fa77d600962cd6ce5.vcf because 1472829881282319104.000000000 != None
debug: Updating 387fa796-a1fb-453f-87f2-80174ce08c03.vcf because 1472829880551319296.000000000 != None
debug: Updating 20150923T050757Z-30690_b6e7c07212c44155.vcf because 1472829879903319296.000000000 != None
debug: Updating 20150813T064312Z-16172_DEFACE.vcf because 1472829880555319296.000000000 != None
debug: Updating 9595b7a8-02d2-4d8f-a2b5-a8d7db878d13.vcf because 1472829880703319296.000000000 != None
debug: Updating 9ed11d8c107e4917be71f38ecd22b16a.vcf because 1472829880066319360.000000000 != None
debug: Updating e225c0f4-c314-4bbe-8449-26842c8dd5a4.vcf because 1472829879788319232.000000000 != None
debug: Updating 3bf92eef-3dd6-4be8-a37c-79f32c13dfa0.vcf because 1472829881061319168.000000000 != None
debug: Updating 9f14aaedac2f43fcbfd7c4f0a67688b8.vcf because 1472829881224319232.000000000 != None
debug: Updating 4ed863a888ff4bd49eb5ab831f0d6c8f.vcf because 1472829880864319232.000000000 != None
debug: Updating 0ae0220a74214903a97a9f11a961b8e2.vcf because 1472829879878319360.000000000 != None
debug: Updating aa07678fed724c46881d2eac3f328dde.vcf because 1472829879577319168.000000000 != None
    Mo Tu We Th Fr Sa Su     No events
Sep 29 30 31  1  2  3  4     
     5  6  7  8  9 10 11     
    12 13 14 15 16 17 18     
    19 20 21 22 23 24 25     
Oct 26 27 28 29 30  1  2     
     3  4  5  6  7  8  9     
    10 11 12 13 14 15 16     
    17 18 19 20 21 22 23     
    24 25 26 27 28 29 30     
Nov 31  1  2  3  4  5  6     
     7  8  9 10 11 12 13     
    14 15 16 17 18 19 20     
    21 22 23 24 25 26 27     
Dec 28 29 30  1  2  3  4 

I can't find any error. Any advise?

**Comment by geier** [comment]
by default, khal only shows events for today and the next two days. Do you have any events scheduled for that time? (If not, have a look at `khal calendar --help` to see how to query for longer time ranges).

**Comment by s-hell** [comment]
Yes i have. I've changed vdirsync from vcf to ics. Then khal shows events....

Am 3. September 2016 14:00:01 MESZ, schrieb Christian Geier <notifications@github.com>:
>by default, khal only shows events for today and the next two days. Do
>you have any events scheduled for that time? (If not, have a look at
>`khal calendar --help` to see how to query for longer time ranges).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/issues/499#issuecomment-244542518

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by geier** [comment]
I guess we can close this one, right?
