### ISSUE TITLE
[possible] pip3 on mac install 0.8.3, has 0.8.2 source

### ISSUE THREAD

**Issue by youngmoney** [pimutils/khal#500]
not sure why this is going on, might be a personal issue but freshly install khal via pip3 on mac installs a khal with --version 0.8.3 but the source is not right (I checked it), it does not have any of the new commands nor does it even like my config file since it has globs

**Comment by geier** [comment]
this is intentionally, those changes will be released with 0.9. 0.8.3 only fixed some minor bugs, no functional changes.
