### ISSUE TITLE
Configuration manual not clear with respect to type = http

### ISSUE THREAD

**Issue by MikePetullo** [pimutils/khal#501]
The "Full Configuration Manual" for vdirsyncer provides the following example for configuring http-type synchronization:

[pair holidays]
a = holidays_local
b = holidays_remote

[storage holidays_local]
type = filesystem
path = ~/.config/vdir/calendars/holidays/
fileext = .ics

[storage holidays_remote]
type = http
url = https://example.com/holidays_from_hicksville.ics

I recently configured vdirsyncer to perform this type of synchronization. However, I found it necessary to add the line "collections = null" to the definition of "pair holidays". Newer versions of vdirsyncer require the collections statement. It took me some time to realize that I should set it to null. I eventually found this helpful:

https://github.com/pimutils/vdirsyncer/issues/344

Please consider adding the required collections statement to the configuration example.

**Comment by untitaker** [comment]
Hello Mike, this is the wrong bugtracker, please refile at https://github.com/pimutils/vdirsyncer

**Comment by MikePetullo** [comment]
Sorry, I obviously made a mistake. I just submitted a report to the vdirsyncer project. Thank you.

**Comment by geier** [comment]
see  https://github.com/pimutils/vdirsyncer/issues/497
