### ISSUE TITLE
Use threadsafe sqlite when possible

### ISSUE THREAD

**Issue by teto** [pimutils/khal#507]
(Follow up on an irc discussion)
I've started writing a khal module for i3pystatus (https://github.com/teto/i3pystatus/tree/calendars). each module is run in its own thread which creates problem when 
running for instance ` self.collection.get_events_on( date.today() ` :
```
qlite3.ProgrammingError: SQLite objects created 
                        in a thread can only be used in that same        
                       thread.The object was created in thread id       
                       139940783351552 and this is thread id            
                       139940518270720
```
I added a parameter to khal "sqlite3.connect" to not check for the thread (works fine) but this can be bad if sqlite doesn't support it. The C API has `sqlite3_threadsafe()` so maybe khal could check if system sqlite is threadsafe and enable it if it is ?
http://stackoverflow.com/a/2894830/2131903

**Comment by geier** [comment]
Feel free to send a PR :)

**Comment by teto** [comment]
Closing as not needed anymore and even so there would be no easy way to achieve it
