### ISSUE TITLE
Air France's ics has invalid or incomprehensible timezone information

### ISSUE THREAD

**Issue by nim65s** [pimutils/khal#512]
Hi,

This ics raises warnings on DTSTART & DTEND, both with 0.8.3 & 9d6ba73

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//dmfs.org//mimedir.icalendar//EN
BEGIN:VEVENT
DTSTART;TZID="GMT+02:00":20160914T183000
DESCRIPTION:Vol n°AF 6147\nHeure locale de décollage : 14 sept. 20h30\nHe
 ure locale d'atterrissage : 14 sept. 21h50\nRéf. de réservation : XXXXXX
SUMMARY:Vol Toulouse - Paris
LOCATION:Aéroport Blagnac (TLS)
TRANSP:OPAQUE
DTEND;TZID="GMT+02:00":20160914T195000
LAST-MODIFIED:20160916T215911Z
DTSTAMP:20160916T215911Z
CREATED:20160916T215911Z
UID:399221c0-9ecf-429e-83ee-38d8edec4ee5.1474063151020
END:VEVENT
END:VCALENDAR
```

This is not a big issue for me, I'm just wanted to let you know about it.

**Comment by geier** [comment]
Hi, thank you for reporting this. Is this the whole icalendar and directly in the form as you get it from AirFrance? If so, the timezone information is just missing and there is nothing we can do about it.

**Comment by nim65s** [comment]
Hum… No, this file had already been processed by Thunderbird & OwnCloud, sorry. Here is the original file from AirFrance:

```
BEGIN:VCALENDAR
PRODID:-//AFKLM//CRMPUSH//TKT//FR
VERSION:2.0
CALSCALE:GREGORIAN
UID:b655c530-083a-41ac-90d3-3da2653fd614
BEGIN:VEVENT
DTSTAMP:20160906T115626Z
DTSTART:20160914T183000Z
DTEND:20160914T195000Z
SUMMARY:Vol Toulouse-Paris
CLASS:PRIVATE
SEQUENCE:1
TRANSP:OPAQUE
STATUS:CONFIRMED
DESCRIPTION:Vol AF6147 Toulouse (TLS) - Paris(ORY)\nHeure Limite d'Enregistrement : 20:10\nHeure locale de départ (Toulouse) : 14/09/2016\, 20:30\nHeure locale d'arrivée (Paris) : 14/09/2016\, 21:50\nRéférence de réservation : XXXXXX
LOCATION:Aéroport Blagnac (TLS) - Terminal 
UID:f734bf28-a1f1-4be9-9270-0fa557496a16
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20160906T115626Z
DTSTART:20160919T065500Z
DTEND:20160919T080500Z
SUMMARY:Vol Paris-Toulouse
CLASS:PRIVATE
SEQUENCE:1
TRANSP:OPAQUE
STATUS:CONFIRMED
DESCRIPTION:Vol AF6110 Paris (ORY) - Toulouse(TLS)\nHeure Limite d'Enregistrement : 08:35\nHeure locale de départ (Paris) : 19/09/2016\, 08:55\nHeure locale d'arrivée (Toulouse) : 19/09/2016\, 10:05\nRéférence de réservation : XXXXXX
LOCATION:Aéroport Orly (ORY) - Terminal W 
UID:1d70b739-0891-4ef6-918f-866759fbdce3
END:VEVENT
END:VCALENDAR
```

So the TZ information is still missing, I'll deal with it, thanks :)

**Comment by geier** [comment]
The original ics file looks fine, start and end times are given in UTC/Zulu time, some other program must have changed the timezones and than not included them. It looks like you synced with CalDAV sync, did you add in on an android phone? If so, with which app?

**Comment by nim65s** [comment]
This ics, like most of mines, have been synced between some thunderbirds, an owncloud, CalDAV sync, and the Google Agenda android app.  The issue only concerns Air France's .ics, and they might have been synced from AirFrance's android app, I don't remember… 
I will provide more relevant debugging informations on my next trip :)
