### ISSUE TITLE
Ability to configure default event format of `list` in config file

### ISSUE THREAD

**Issue by untitaker** [pimutils/khal#515]
I'd like to change my `khal list` to exclude DESCRIPTION, but include LOCATION. The current way to do this is to pass `-f`, but I want to set that in the config file.

**Comment by geier** [comment]
in [view] set:
agenda_event_format: {calendar-color}{start-end-time-style} {title} {location}{reset}

Quoting Markus Unterwaditzer (2016-10-06 12:16:17)

**Comment by untitaker** [comment]
I see, couldn't find it, thanks.
