### ISSUE TITLE
import ICS from stdin

### ISSUE THREAD

**Issue by xals** [pimutils/khal#522]
Hi,

Wanting to use khal from mutt, I think it should be quite nice to be able to import a .ics file from stdin, for example typing in mutt:

```
| khal import -a personal -
```

This would avoid manually building a unique name for the .ics file.

**Comment by geier** [comment]
This sounds like a reasonable idea (and should be implemented rather easily).

**Comment by pfertyk** [comment]
I think it should work already by default, at least according to [click's documentation](http://click.pocoo.org/5/arguments/#file-arguments). I created a simple program:
```python
import click


@click.command()
@click.argument('input', type=click.File('rb'), nargs=-1)
def dots(input):
    for ics in input:
        ics_str = ics.read()
        click.echo(ics_str)


if __name__ == '__main__':
    dots()
```
It works with single dash, multiple single dashes and mixed dashes and filenames. When using multiple dashes (`python main.py - - file.txt`), I need to send Ctrl+D multiple times:
```
hi
hi

hey
hey

Hello, content from file.txt!
```

I modified the existing test a bit (`cli_test.py:test_import`) to check if dash will work and the test passed, however the `ics` value was an empty string. I think we only need to mock the stdin for the test.

@xals could you confirm that the feature is already working?

**Comment by geier** [comment]
I believe the issue is that `khal import -` will redirect standard in
*and* out, this might work in batch mode, but the interactive part
probably won't work. 

Quoting pfertyk (2016-11-22 16:35:56)
