### ISSUE TITLE
Multiple events in one ics file

### ISSUE THREAD

**Issue by benf33** [pimutils/khal#525]
Can we have the ability for khal to work on one ics file per calendar rather than one ics file per event ?

**Comment by untitaker** [comment]
You can work around this by using vdirsyncer to synchronize from `singlefile` storage to `filesystem`. Then you'd modify a folder structure with one event per file using khal and use vdirsyncer to sync to a structure with one calendar per file.

**Comment by benf33** [comment]
All right, I see what you mean. Makes things a little trickier but should make it.
Thank you.
