### ISSUE TITLE
Have calendars with "low priority coloring"

### ISSUE THREAD

**Issue by HappyTetrahedron** [pimutils/khal#526]
Hello

I've been using khal for a while now and I love it, but there's one little feature I'd love to have. 

I'd like to be able to specify a calendar to have "low priority coloring", which means that the events get a color in the agenda, but that color doesn't cause the "multiple" color to appear when an event from this calendar conflicts with events from the other. In other words, the colors of some calendars should have precedence over the color of other calendars.

I think this is probably better explained with an example: I have my lecture schedule in one calendar, and several other calendars with appointments for various groups. Naturally, these appointments are more important since my schedule hardly ever changes anyway. Now, even when I specify no color for the schedule calendar, the "multiple" color shows up on the calendar when an appointment is on a day where I also have a lecture. I'd like the color of the appointment to have precedence, so that I can immediately see from which calendar it is, without having to entirely ignore the schedule calendar using the -i option.

Maybe this could be generalized into priorities for the calendars. The color of a calendar with higher priority suppresses the color of one with lower priority, but when two calendars with equal priority have a conflict, the "multiple" color shows up.

**Comment by geier** [comment]
This sounds like a very interesting enhancement! If anyone is interested in implementing this, I'll gladly help over any bumps, but I probably won't have time for this in the near future to do it myself.
