### ISSUE TITLE
Error with "Apple-Structured- Location"

### ISSUE THREAD

**Issue by TheRojam** [pimutils/khal#531]
Given `khal -v 0.8.4`
And `vdirsyncer - v  0.14.0`
And `Python 3.5.2`
And `ArchLinux 4.8.10-1 x86_64`
And multiple ics-file from google-calendar
When I open khal fo the first time
Then I see multiple errors

>  ```
> 
> `error: Errors occurred when parsing Private/8B1AC699-5D5A-432C-980D-633CCDE28548.ics for the following reasons:
> error: (None, 'Content line could not be parsed into parts: \'X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Leipzig, Deutschland";X-APPLE-MAPKIT-HANDLE=CAES4wEaEgkvUFJgAaxJQBGWCFT/IMooQCKEAQoHR2VybWFueRICREUaBlNheG9ueSoHTGVpcHppZzIHTGVpcHppZzoFMDQzMTVCCE5ldXN0YWR0UhFLb2hsZ2FydGVuc3RyYcOfZVoCMTNiFEtvaGxnYXJ0ZW5zdHJhw59lIDEzigELWmVudHJ1bS1Pc3SKAQNPc3SKAQhOZXVzdGFkdCoUS29obGdhcnRlbnN0cmHDn2UgMTMyFEtvaGxnYXJ0ZW5zdHJhw59lIDEzMg0wNDMxNSBMZWlwemlnMgdHZXJtYW55ODlAAA==;X-APPLE-RADIUS=49.91306996449045;X-APPLE-REFERENCEFRAME=1;X-TITLE="Kohlgartenstraße 13":geo:51.343792,12.394783\': \'X-APPLE-MAPKIT-HANDLE=CAES4wEaEgkvUFJgAaxJQBGWCFT/IMooQCKEAQoHR2VybWFueRICREUaBlNheG9ueSoHTGVpcHppZzIHTGVpcHppZzoFMDQzMTVCCE5ldXN0YWR0UhFLb2hsZ2FydGVuc3RyYcOfZVoCMTNiFEtvaGxnYXJ0ZW5zdHJhw59lIDEzigELWmVudHJ1bS1Pc3SKAQNPc3SKAQhOZXVzdGFkdCoUS29obGdhcnRlbnN0cmHDn2UgMTMyFEtvaGxnYXJ0ZW5zdHJhw59lIDEzMg0wNDMxNSBMZWlwemlnMgdHZXJtYW55ODlAAA==\' is not a valid parameter string: too many values to unpack (expected 2)')
> error: This might lead to this event being show wrongly or not at all.
> error: Errors occurred when parsing Private/04B3916E-BA33-4917-B966-2DDF2C47CC84.ics for the following reasons:
> error: (None, 'Content line could not be parsed into parts: \'X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Hohepfortestraße 37, 39104 Magdeburg, Germany";X-APPLE-MAPKIT-HANDLE=CAES4wEIrk0QiN+TlIG2guxSGhIJTPxR1JkRSkARXFX2XRFMJ0AiewoHR2VybWFueRICREUaDVNheG9ueS1BbmhhbHQqCU1hZ2RlYnVyZzIJTWFnZGVidXJnOgUzOTEwNEIIQWx0c3RhZHRSEUhvaGVwZm9ydGVzdHJhw59lWgIzN2IUSG9oZXBmb3J0ZXN0cmHDn2UgMzeKAQhBbHRzdGFkdCoTQWdlbnR1ciBmw7xyIEFyYmVpdDIUSG9oZXBmb3J0ZXN0cmHDn2UgMzcyDzM5MTA0IE1hZ2RlYnVyZzIHR2VybWFueQ==;X-APPLE-RADIUS=49.91307246156039;X-APPLE-REFERENCEFRAME=1;X-TITLE="Agentur für Arbeit":geo:52.137507,11.648570\': \'X-APPLE-MAPKIT-HANDLE=CAES4wEIrk0QiN+TlIG2guxSGhIJTPxR1JkRSkARXFX2XRFMJ0AiewoHR2VybWFueRICREUaDVNheG9ueS1BbmhhbHQqCU1hZ2RlYnVyZzIJTWFnZGVidXJnOgUzOTEwNEIIQWx0c3RhZHRSEUhvaGVwZm9ydGVzdHJhw59lWgIzN2IUSG9oZXBmb3J0ZXN0cmHDn2UgMzeKAQhBbHRzdGFkdCoTQWdlbnR1ciBmw7xyIEFyYmVpdDIUSG9oZXBmb3J0ZXN0cmHDn2UgMzcyDzM5MTA0IE1hZ2RlYnVyZzIHR2VybWFueQ==\' is not a valid parameter string: too many values to unpack (expected 2)')
> error: This might lead to this event being show wrongly or not at all.
> error: Errors occurred when parsing Die PARTEI Magdeburg/E0A89148-7F44-41E5-AC22-40D329E50ACA.ics for the following reasons:
> error: (None, 'Content line could not be parsed into parts: \'X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS="Erich-Weinert-Straße 27, 39104 Magdeburg, Germany";X-APPLE-MAPKIT-HANDLE=CAES+QEIrk0Qqc7Sx7S+94mXARoSCRS0yeGTDkpAEZSFr691QSdAIoMBCgdHZXJtYW55EgJERRoNU2F4b255LUFuaGFsdCoJTWFnZGVidXJnMglNYWdkZWJ1cmc6BTM5MTA0QghBbHRzdGFkdFIVRXJpY2gtV2VpbmVydC1TdHJhw59lWgIyN2IYRXJpY2gtV2VpbmVydC1TdHJhw59lIDI3igEIQWx0c3RhZHQqG0FNTyBLdWx0dXIgdW5kIEtvbmdyZcOfaGF1czIYRXJpY2gtV2VpbmVydC1TdHJhw59lIDI3Mg8zOTEwNCBNYWdkZWJ1cmcyB0dlcm1hbnk=;X-APPLE-RADIUS=49.91307238765316;X-APPLE-REFERENCEFRAME=0;X-TITLE="AMO Kultur und Kongreßhaus":geo:52.113888,11.627851\': \'X-APPLE-MAPKIT-HANDLE=CAES+QEIrk0Qqc7Sx7S+94mXARoSCRS0yeGTDkpAEZSFr691QSdAIoMBCgdHZXJtYW55EgJERRoNU2F4b255LUFuaGFsdCoJTWFnZGVidXJnMglNYWdkZWJ1cmc6BTM5MTA0QghBbHRzdGFkdFIVRXJpY2gtV2VpbmVydC1TdHJhw59lWgIyN2IYRXJpY2gtV2VpbmVydC1TdHJhw59lIDI3igEIQWx0c3RhZHQqG0FNTyBLdWx0dXIgdW5kIEtvbmdyZcOfaGF1czIYRXJpY2gtV2VpbmVydC1TdHJhw59lIDI3Mg8zOTEwNCBNYWdkZWJ1cmcyB0dlcm1hbnk=\' is not a valid parameter string: too many values to unpack (expected 2)')
> error: This might lead to this event being show wrongly or not at all.
> ```

I think this is not a real error, but khal does not how to handle these location entries from apple-calendar.

**Comment by geier** [comment]
The problem is, that the icalendar library we are using does currently not support these Apple locations (see #467). Be aware, that if you change any of those events, the location data might get lost.

**Comment by geier** [comment]
And sorry that you are having such a rocky start with vdirsyncer & khal.
