### ISSUE TITLE
Cannot create "daily" recurrences 

### ISSUE THREAD

**Issue by wavexx** [pimutils/khal#538]
Currently you can set "weekly, monthly, yearly" for the recurrence frequency, but "daily" is missing.
Daily is also important (when #62 is fixed) to create events that happen at fixed intervals such as "every 3 days".

**Comment by geier** [comment]
Sounds like a good enhancement.

**Comment by Dakurels** [comment]
I would like to take care of this issue. Is there any place where I should start?

**Comment by geier** [comment]
Hi and welcome to khal!
Grepping through the source tree for `weekly` should point you to all
the places that need a change.
If that doesn't help, feel free to ask more questions here and/or on IRC
(#pimutils@Freenode).

Quoting Szymon Stankiewicz (2017-01-18 16:25:44)
