### ISSUE TITLE
"Content line could not be parsed into parts" exceptions flood the screen

### ISSUE THREAD

**Issue by hobarrera** [pimutils/khal#541]
Whenever I run `khal`, I get a huge stream of exceptions that look like this:

Followed by about 88kB of base64 data (each exception!)

```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/icalendar/parser.py", line 230, in from_ical
    key, val = q_split(param, '=')
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/icalendar/parser.py", line 336, in parts
    strict=self.strict)
  File "/usr/lib/python3.5/site-packages/icalendar/parser.py", line 255, in from_ical
    % (param, exc))
ValueError: 'X-ABCROP-RECTANGLE=ABClipRect_1&1&0&197&197&LfFMvJFI9KQ0gUZJ1U5ieA==' is not a valid parameter string: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/khal/khalendar/khalendar.py", line 271, in _update_vevent
    update(event.raw, href=href, etag=etag, calendar=calendar)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 276, in update_birthday
    ical = icalendar.Event.from_ical(vevent)
  File "/usr/lib/python3.5/site-packages/icalendar/cal.py", line 328, in from_ical
    name, params, vals = line.parts()
  File "/usr/lib/python3.5/site-packages/icalendar/parser.py", line 346, in parts
    % (self, exc)
ValueError: Content line could not be parsed into parts:
```

In total, I get 2769530bytes of data, in 430 lines in total.

This is huge, and there's really no way to silence these warning, so I see a few problems here:

1. Not sure why reading this data fails.
1. Do we really care about these props anyway?
1. There's no way to mute these warnings, so I see them after every time vdirsyncer updates contacts.

**Comment by geier** [comment]
The underlying bug is #467, but obviously, you shouldn't be spammed with error messages. I'll have a look.

**Comment by hobarrera** [comment]
Yup, looks like it's related. The slight difference is that these are contacts (so we only need to be able to read, we'll never write to these, so it doesn't matter if we skip attributes).

**Comment by geier** [comment]
ah, sorry, looks like I didn't properly read your report. That obviously
makes dealing wwith this somewhat simpler.

Quoting Hugo Osvaldo Barrera (2016-12-16 19:56:30)

**Comment by geier** [comment]
I now intend to fix this bug upstream, see https://github.com/collective/icalendar/pull/207, for now, a solution for you could be to install icalendar from my respective branch.

**Comment by hobarrera** [comment]
Thanks for pinpointing this! I clearly was not familiar with the icalendar (nor the format nor the library) to have found this so fast.

**Comment by hobarrera** [comment]
Thanks for pinpointing this! I clearly was not familiar with the icalendar (nor the format nor the library) to have found this so fast.

**Comment by geier** [comment]
This should finally be fixed within icalendar, but the patch hasn't made it into a release yet. You should be able to fix this issue with ``pip install --upgrade git+https://github.com/collective/icalendar.git``.

**Comment by geier** [comment]
As a new version of icalendar was released yesterday, I'll close this bug now. Please reopen if you stumble upon it with icalendar > 3.11.4.
