### ISSUE TITLE
Unable to select text in interactive view

### ISSUE THREAD

**Issue by samdmarshall** [pimutils/khal#544]
When viewing calendar events in `ikhal` or `khal interactive`, the user cannot select text that is displayed in the description or notes section of an event. So, for example, if the additional info contains a URL, there is no way to copy that URL without exporting the event out to a file first. Ideally this should be selectable so that the user interact with the contents of an event.

**Comment by geier** [comment]
I believe this is a "feature" in urwid (the pseudo graphics toolkit we are using), so that you can click on items to make them focused. I'll investigate.

What works for me™ (ugh! sorry!) is holding shift and selecting at the same time.

**Comment by samdmarshall** [comment]
That doesn't work at all for me 😢

**Comment by geier** [comment]
hmm, what OS and terminal are you using?

**Comment by samdmarshall** [comment]
```
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67
```

and Terminal.app.

**Comment by geier** [comment]
Ok, that I can't check at the moment, will try on next chance.

**Comment by samdmarshall** [comment]
Ah, I finally figured this out, I have to use the `fn` key on OS X + Terminal.app to do text selection. This is still a pain but possible. It is a byproduct of urwid's control schemes -- not sure if anything can be done about this without fundamentally changing urwid or the graphics library used.

**Comment by geier** [comment]
Sorry for not checking up on this. It looks like we need to decide if we want to let urwid handle the mouse or not (`MainLoop(handle_mouse=True)`). Perhaps we could make that configurable.

**Comment by samdmarshall** [comment]
It might also be worth-while to see if urwid can be modified to accept partial mouse input without blocking all mouse access, eg: enable scrolling but not clicks.
