### ISSUE TITLE
Can't create event for 2017 year and later

### ISSUE THREAD

**Issue by MobDev-Hobby** [pimutils/khal#545]
If I try to create event to any 2017th year date, ex:
`khal new --calendar events-28354 2017-01-01 2017-01-01 Test2017`
It creates event for 2016 year, but shows it if I watch agenda:
```
khal agenda 2017-01-01
2016-01-01
Test2017
```
If I watch 2016 agenda, it shows event too:
```
khal agenda 2016-01-01
2016-01-01
Test2017
```
In .ics file it contains 2016 year:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//CALENDARSERVER.ORG//NONSGML Version 1//EN
BEGIN:VEVENT
SUMMARY:Test2017
DTSTART;VALUE=DATE:20160101
DTEND;VALUE=DATE:20160102
DTSTAMP;VALUE=DATE-TIME:20161230T152057Z
UID:BE40HX9V8NBQTLNB5BTPYVK91WLCSQHKRCL0
END:VEVENT
END:VCALENDAR

```
khal, version 0.8.3

UPD: khal, version 0.8.4 has the same error

**Comment by geier** [comment]
As I cannot reproduce this, can you show your configuration file?

**Comment by MobDev-Hobby** [comment]
Yes, of course 
**.config/khal/khal.conf** 
```
[calendars]
[[support_offline]]
path = ~/.vdirsyncer/calendar
type = discover

[locale]
timeformat = %H:%M
dateformat = %Y-%m-%d
longdateformat = %Y-%m-%d
datetimeformat = %Y-%m-%d %H:%M
longdatetimeformat = %Y-%m-%d %H:%M
```
Seems like it happens because of [here](https://github.com/pimutils/khal/blob/v0.8.4/khal/aux.py#L202) works wrong with short date. If I remove [line 202](https://github.com/pimutils/khal/blob/v0.8.4/khal/aux.py#L202) and [line 198](https://github.com/pimutils/khal/blob/v0.8.4/khal/aux.py#L198), it works OK:
`khal new --calendar events-28354 2017-01-01 2017-01-01 Test2017FixeTest`
```
khal agenda 2017-01-01
2017-01-01
Test2017FixeTest
```
