### ISSUE TITLE
khal import -a/--include-calender doesn't work when there are multiple "writable" calendars

### ISSUE THREAD

**Issue by samdmarshall** [pimutils/khal#549]
Ran into a problem this morning when trying to setup my .mailcap to have `alot` import calendar invites into `khal`. The problem exists when trying to specify which calendar to import the event into, there is extremely divergent behavior under `--batch`.

Without specifying `--batch` i get the prompt asking me to confirm which calendar to use. The default option here is the default specified in my khal.conf. However, when specifying `--batch`, khal will select the first calendar from, what seems to be an alphabetically sorted list,  [`collection.writable_names`](https://github.com/pimutils/khal/blob/master/khal/controllers.py#L558). This is *not* the same as the default calendar specified in the configuration file. 

Additionally this issue has uncovered a bug where multiple calendars that are marked as readonly in the `khal.conf` file, are able to be written to by khal during this described importing process. 

Version: `khal, version 0.8.4` (via homebrew)

**Comment by untitaker** [comment]
In #548 [there's a commit](https://github.com/pimutils/khal/pull/548/commits/6db7efd032269bce3db0821f869554844c2cc5a3) that looks like it fixes this issue.

**Comment by untitaker** [comment]
@samdmarshall Could you try the master branch of khal?

**Comment by samdmarshall** [comment]
the master branch? as far as I can tell the commits you referenced aren't in master yet as the PR isn't merged.

**Comment by untitaker** [comment]
I cherry-picked the relevant commit into master

On 7 January 2017 17:16:16 CET, Samantha Marshall <notifications@github.com> wrote:
>the master branch? as far as I can tell the commits you referenced
>aren't in master yet as the PR isn't merged.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/issues/549#issuecomment-271092718

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by geier** [comment]
@samdmarshall did you have the time to check if this now behaves as expected?

**Comment by samdmarshall** [comment]
Sorry for the delay, yeah I have tried this out against master and it now behaves as expected. Thanks for the quick turn-around on this!
