### ISSUE TITLE
Define ICS format for DTSTART

### ISSUE THREAD

**Issue by cedricpim** [pimutils/khal#550]
I am currently using khal with vdirsyncer and radicale, and I am currently getting an issue because an event created on khal has the format `VALUE=DATE-TIME` for `DTSTART`. Is it possible to define the format to be used for creating the ics?

`VALUE=DATE-TIME` is a valid format but since dateutils seems to be taking its time to allow it, I was wondering if anything could be done on the khal side.

Thanks for this software.

**Comment by geier** [comment]
I'm not sure I completely understand the problem yet. Are you saying that radicale doesn't accept something like `DTSTART;VALUE=DATE-TIME:19980101T050000Z` but can work with `DTSTART;VALUE=:19980101T050000Z`?

**Comment by cedricpim** [comment]
Currently is working with: `DTSTART;TZID=Europe/Bratislava:20160621T190000` for example.

**Comment by geier** [comment]
Sadly, we have no control over this with khal, as this is handled by [icalendar](https://github.com/collective/icalendar). You can file an issue over there (and will probably meet me there again), but as this is, as far as I see it, valid under RFC5545 (even though most libraries seem to omit it, as it is optional) this behavior will probably not be changed. Even if it will be considered, do not expect a quick fix, most issues take quite some time to resolve there.

I would suggest filing an issue at radicale and see what they have to say.

**Comment by cedricpim** [comment]
I believe this is an issue at the python library level (at least, from my research).

I was just wondering if there would be any workaround here, but you are right 👍 
Closing this, thanks for the fast reply.
