### ISSUE TITLE
Use week day names in agenda

### ISSUE THREAD

**Issue by theOtherNuvanda** [pimutils/khal#553]
Currently the agenda will only use “today” and “tomorrow”, before switching to dates. It would be more readable, if the names of days would be used instead of dates, for the next week.

**Comment by geier** [comment]
Fully agree.

Note to self: when fixing this, also have a look at the defaults for agenda_event_format and event_format.

**Comment by nim65s** [comment]
you can workaround this by setting `longdatformat = %A […]` :)

**Comment by geier** [comment]
this should be fixed with 1bc1b4df48aaba2df9eda57867fd9eac01e95d83
