### ISSUE TITLE
Cannot find timezone `None` in .ics file

### ISSUE THREAD

**Issue by Brixy** [pimutils/khal#554]
Not sure, whether this issue is redundant:

```
khal import file.ics
```

causes this error when a local time, e. g. `DTSTART:20170120T190000`, is used.

```
Cannot find timezone `None` in .ics file, this could be a bug, please report this issue at http://github.com/pimutils/khal/.
```

`local_timezone` and `default_timezone` are set in my config file.

Thank you very much

**Comment by geier** [comment]
Thank you for reporting this. This is a bug I'll try to fix ASAP.

**Comment by geier** [comment]
Just to clarify: the warning is the bug, nothing malicious is happening to your data.

**Comment by Brixy** [comment]
Yes, it’s just the error message. The the import work properly.

Thanks
