### ISSUE TITLE
pytests fails because ~/.config/khal/config exists

### ISSUE THREAD

**Issue by quite** [pimutils/khal#565]
I'm getting this assert failure because my ~/.config/khal/config exists. Is this intentional? I would assume that the tests can be run as a normal user, but perhaps not. Came across this when trying to install latest version from AUR using pacaur... 
```
runner = <tests.cli_test.CustomCliRunner object at 0x7fa44aeb2fd0>

    def test_configure_command(runner):
        runner_factory = runner
        runner = runner()
        runner.config_file.remove()
    
        result = runner.invoke(main_khal, ['configure'], input=choices())
>       assert 'Successfully wrote configuration to {}'.format(runner.config_file) in result.output
E       assert 'Successfully wrote configuration to /tmp/pytest-of-quite/pytest-8/test_configure_command0/.config/khal/config' in 'critical: Found an existing config file at /home/quite/.khal/khal.conf.\ncritical: If you want to create a new configuration file, please remove the old one first. Exiting.\n
'```

**Comment by hobarrera** [comment]
I'm one of the khal maintainers for the AUR package, and can't honesly reproduce this. There doesn't seem to by any attempt to write to `~/.khal` (I created it as a directory, so any attempts to write under it would fail).

Note that it seems that `/home/quite/.khal/khal.conf` is conflicting, not your actual config file too.

Just to know exactly where to look: is this `khal`, or `khal-git`?

**Comment by quite** [comment]
We don't need to involve AUR at all. I was getting the above error when
running pytest from a freshly cloned pimutils/khal. You're right of course
that my config was in ~/.khal/ and nowhere else. Migrating the config and db
to XDG style now made pytest run fine. The tests were not happy with old
style config, even though khal ran just fine.

**Comment by geier** [comment]
I'll "fix" this bug by deprecating every config file but xdg_home/khal/config (and perhaps *one* alternative provided by an environment varibale).

**Comment by hobarrera** [comment]
FWIW, it might also help to invalidate set `XDG_CONFIG_HOME` to a temporary directory when running config-related tests to avoid leaking and reads completely as well.

See [this test](https://github.com/pimutils/todoman/blob/4138fc6ba6a73926aebba8a8d8c39ebfa1aa7fca/tests/test_config.py#L31-L41) from todoman as a an example.

**Comment by geier** [comment]
I believe we are doing that, but the problem here was the hardcoded
path ~/.khal/khal.conf, wasn't it?

Quoting Hugo Osvaldo Barrera (2017-02-18 15:31:19)
