### ISSUE TITLE
khal new $DATE $TIMDELTA creates events that are one day to long

### ISSUE THREAD

**Issue by geier** [pimutils/khal#568]
Adding what I thought was going to be a 3 day event:

      khal new -a test 2017/03/10 3d Visit

produces a 4 day event:

    BEGIN:VCALENDAR
    VERSION:2.0
    BEGIN:VEVENT
    SUMMARY:Visit
    DTSTART;VALUE=DATE:20170310
    DTEND;VALUE=DATE:20170314
    DTSTAMP;VALUE=DATE-TIME:20170206T144724Z
    UID:4UL8DT8GO43ZLZHTQRXJ7U4E2WV9MUEP59MP
    END:VEVENT
    END:VCALENDAR

(note: DTEND is exclusive for allday events)

**Comment by untitaker** [comment]
OTOH if I create an event with `3h`, it is only 3 hours long.

**Comment by geier** [comment]
only all day events are affected.

Quoting Markus Unterwaditzer (2017-02-08 14:49:09)

**Comment by geier** [comment]
fixed with dc7797ed696bef4476e3a7557a049367f9d83754
