### ISSUE TITLE
Zsh completion doesn't match cli of khal in 0.9.1

### ISSUE THREAD

**Issue by lucc** [pimutils/khal#571]
The update of the zsh completion file was only done in c5754e49df021e7a1b4f385cffaa87ccd42a0ea9. The commit message also contains a note that there is more to be done.

I would be glad to help to fix the zsh completion if you tell me what needs to be done. Also I want to ask if you can release 0.9.2 with the updated completion (my distro currently ships 0.9.1 and it is annoying that the completion doesn't match the cli (I know I can run from git ...))

**Comment by geier** [comment]
hey lucc, 0.9.2 is released. Sadly, I can't really remember what needs to be fixed. If you want to help, either look through the various commands `--help` texts or just use the completion and see if it's missing anything.

**Comment by geier** [comment]
To me, it looks like it's working well enough, please open a new issue if you notice any deviations.
