### ISSUE TITLE
[PSA] new version released 0.9.2

### ISSUE THREAD

**Issue by geier** [pimutils/khal#572]
@pimutils/packaging 

I've made a new release fixing two important bugs, if you have already packaged 0.9.x, it would be great if you could update the packages as soon as possible.

New release is on [PyPI](https://pypi.python.org/pypi/khal/) and [khal's hompage](http://lostpackets.de/khal/news/khal092.html), read the docs has some [build issues](https://readthedocs.org/projects/khal/builds/5019825/) and only when I'm home I'll be able to tag and sign the release on github.

Unrelated question: is there a way to auto-close an issue at a specific time?

**Comment by hobarrera** [comment]
> Unrelated question: is there a way to auto-close an issue at a specific time?

No, but I'd definitely love to see a "remind me in X time" bot for github.

**Comment by fpytloun** [comment]
Hello, thank you for notification.
I have prepared update of Debian package but I hit issue with man page
during packaging of 0.9.2 which will probably be noticed by maintainers
for other distros as well:

https://github.com/pimutils/khal/issues/598

It's more a warning than error but it didn't happen in earlier releases
and I didn't find a way how to fix it nicely with Sphinx :-/

Filip

**Comment by geier** [comment]
Sorry for the unfortunate timing, but I released 0.9.3 only minutes ago. I hope this isn't too much work for you. I saw the issue, I'll respond there.
