### ISSUE TITLE
show more events in calendar and agenda

### ISSUE THREAD

**Issue by rohieb** [pimutils/khal#582]
There are times when I only have one or two events a week, so I only use khal very infrequently. Nevertheless, I'd like to be reminded about future events, even when they're far away, so I don't miss them :-) Also, navigating around the agenda is very cumbersome, you have to give multiple `agenda <date>` to see all of them, because normally, the `calendar` and `agenda` views show very few events, mostly only for "today" and "tomorrow". Instead, they could show the next _n_ events in the future, and choose _n_ to be a number that fills the height of the calendar in `calendar` view, or around ~10 (a configurable number maybe?) in `agenda` view.

**Comment by hobarrera** [comment]
Maybe the setting `timedelta` can help you? It basically controls how far into the future you want to see events by default (it's the amount of days, rather than the amount of events). I do feel that there's some overlap between both options.

```
[default]
timedelta = 8 days
```

**Comment by rohieb** [comment]
Oh, great :) I must have overread that in the [docs](https://lostpackets.de/khal/configure.html), probably because the description is very technical:

```
 timedelta
    Default timedelta to use for reporting, for example in list
```

**Comment by geier** [comment]
@rohieb: you might want to check if you find the current version clearer, if not, we are open to suggestions ;-)
Should appear any minute at read the docs: 
https://khal.readthedocs.io/en/latest/configure.html#the-default-section

**Comment by rohieb** [comment]
*hrm* let me just update my khal, the version in Debian does not support `timedelta` yet… Yes, that looks good! I guess that's all I wanted, and I can live with `timedelta = 8d` :smiley:

I could have been a bit more clearer regarding the documentation. I would think of something like this:
```
timedelta
    Default time interval to use for showing future events, like in `khal calendar` or `khal list`
```

**Comment by geier** [comment]
Thanks, updated.

Also we wanted to close this with #584, but I guess `closes` doesn't work on github.

**Comment by hobarrera** [comment]
Actually, it should:

https://help.github.com/articles/closing-issues-via-commit-messages/

I think it's because you merged manually and closed the PR (the `closes XXX` was on the PR, not on a commit).

**Comment by geier** [comment]
Quoting Hugo Osvaldo Barrera (2017-02-24 15:11:32)
> Actually, it should:
> 
> https://help.github.com/articles/closing-issues-via-commit-messages/
> 
> I think it's because you merged manually and closed the PR (the `closes XXX` was on the PR, not on a commit).

oh, I see. Thanks for clarification.
