### ISSUE TITLE
Going back with the h key doesn't work when you're in the right column and the day is empty in the interactive mode

### ISSUE THREAD

**Issue by Hund** [pimutils/khal#592]
When I'm using Khal 0.9.2 and in the interactive mode and enters a empty day, I can only go back using the `h` if I have selected a event. If the day is empty I can only go back using the left arrow key. The `h` should work no matter what you've currently selected.

**Comment by geier** [comment]
you are using the non-dynamical version, right?

Quoting Hund (2017-02-21 17:54:06)

**Comment by Hund** [comment]
Yes. I tried enabling it now and it work as intended then.
