### ISSUE TITLE
Agenda is not updated when ikhal runs for more then one day

### ISSUE THREAD

**Issue by lmoellendorf** [pimutils/khal#613]
It still states that the given date is "x days from now" with "now" being the day when ikhal has been started. E.g. today on Saturday March 25th it shows:

    Samstag, Sa 25.03.2017 (2 days from now)

Which was correct two days ago when I re-launched ikhal the last time.

**Comment by geier** [comment]
Which version of khal are you running? 

Am 25. März 2017 23:48:05 MEZ schrieb "Lars Möllendorf" <notifications@github.com>:
>It still states that the given date is "x days from now" with "now"
>being the day when ikhal has been started. E.g. today on Saturday March
>25th it shows:
>
>    Samstag, Sa 25.03.2017 (2 days from now)
>
>Which was correct two days ago when I re-launched ikhal the last time.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/issues/613

-- 
Sent from my phone. Please excuse my brevity.

**Comment by lmoellendorf** [comment]
It was 0.9.0. But I just updated to 0.9.3 and will report if this is still an issue. Sorry, I should have done this before reporting.

**Comment by geier** [comment]
no worries, as I believe I have taken care of this in 0.9.2 I'll close this, if it's still an issue, please reopen this or a new issue.
