### ISSUE TITLE
ikhal day selection is invalid after event date is modified

### ISSUE THREAD

**Issue by pfertyk** [pimutils/khal#622]
I'm using python3.5 and khal 0.9.4. I created some events, all for the same day (2017-04-05): 
![khal-events](https://cloud.githubusercontent.com/assets/11876747/24705171/0889905c-1a0b-11e7-83ed-379057cd4a5b.png)
Next I used ikhal to modify one of the events (`event 3`). I changed the start and end date to 2017-04-06 and clicked Save. This is the result:
![ikhal-invalid-day-selected](https://cloud.githubusercontent.com/assets/11876747/24705176/0aecff5a-1a0b-11e7-8183-b3ddfd40bbea.png)
The problem is that the side panel shows events from April 6th, but the currently selected day is still April 5th.

**Comment by geier** [comment]
Thank you for reporting this, I'll try to fix this ASAP.

**Comment by geier** [comment]
What would you expect to be in focus? The date that was in focus before you started editing or the event's new start date?

**Comment by pfertyk** [comment]
I think that focusing on event's new date would be a better solution. But the bigger problem here is inconsistency. The side panel shows events from a date that is not selected. If you want to keep the old date in focus, that's OK too, as long as the side panel shows events from that date.

**Comment by geier** [comment]
Should be fixed in master.
