### ISSUE TITLE
Test failure on 0.9.5

### ISSUE THREAD

**Issue by polyzen** [pimutils/khal#624]
`tests/khalendar_test.py:342: AssertionError` appears to be back(#574) in 0.9.5.

https://ptpb.pw/hDGa

**Comment by geier** [comment]
Filesystems and caching are fun :crying_cat_face: Perhaps we really should just mock those syscalls.

**Comment by polyzen** [comment]
Figured I'd try to build 0.9.5 again, and the error didn't show up. 🙏

**Comment by cedricpim** [comment]
@geier while working on having my setup in ansible and testing it on a VM, I was able to reproduce the errors above consistently with:

- git clone https://github.com/cedricpim/archlinux-pacaur
- cd archlinux-pacaur
- vagrant up
- vagrant provision
- vagrant ssh
- pacaur -S khal

It almost always fails on `tests/cal_display_test.py`.

I understand if they are not worth the trouble fixing, I can always edit the `PKGBUILD`. 
Unfortunately, it means the installation can't be automated.

**Comment by geier** [comment]
No, if this is an error that keeps coming up, we need to take care of it. Getting used to failing tests is as bad as not having them in the first place.
