### ISSUE TITLE
Pass unknown arguments to default command

### ISSUE THREAD

**Issue by madduck** [pimutils/khal#625]
I have `khal` invoke `khal calendar` if no subcommand is specified. Unfortunately, `khal monday` or `khal 2017-05-07` yields "no such command: monday" etc.. Would it be possible to alter the error handler to make it try invoking the default command with the given list of arguments, i.e. `khal calendar monday` in this case?

**Comment by madduck** [comment]
This seems related to #583. The problem is that if I alias `k=khal list`, then I have to remember to type `khal new` instead of `k new`.

**Comment by geier** [comment]
I'll have a look if something like this will be possible when time permits.

**Comment by hobarrera** [comment]
TBH, click should support a default command instead of us having to call one.

**Comment by untitaker** [comment]
This is not possible without basically guessing which options belong to the group and which ones to the default command. If there is any overlap, the entire command line becomes ambiguous.

**Comment by geier** [comment]
we are going to remove the default command altogether, see #648. Old behavior can be emulated with a shell alias.
