### ISSUE TITLE
White text on bright yellow background in interactive mode

### ISSUE THREAD

**Issue by mortie** [pimutils/khal#633]
The selected day in interactive mode is highlighted by having white text with a yellow background, like so: ![scr-3029579](https://cloud.githubusercontent.com/assets/3728194/25333148/7c2bc678-28e9-11e7-91e0-9a6ef83cfff9.png)

With many color schemes, this will probably look okay, but with others, like mine, the contrast is way too low. I don't think khal should assume that white text on a bright yellow background will be readable.

**Comment by kflak** [comment]
I have the same issue, it is very close to impossible to read the highlighted text...

**Comment by geier** [comment]
Should be fixed with 7b44b59, further refinement should be easier after #705

**Comment by rslindee** [comment]
As of v0.9.10, the old "white text on bright-yellow background" is still the color scheme for date selected. Is there a way to override/modify this without changing the colors.py located in my /usr/lib/.../khal/ui directory?

**Comment by rslindee** [comment]
As of v0.9.10, the colors appear to still be unreadable "white on yellow background" for "date selected". Is there any way to override/modify this without having to change /usr/lib/.../khal/ui/colors.py?

Or, a simple hotfix in the next release would certainly work.

**Comment by geier** [comment]
can you send a screenshot of how it looks on your machine?

**Comment by rslindee** [comment]
![screenshot-2019-04-01-21:24:46](https://user-images.githubusercontent.com/3173046/55376348-db3c5c00-54c4-11e9-956a-545453a56b1f.png)

This is with st term with what I understand to be no color/theme modifications.

**Comment by geier** [comment]
With the merging of https://github.com/pimutils/khal/pull/1279 this can now be fixed in your config file. The how should be [documented](https://khal.readthedocs.io/en/master/configure.html#the-palette-section).  You probably want to override     `date header`, `date header focused` and `date header selected`. If you find something that works well for you and also improves the default theme, please send a PR.
