### ISSUE TITLE
[Question] Performance of `khal list`

### ISSUE THREAD

**Issue by samdmarshall** [pimutils/khal#638]
Hi, so i've been trying to integrate using `khal` into my terminal prompt to give myself a heads-up about upcoming events and such. I've already implemented a similar behavior with `notmuch` for when i have new email waiting for me. Major difference is in execution time, which, is not unexpected as `notmuch` is written in C, and `khal` is written in Python. Given that, I was wondering if there was anything that could be done around there performance around getting the number of upcoming events. Right now I'm measuring it at about 1/3 to 2/5 of a second to return the data, if I can get that fast it would be much appreciated.

Thanks.

**Comment by hobarrera** [comment]
Actually, the issue it not because of python itself: it's the entry point that setuptools generates.

Maybe we could adapt https://github.com/pimutils/todoman/pull/88/files to khal, which trimmed off quite a bit for todoman.

**Comment by samdmarshall** [comment]
My only hesitation behind the patch you linked to is that Python 2 uses `python` by default, whereas `python3` does not, and would not be feasible to patch these things on many systems, otherwise this sounds great.

**Comment by hobarrera** [comment]
The script is mainly targetted towards packagers, so they can patch it accordingly (including weird python paths, etc).

Another optimization I've done locally (I think this is worth documenting), is running `khal > /dev/null` right after `vdirsyncer sync`. This makes sure the cache is up to date after syncs, and reduces startup time.

**Comment by samdmarshall** [comment]
My khal config is set to use `interactive` by default, is there a particular command that you are running to update the cache?

**Comment by hobarrera** [comment]
`khal list` should update the cache.

**Comment by samdmarshall** [comment]
Hmmm, I dunno if i'm missing something about this then. I have a background task that runs every 15 minutes that invokes `vdirsyncer sync` so that my calendars and todo lists get updated automatically. When I run `khal` after an update i'm not noticing any measurable difference between invocations (before and after the cache is updated). Both `khal` and `todo` take approximately a third of a second to run regardless, so i'm not sure if there is a measurable perf change in the patch you linked to.

**Comment by hobarrera** [comment]
That might depend a bit on your scenario. One of my devices/servers (not sure which) tend to "touch" lots of events, so during every `sync`, about half of them are needlessly updated, making the cache invalid.

**Comment by geier** [comment]
Can you [perhaps generate a profile](https://github.com/pimutils/khal/issues/172#issuecomment-78962657) so we can actually see what actually uses up the CPU time?

**Comment by samdmarshall** [comment]
When running `python3 -mcProfile -o khal.profile /usr/local/Cellar/khal/0.9.5/bin/khal list` i get the following error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cProfile.py", line 160, in <module>
    main()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cProfile.py", line 153, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cProfile.py", line 20, in runctx
    filename, sort)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/profile.py", line 64, in runctx
    prof.runctx(statement, globals, locals)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "/usr/local/Cellar/khal/0.9.5/bin/khal", line 11, in <module>
    load_entry_point('khal==0.9.5', 'console_scripts', 'khal')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 553, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 427, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'khal==0.9.5' distribution was not found and is required by the application
```

**Comment by geier** [comment]
Does ```python3  /usr/local/Cellar/khal/0.9.5/bin/khal list``` work?

**Comment by samdmarshall** [comment]
no it doesn't seem to (same error message), I have it installed through homebrew because that is the package manager on my system that i regularly interface with. I know it is available via pip but i rarely use pip so it doesn't make much sense to split the usage of package and dependency management across all the software i use.

**Comment by geier** [comment]
I don't package managers of languages I'm not familiar with either.
With 0.3s you might just have hit the python and khal being slow mark anyway. An ugly workaround I did for something similar was running a command via cron, piping it's output into a file and then reading that from the shell prompt (or in my case i3bar).

**Comment by samdmarshall** [comment]
the current solution i have is that i wrote a small utility that runs a bunch of commands for my shell in parallel so it only takes as long as the longest command to execute. Still not ideal, but better than the alternatives i have for right now.
