### ISSUE TITLE
khal shows a question mark after calendar entries

### ISSUE THREAD

**Issue by andreas-bulling** [pimutils/khal#640]
Hi,

for some reason, khal is showing a question mark after most of the calendar events although (if I look at these events in MacOS's calendar application) I did not add any. I also noticed that German Umlaute (non-ascii) are not shown properly in khal although utf-8 otherwise works fine in the same console (iterm2) and the Umlaute are shown properly in MacOS's Calendar. Maybe related?

**Comment by geier** [comment]
The font you are using is probably missing some symbols used by khal.
Those question marks should probably by arrow-circles.
You can replace them by ascii symbols with setting `[locale]
unicode_symbols = False` in the configuration file.

Quoting andreas-bulling (2017-05-02 15:15:48)

**Comment by andreas-bulling** [comment]
Thanks a lot for your quick reply. With this option it now shows a "R" behind these entries...

Which font are we supposed to use that fully supports the symbols used by khal? As I said, otherwise I don't have any problem with UTF-8 support in my terminal...

**Comment by geier** [comment]
The R or circle is supposed to indicate that this is a repeating event,
the circle symbol is U+27F3 'CLOCKWISE GAPPED CIRLE'.
I expected it to be one of the more common non-ascii symbols, but to my
surprise I just realized it isn't the font I'm using either, so it must
be some kind of fallback font, perhaps Symbola
(http://users.teilar.gr/~g1951d/).

We really should add this to the FAQ.

Quoting andreas-bulling (2017-05-02 15:34:19)

**Comment by andreas-bulling** [comment]
ok... Well, what about simply showing the "R" in brackets behind the title (i.e. "$title (R)") instead of this fancy (and apparently difficult to properly support) symbol?

**Comment by hobarrera** [comment]
> Which font are we supposed to use that fully supports the symbols used by khal? As I said, otherwise I don't have any problem with UTF-8 support in my terminal.

What's the output of `echo ⟳'  (you can retype this on gtk apps with ctrl+shift+u27f3)? It seems you do have problems, since this is plain utf-8.

**Comment by geier** [comment]
I'm open to replace `R` by `(R)` for the no-fancy symbols setting, but I'm actually quite fond of the unicode symbols.

**Comment by andreas-bulling** [comment]
@hobarrera I am on MacOSX/iterm. If you let me know what I have to type there I am happy to test. As I said before, I didn't notice any problems with UTF-8 so far in any other software.

**Comment by hobarrera** [comment]
Can you copy-paste the above character? I've no idea about macOS/OS X/iterm.

You're saying you've no issues with Unicode, but this bug report seems tonne about your terminal not properly supporting Unicode on some level.

**Comment by andreas-bulling** [comment]
I copied and pasted and it shows properly in my terminal

**Comment by hobarrera** [comment]
Huh, that's odd/curious. What's the output of each of these commands:

    python -c "print('⟳')"
    python -c "print('\u27f3')"
    printf "⟳\n"

**Comment by andreas-bulling** [comment]
The first and third return the desired symbol, the second returns `\u27f3`. (Python 2.7.13, system default).

With python 3.6 all three return the desired symbol, i.e. seems to be a Python (version) problem.

**Comment by geier** [comment]
The way we wall this in python is this `python -c "print('\N{Clockwise gapped circle arrow}')"`, please try that as well.

Also, which version of khal and python are you using?

**Comment by andreas-bulling** [comment]
python 2.7.13: \N{Clockwise gapped circle arrow}
python 3.6.1: the desired symbol

khal: 0.9.5

**Comment by uqam-fob** [comment]
Hi,

I find the unicode's cool, but, when disabled, the "R" can easily be confused with
the summary. I second the change for a spaced version or, better IMHO, a "(R)"
version as, in my case, it is really a font issue and I like mine too much to use another.

khal's pretty nice, btw :)

**Comment by hobarrera** [comment]
What confuses me is that no-one has managed to reproduce the problem by simply running `print` on python3 (even though they see the problem in khal), so it's unclear if it's a python problem or a khal one.

For those who see the issue, can you make sure you're not somehow running khal with python2 (python2 is unsupported, and `setup.py` shouldn't let you install it with python2, but just in case).

**Comment by uqam-fob** [comment]
Well, in my case issuing `python3 -c "print('\N{Clockwise gapped circle arrow}')"` prints an empty box since it is not implemented. I use Inconsolata. Also, khal is definitely running with python3 on my side.

**Comment by hobarrera** [comment]
@uqam-fob So, it sound to me like the font is missing the glyphs, and there's no fallback font configured? Maybe your terminal supports having a fallback font (eg: like urxvt, termite).

**Comment by uqam-fob** [comment]
@hobarrera You are correct, there is no fallback font.

Just to make sure that the focus is on the right thing, I added `unicode_symbols = False` in my configuration and I, too, think the "R", for recursive events, could be separated from the summary to increase readability.

**Comment by uqam-fob** [comment]
Well, I just re-read my comment in the context of the issue and created #657.

As for the issue at hand, I would consider it is installation- or font-related. I can't think of any sane way to protect against the latter. For the first, maybe @andreas-bulling can tell how he managed to install/use khal with python2.

**Comment by andreas-bulling** [comment]
I simply installed it using homebrew

**Comment by andreas-bulling** [comment]
I just checked `/usr/local/Cellar/khal/0.9.5/bin/khal`:
The first line reads `#!/usr/local/Cellar/khal/0.9.5/libexec/bin/python3.6`, i.e. khal does seem to be run with python3 as it should be. Still the symbol is not shown properly.

**Comment by hobarrera** [comment]
@andreas-bulling Can you confirm that that is the `khal` being used running `which khal`.

**Comment by andreas-bulling** [comment]
```
$ which khal
/usr/local/bin/khal
$ ls -la /usr/local/bin/khal
lrwxr-xr-x  1 user  admin  29 29 Apr 13:22 /usr/local/bin/khal -> ../Cellar/khal/0.9.5/bin/khal
```

**Comment by geier** [comment]
Is there a way to contact the homebrew maintainer of khal? Perhaps they have an idea of what's going on. Or, as a last resort, open an issue at homebrew? I'm already put off by their strange nomenclature though, and [this](https://github.com/Homebrew/homebrew-core/blob/master/Formula/khal.rb) doesn't seem to list a maintainer.

**Comment by geier** [comment]
possibly related urwid bug: https://github.com/urwid/urwid/issues/286

**Comment by geier** [comment]
As I now have frequent access to a Mac I can confirm that this is indeed a case of urwid/urwid#286.

**Comment by geier** [comment]
As discussed in urwid/urwid#286, this is an issue of wrongly set locale. E.g. setting the locale to `LC_ALL=en_US.UTF-8` fixes the issue.
