### ISSUE TITLE
Fix detecting if a date contains a year

### ISSUE THREAD

**Issue by geier** [pimutils/khal#651]
We currently check if `%y` or `%Y` is in the format string, with using `%X` this will fail, see
https://github.com/pimutils/khal/blob/1fe4d6ea73abd3a8e00014f810fab45f6751bd83/khal/utils.py#L268

**Comment by hobarrera** [comment]
The intention of the linked code is to assert that the format includes the year, right?

This check seems a lot more robust:

```python
now = datetime.now()
formatted = now.strftime(short_format)
assert re.search("(?<!\d){}(?!\d)".format(now.year), formatted) is not None
```

I think this can only fail for *extremely* weird date formats combined with very specific dates, like:

* date: 2017-05-15 20:17
* format: `%H%m`

**Comment by geier** [comment]
I thought of taking a specific time, like `datetime(1997, 10, 11, 12, 13, 14)` and then check for `97` in the resulting string.

**Comment by hobarrera** [comment]
Ah, a specific hardcoded time guarrantees that, yes. I like that a lot more. 👍

**Comment by geier** [comment]
basically
```
if '97' in dt.datetime(1997, 10, 11, 12, 13, 14).strftime(dtformat):
    continue
```
now we only need some tests...

**Comment by hobarrera** [comment]
Yup, that looks good!

**Comment by geier** [comment]
we already had a test for this.
