### ISSUE TITLE
Broken design for months that have long abreviated names

### ISSUE THREAD

**Issue by nim65s** [pimutils/khal#653]
With a french locale, this is what ikhal looks like (note the blank lines for juil. and others) :  
![khal](https://cloud.githubusercontent.com/assets/131929/26066185/654bc54e-3996-11e7-816a-5cea220b23e6.png)

**Comment by geier** [comment]
It's probably broken in khal as well, or isn't it?

**Comment by nim65s** [comment]
Yep, you're right, I just had never used it: 
![khal](https://cloud.githubusercontent.com/assets/131929/26067475/b40a9b66-399a-11e7-95ea-498ea32aa1ca.png)
