### ISSUE TITLE
Doc building broken with latest sphinx

### ISSUE THREAD

**Issue by geier** [pimutils/khal#659]
I have opened [an issue at sphinxcontrib-newsfeed](https://bitbucket.org/prometheus/sphinxcontrib-newsfeed/issues/3/not-compatible-with-sphinx-161).

**Comment by hobarrera** [comment]
I debugged this for a while, found that it was `sphinx-newsfeed`, and noticed you'd already reported this upstream.

I'll leave a link here for anyone else stumbling across this:

https://bitbucket.org/prometheus/sphinxcontrib-newsfeed/issues/3/not-compatible-with-sphinx-161

**Comment by geier** [comment]
sorry for the quiet editing and wasting your time.

**Comment by geier** [comment]
Will be fixed with sphinx, 1.6.2, see https://github.com/sphinx-doc/sphinx/issues/3796#issuecomment-303743067

**Comment by hobarrera** [comment]
No problem, I should reload tabs after they're open 15hours before starting to read them anyway. 😆

**Comment by geier** [comment]
fixed.
