### ISSUE TITLE
Exception when attempting to unpack values in event

### ISSUE THREAD

**Issue by samdmarshall** [pimutils/khal#661]
Safer handling of unpacking values from icalendar events. I think this falls under the third party compatibility label, but generally i think it would be better to add some safer code handling here to split on the first `=` encountered rather than on all.

```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/local/Cellar/khal/0.9.5/libexec/lib/python3.6/site-packages/icalendar/parser.py", line 230, in from_ical
    key, val = q_split(param, '=')
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/khal/0.9.5/libexec/lib/python3.6/site-packages/icalendar/parser.py", line 336, in parts
    strict=self.strict)
  File "/usr/local/Cellar/khal/0.9.5/libexec/lib/python3.6/site-packages/icalendar/parser.py", line 255, in from_ical
    % (param, exc))
ValueError: 'X-ABCROP-RECTANGLE=ABClipRect_1&96&370&928&928&YlR0U0hEDiJnRSmsJhYg6Q==' is not a valid parameter string: too many values to unpack (expected 2)
```

**Comment by geier** [comment]
That can't be done in khal since the icalendar library just fails to parse, we could only present a nicer error message.

 However I fixed this specific bug and the fix has been included in the latest icalendar release, so you might be able to upgrade.

**Comment by samdmarshall** [comment]
is that a requirement defined by khal? I believe I am only installing packages that are listed as satisfying the requirements of `khal`will get installed, so perhaps this can be made as a dependency change in the next update?

**Comment by hobarrera** [comment]
Can you confirm which version of `icalendar` you're running? You can determine this by running:

    python -c "import icalendar; print(icalendar.__version__)"

**Comment by geier** [comment]
Yes, that is a requirement by khal, it is listed as a dependency and you
have it already installed, otherwise khal wouldn't work at all.

Depending on how you installed khal (and with that icalendar) you might
be able to upgrade to a newer version of icalendar.

Quoting Samantha Marshall (2017-06-08 18:57:28)

**Comment by geier** [comment]
Perhaps a reinstall of khal would get the latest version of
icalendar from PyPI? (I have no experience with homebrew.)

Quoting Samantha Marshall (2017-06-08 19:27:44)

**Comment by samdmarshall** [comment]
Yeah; looks like due to the release dates of 3.11.4 coming after the release of 0.9.5 there isn't a clean way to update it atm; but based on what i know of brew this should be automatically packaged in as part of their pre-compiled installations (default method of install) in the next khal release. I am going to close this out now as there isn't anything this project has to do to resolve it. Thanks!

**Comment by geier** [comment]
You are welcome. You might want to notifier the packagers, perhaps they can do something like changing the version number to 0.9.5-1, if upgrading khal also makes homebrew upgrade all dependencies that might fix the issue for everybody else.
