### ISSUE TITLE
usability improvement: put month name on the first row where the first day is in the month

### ISSUE THREAD

**Issue by pdav** [pimutils/khal#685]
In the calendar view (left panel), the month name is on located on the first row where a day of the month appears. Example for Jun 2017:

         Mo Tu We Th Fr Sa Su
          ....
    Jun  29 30 31  1  2  3  4
          5  6  7  8  9 10 11
          ....

Instead, it should be located on the first row where the first day (either monday or sunday or another day, depending upon the `firstweekday` configuration item) is inside the new month. Example:

         Mo Tu We Th Fr Sa Su
          ....
         29 30 31  1  2  3  4
    Jun   5  6  7  8  9 10 11
          ....

This would be a great readability improvement.

**Comment by geier** [comment]
Personally I prefer the way it is now, but if many people agree with your suggestion I'm open to have it changed.

**Comment by pdav** [comment]
May I suggest to make a configuration option?

 Example:
    month_display = first_day | plain_week

**Comment by geier** [comment]
While I generally dislike the amount of configurability we already have,
as this one doesn't affect function and is easy to test, it probably is
a good option to make it configurable.


Quoting Pierre DAVID (2017-07-19 16:26:37)

**Comment by geier** [comment]
this was closed by #686
