### ISSUE TITLE
Better documentation for date(time)formats in new

### ISSUE THREAD

**Issue by Llewxamris** [pimutils/khal#694]
Tried to add a new event using kahl:
`khal new -a work 26.08. Great Event -g meeting -r weekly`

Recieved this crash dump:

> Traceback (most recent call last):
>   File "/usr/bin/khal", line 11, in <module>
>     sys.exit(main_khal())
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/khal/cli.py", line 396, in new
>     format=format,
>   File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 339, in new_from_string
>     info = utils.eventinfofstr(info, conf['locale'], adjust_reasonably=True, localize=False)
>   File "/usr/lib/python3.6/site-packages/khal/utils.py", line 521, in eventinfofstr
>     raise ValueError('Could not parse `{}`'.format(info_string))
> ValueError: Could not parse `26.08. Great Event

Ran on khal 0.9.6. Installed via pip. ikahl does not throw any errors making this event.

**Comment by geier** [comment]
Please make sure that 26.08. fits your configured dateformat. Also the error message is could be improved.

**Comment by Llewxamris** [comment]
You are correct, that wasn't my dateformat. However, switching it too `08.26.` or `2017.08.12.` still results in the crash.

**Comment by geier** [comment]
could you show us the [locale] part of your config file and/or the output of `khal printformats`?

**Comment by Llewxamris** [comment]
Certainly.
`khal printformats`

> longdatetimeformat: 2013-12-21 10:09
> datetimeformat: 2013-12-21 10:09
> longdateformat: 2013-12-21
> dateformat: 2013-12-21
> timeformat: 10:09

`~/.config/khal/config`
> [locale]
> timeformat = %H:%M
> dateformat = %Y-%m-%d
> longdateformat = %Y-%m-%d
> datetimeformat = %Y-%m-%d %H:%M
> longdatetimeformat = %Y-%m-%d %H:%M

**Comment by geier** [comment]
You'll need to either use the format specified in the config file, e.g., 2017-08-12 or change the formats in the config file, e.g. to %Y.%m.%d.

**Comment by geier** [comment]
Also, on master the error messages should be somewhat nicer.

**Comment by Llewxamris** [comment]
Ah, that does it. Thanks for your help. I assumed the dot notation was the standard when entering via CLI. I can't grab master atm, but when I have time I can grab master and give feedback as to if the error message is improved.

**Comment by geier** [comment]
This probably means that the documentation needs to be improved.

**Comment by Llewxamris** [comment]
Reading through the documentation again, I feel that the explanation for `khal new` in `usage.rst` does explain that you should use the dateformat specified inside the configuration file. Maybe add some sort of reminder in the *examples* section that the user should format the START and/or the END param to match their dateformat? That on top of the improved error message should prevent most confusion.

**Comment by chetnuy** [comment]
Please, add dataformat for your example in manual:
"khal new -a work 26.07. Great Event -g meeting -r weekly" == for current format(d-y**etc).
It's really trouble.
