### ISSUE TITLE
Remove default 'new event' title for new events (ikhal) or make it configurable

### ISSUE THREAD

**Issue by pfertyk** [pimutils/khal#695]
I'm using khal 0.9.6. When I open ikhal and type `n` (new event) I get the default event title `new event`. I almost never want to create an event with such a title, so every time I have to remove it. I'm pretty sure that previous versions of khal used an empty title by default.

Can this default `new event` value be removed? If not, could we make it configurable (`default_new_event_title: ''`)?

**Comment by geier** [comment]
You are right, nobody wants to add an event called "New event", this is mainly there to make sure users understand where to edit the title of the event. Highlighting of editable text fields would make this clear and is on my todo list. The `new event` will be removed then.

**Comment by pfertyk** [comment]
I already started working on making this configurable, shall I stop? :)

**Comment by geier** [comment]
If you have the time and motivation, I believe it is better spend at making all editable text fields in the editor stand out like the start and end date/time.

**Comment by pfertyk** [comment]
Sounds good. Can we leave this open until the job is done?

**Comment by geier** [comment]
Sure.

**Comment by pfertyk** [comment]
Is there a task for this (making all editable fields stand out) already?

**Comment by geier** [comment]
No, not yet.

Quoting pfertyk (2017-08-03 15:03:59)

**Comment by geier** [comment]
@pfertyk some pointers:
ikhal makes use of the [urwid](http://urwid.org) toolkit.
Styling of element works by assigning [display attributes](http://urwid.org/manual/displayattributes.html), which you can than style via the matching palette entries.

For the editable text widget you will probbaly need to wrap them in `urwid.AttrWrap`s and make sure that if they are accessed later, an `.original_widget.` is added.

Example:
```self.summary = urwid.AttrMap(ExtendedEdit(caption='Title: ', edit_text=event.summary), 'editbg', 'editfg')```
and than change `self.summary.get_edit_text()` to `self.summary.original_widget.get_edit_text()`

The palettes are defined in khal/ui/colors.py, editbg and editfg are not defined there (yet), I just used them as examples.

Feel free to ask either here or at IRC, but I have rather long response times at the moment.

**Comment by geier** [comment]
perhaps it is also `base_widget` instead of `original_widget`.

**Comment by pfertyk** [comment]
Thanks, that will help me a lot! Any hints on how to test such improvement? Is styling of widgets even testable?

**Comment by geier** [comment]
You can call a widget's render() method, but I'm not sure it actually applies the styling. So, for the moment, no we don't test the styling. If you can come up with a way to do it, it'd be great.

**Comment by pfertyk** [comment]
I made a new branch for this task (WIP): #696 

Notes:
- I used an existing `edit` color palette, it seems to work fine but I'm not sure if it is the right one; could you confirm?
- the highlighted text fields were not aligned properly, so I added some extra spaces after field names, resulting in this:
![khal0](https://user-images.githubusercontent.com/11876747/29190257-b442c9f0-7e19-11e7-9402-fe6c5fd67120.png)
In general, this looks OK, but the `Title` field is still not aligned with other fields. One solution would be to put the calendar chooser in a separate line:
![khal1](https://user-images.githubusercontent.com/11876747/29190294-d6c68818-7e19-11e7-98bc-d77694ccb5a6.png)
That gives us a nice, aligned view, but we lose a whole line just for the calendar chooser. Do you have any suggestions what would be the best solution here?

Please note that the branch contains (at the moment) only the new styling of editor fields. Once we figure out how exactly they should look like, I will remove the default 'new event' title and the comments I left in the code.

**Comment by geier** [comment]
Using `edit` is probably fine, at the moment I can't really remember what it was supposed to do anyway. I like the second option better, but perhaps somebody else wants to weigh in.

This also shows that we probably want to add some spacing around the editor and/or restrict the length of the calendar chooser, perhaps even style the buttons. (This is not something I expect you to fix with this PR.)

**Comment by pfertyk** [comment]
I've added 2 spaces between the editor and the dates column. I've also set the constant width of 12 for all the buttons in the event editor. The results look in general quite well:
 
![buttons2](https://user-images.githubusercontent.com/11876747/29287686-9c7ddd44-8136-11e7-9a9d-ae062568fe36.png)

There is however a problem with longer calendar names:

![buttons1](https://user-images.githubusercontent.com/11876747/29287513-01c008fe-8136-11e7-8a11-3fec54b337ab.png)
![buttons0](https://user-images.githubusercontent.com/11876747/29287519-06a90262-8136-11e7-91f8-0b7b1387777e.png)

Can we leave it like that or do you have an idea how to fix this?

Also, I've set the width for all 4 event editor buttons to 12. It might be a good idea to create a constant with this value and use it in all 4 places. What do you think? Is there a file in khal's structure where such a constant can be placed?

**Comment by fpose** [comment]
Hello,

can you tell in which release the default "new event" will be removed?

**Comment by geier** [comment]
The next one. If you want this behavior NOW, you'll have to install from master.
