### ISSUE TITLE
default year should be such that event is in the future

### ISSUE THREAD

**Issue by mcrucifix** [pimutils/khal#697]
So far the default year is always the current year. Wouldn't it be more handy if khal understands by default that I mean an event in the future?   If, in December 2017, I add a new event for the 20.04. , it should understand that I mean 20.04.2018, not 2017.

**Comment by geier** [comment]
agreed!

**Comment by pfertyk** [comment]
The fix should be ready, awaiting code review.

**Comment by mcrucifix** [comment]
thank you so much for your help. This should spare me a few goofs. 

michel. 
* pfertyk <notifications@github.com> [2017-08-23 06:34:37 -0700]:

> The fix should be ready, awaiting code review.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Michel Crucifix

http://perso.uclouvain.be/michel.crucifix
http://www.uclouvain.be/teclim

Phone: + 32 10 473300
