### ISSUE TITLE
Default alarm

### ISSUE THREAD

**Issue by inducer** [pimutils/khal#698]
It would be nice if khal could default to setting an alarm, say, a configurable number of minutes before a newly-created event.

**Comment by mdosch** [comment]
I just wanted to request also a feature for configurable default alarms as I often forget to set `--alarm` and discovered there is already this request.

I would suggest to have two default alarm configurations as I would like to set it to e.g. 1h for events with a start time and 1d for full-day events.

**Comment by Brixy** [comment]
Tiny addition: A default alarm option would come in handy for `type = birthdays` as this type is `readonly`.
