### ISSUE TITLE
use notifications

### ISSUE THREAD

**Issue by teto** [pimutils/khal#718]
sometimes when saving an event, khal tries to warn me from something but the message disappears very fast so it's hard to read. Having a setting in config/hook so that I can relay these messages to freedesktop notifications could be nice.

**Comment by pdav** [comment]
Seems to be correlated with problem number 2 in #666.
Personnally, I would prefer a message displayed in the ikhal window (status bar or something related).

**Comment by WhyNotHugo** [comment]
Status bar makes sense the most and would be the easiest to implement.

An XDG notification isn't a good idea really, terminal applications relying on a specific desktop environment won't really work well (eg: other desktops, or simply no desktops, or a just fullscreen terminal, etc).

**Comment by Tonus1** [comment]
Makes sense for status bar. 

Could it be overrided in the config file to match personal likes? 

Le 5 oct. 2017 à 08:58, à 08:58, Hugo Osvaldo Barrera <notifications@github.com> a écrit:

**Comment by geier** [comment]
Yes, this is the same issue as mentioned in #666. I have this fixed for now, even though it could need some more refinement (and the whole Pane/Window structure needs a refactoring).
