### ISSUE TITLE
Timezone converts to UTC only

### ISSUE THREAD

**Issue by nolash** [pimutils/khal#733]
My system is configured for CEST:

```
$ zdump /etc/localtime 
/etc/localtime  Wed Oct 25 08:42:32 2017 CEST
```

However if I add an event using `America/New_York`, which is in the time of writing 8 hours earlier, it is saved as 6 hours later locally. Furthermore, setting `TZ` seems to make no difference:

```
$ khal new 10:00 11:00 America/New_York foo
$ TZ=Europe/Berlin; khal new 10:00 11:00 America/New_York foo
$ TZ=Europe/London; khal new 10:00 11:00 America/New_York foo
$ khal search foo
25-10-2017 16:00-25-10-2017 17:00 foo
25-10-2017 16:00-25-10-2017 17:00 foo
25-10-2017 16:00-25-10-2017 17:00 foo
```

**Comment by geier** [comment]
America/New_York is currently still on daylight saving time, so they are UTC-4, CEST is DST as well, so it is UTC+2, that makes 6 hours of difference (also see here: https://www.worldtimebuddy.com/united-states-new-york-new-york-to-cest). 

On the second issue, of setting TZ having no effect: did you set local_timezone in your configuration file? The environment variable TZ **does not override** an explicitly set timezone, but perhaps it should.

**Comment by nolash** [comment]
> but perhaps it should.

I would vote for it.

>  did you set local_timezone in your configuration file

No, as I expected my system settings to have effect.

> America/New_York is currently still on daylight saving time

Aaaaah I see ;)

At the risk of being off-topic, here's the precursor to the confusion:

I got a google event in email specifying MDT.

I "translated" this using `tzselect` (v2.26), selecting Americas -> United States of America -> Mountain (most areas). The resulting time I got from the system was -8 offset from mine. 

Selecting Europe -> Germany -> Germany (most areas) the time returned was +8 from MDT. Thus meaning it returns CEST equivalent for Germany, but no summer time correction for MDT(?)

Strange...?

**Comment by geier** [comment]
Despite what tzselect says, mountain time (MDT = Mountain Daylight Time) is not "most areas"of the USA, but more like a forth (green area in [0]), but MDT is UTC-6 during DST. 
 
New York actually is actually part of the Eastern Time Zone.

According to [1], 'America/Denver' is the tz database equivalent of Mountain Time.
                        
Sadly, the timezone database we use, does not know abbreviations like MDT, but the timezone `America/Mountain` would work instead. 

[0] https://en.wikipedia.org/wiki/Mountain_Time_Zone#/media/File:Timezoneswest.PNG
[1] https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

And please forget my question about the setting of TZ, I didn't read your comment properly and thought you had set TZ when querying khal, not creating a new event.

**Comment by nolash** [comment]
Using `America/Mountain` that and everything after it ends up part of the event title instead :/

**Comment by nolash** [comment]
(using `khal` 0.9.6 btw)

**Comment by geier** [comment]
You are right, America/Mountain does not work for me either, sorry.
America/Denver however does, could you check if that works for you?

Quoting lash (2017-10-25 10:48:51)

**Comment by geier** [comment]
My fault again, it's US/Mountain, not America/Mountain.

Quoting lash (2017-10-25 10:48:51)

**Comment by nolash** [comment]
`US/Mountain` works, and gives me the result locally that the sender intended with `MDT`. Great!

**Comment by geier** [comment]
I'll close this as I believe this is resolved, feel free to open new issues for feature requests.
