### ISSUE TITLE
day names barely align with day numbers

### ISSUE THREAD

**Issue by teto** [pimutils/khal#735]
Nothing important but the names of the days ("lu" => monday, "ma" => tuesday etc) are slightly misaligned with the motnh numbers (upper left) so it's *easy* to confound 2 following days. 

it's khal v0.9.7
![2017-11-02-151040_636x354_scrot](https://user-images.githubusercontent.com/886074/32315176-75546eb2-bfee-11e7-8a23-44c3b6e06f54.png)

**Comment by geier** [comment]
Thank you for reporting this, I believe I fixed this just now (in master), please comment or reopen if I didn't.

**Comment by teto** [comment]
will try to test soon. thanks for the quick fix.

**Comment by bepolymathe** [comment]
Hi, i always have this bug with the 0.9.8 version

**Comment by bepolymathe** [comment]
Any option to correct this ?

**Comment by geier** [comment]
Can you send a screenshot and share which version are you using?

**Comment by bepolymathe** [comment]
Hi,

Here a screenshot. 

![capture du 2018-08-04 10-52-05](https://user-images.githubusercontent.com/29939805/43674483-093ec6ae-97d5-11e8-861a-b952c9f2c088.png)

**Comment by bepolymathe** [comment]
I tried with different Khal configurations... and I had the impression that it appeared after testing the "frame = width" option... but i am not sure.

**Comment by geier** [comment]
Sorry for not getting back to you. If this is still relevant, what locale settings are you using and what operating system are you on?

**Comment by ephase** [comment]
Hi,

This issue seems to duplicate #897. This kind of problems occur with french locale because this is the only locale with 4 char for shorten month name.
