### ISSUE TITLE
Custom longdateformat breaks interactive editor

### ISSUE THREAD

**Issue by lucc** [pimutils/khal#736]
I have changed the longdateformat and this breaks the date field in the interactive editor. I can not leave it any more.

To reproduce this use the following config file:
```
[default]
  default_calendar = test
[calendars]
  [[test]]
    path = ~/tmp/khal_test
[locale]
  longdateformat = %a %F
```

**Comment by lucc** [comment]
I was in a hurry yesterday, so here is some more info:

* this happens on master (4354327824bab890bd846ca35346f179ffed1512) and on 0.9.8 installed from the aur on arch linux.
* this happens when editing existing items or creating new ones.  As soon as the cursor tries to leave the date field (for example with TAB) it turns read and I have to press ESC to cancle the editor.
* also the title of each day in the interactive interface is redundantly showing the day of week. With the changed longdateformat it looks like this:
```
Today (Tuesday, Tue 2017-11-07)
Tomorrow (Wednesday, Wed 2017-11-08)
Thursday, Thu 2017-11-09 (2 days from now)
```
whereas the default looks like this:
```
Today (Tuesday, 07.11.2017)
Tomorrow (Wednesday, 08.11.2017)
Thursday, 09.11.2017 (2 days from now)
```

**Comment by geier** [comment]
Thanks for reporting this, I'll look into this.

**Comment by geier** [comment]
The problem seems to be that python's strptime does not support `%F`, [the documentation does not mention it for strftime either](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior), but there it works.

```python
>>> import datetime as dt
>>> dt.datetime.strptime(dt.datetime.now().strftime('%F'), '%F')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-78da6c878047> in <module>()
----> 1 dt.datetime.strptime(dt.datetime.now().strftime('%F'), '%F')

/usr/lib/python3.6/_strptime.py in _strptime_datetime(cls, data_string, format)
    563     """Return a class cls instance based on the input string and the
    564     format string."""
--> 565     tt, fraction = _strptime(data_string, format)
    566     tzname, gmtoff = tt[-2:]
    567     args = tt[:6] + (fraction,)

/usr/lib/python3.6/_strptime.py in _strptime(data_string, format)
    352                 del err
    353                 raise ValueError("'%s' is a bad directive in format '%s'" %
--> 354                                     (bad_directive, format)) from None
    355             # IndexError only occurs when the format string is "%"
    356             except IndexError:

ValueError: 'F' is a bad directive in format '%F'
```

**Comment by geier** [comment]
When using `%a`, where do you want the weekday to appear?

**Comment by lucc** [comment]
I was hoping to use %a instead of the full name of the weekday but that seems to be hardcoded into the output. I can now use `%Y-%m-%d` instead of `%F` and it seems to work (the editor and the output).

In general (and related to #583) it might be nice to have a more permissive parser, especially for the `new` command. It could accept "german" dates like 10.11.2017, 10.11.17 or 10.11., "american dates" like 11/10/2017, 11/10/17 or 11/10 and "international/ISO" dates like 2017-11-10 or --11-10 and not just one date. I assume that these formats are well distinguishable, and maybe some more can be added to the list. This would make it easier to copy paste dates from websites or emails into the command line of `khal new`. 

Alternatively (but much less nice) the parser could support/read a different config option to make it possible to have a different format for input and output (I like the output to be verbose but the input to be as short as possible if it has to be *one fixed* format).

**Comment by geier** [comment]
daynames can be customized, but currently only support date, date-long and the name, adding the abbreviated date would be easy though (#738).

Regarding the second issue: agreed, the problem though is that [both dd/mm/yy and mm/dd/yy are in use](https://en.wikipedia.org/wiki/Date_format_by_country).

I'll close this one as I believe the main issue has been cleared up, feel free to open a new issue to make sure the other parts are not forgotten.
