### ISSUE TITLE
Newlines in --format argument impossible

### ISSUE THREAD

**Issue by fpose** [pimutils/khal#737]
Hi,

i am using khal 0.9.8. I try to style the printics command output with the format agument:

```
khal printics --format '{start}\n{title}' file.ics
1 events found in file.ics
2017-11-10 11:00\nMeeting
```

I can see that backslashes are escaped before the format string is used. How to put newlines in the format? Maybe a format attribute {nl} could be added?

Thanks,
Florian

**Comment by geier** [comment]
Looks like it can't be put in at the moment, a new attribute `{nl}` is probably a sensible idea.

**Comment by geier** [comment]
(it would need to be tested how well this works with ikhal).
