### ISSUE TITLE
Display ISO week date

### ISSUE THREAD

**Issue by fpose** [pimutils/khal#740]
Hello,

we are starting to use khal in our company and what we notices at the beginning was, that there is no possibility to display the ISO week date [1], which we use quite often when communicating with our customers. It would be great if the week number could be displayed (for example) as additional column between the month abbreviation and the first day-of-week. Probably this should be configurable.

- Is this already possible (via configuration) and I overlooked it?
- If not, would you accept a pull request for this?

[1] https://en.wikipedia.org/wiki/ISO_week_date

Regards,
Florian

**Comment by geier** [comment]
This should be possible: In section [locale] set "weeknumbers"  to "left" or "right".

I just noticed, that the documentation is broken there, so please don't close this issue yet, so that I am reminded to fix that later. 

Am 21. November 2017 10:07:19 MEZ schrieb Florian Pose <notifications@github.com>:
>Hello,
>
>we are starting to use khal in our company and what we notices at the
>beginning was, that there is no possibility to display the ISO week
>date [1], which we use quite often when communicating with our
>customers. It would be great if the week number could be displayed (for
>example) as additional column between the month abbreviation and the
>first day-of-week. Probably this should be configurable.
>
>- Is this already possible (via configuration) and I overlooked it?
>- If not, would you accept a pull request for this?
>
>[1] https://en.wikipedia.org/wiki/ISO_week_date
>
>Regards,
>Florian
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/issues/740

-- 
Sent from my phone. Please excuse my brevity.

**Comment by fpose** [comment]
I started to look into the code and meanwhile also discovered the weeknumbers parameter. ;-)

Perfect solution! Especially I find it a great idea to display the week numbers on the left between the month names. Thank you.

**Comment by geier** [comment]
Seems to have been an issues with building the documentation, now it seems to be documented.
