### ISSUE TITLE
Ugly error message on invalid config file [was: Struggling with a first install]

### ISSUE THREAD

**Issue by amandabee** [pimutils/khal#744]
I installed `khal` with `python3 -m pip install khal`, but when I try to run it (with `python3 -m khal`) I get the following:

> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/amanda/.local/lib/python3.5/site-packages/khal/__main__.py", line 25, in <module>
>     main_khal()
>   File "/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
>     with self.make_context(prog_name, args, **extra) as ctx:
>   File "/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line 621, in make_context
>     self.parse_args(ctx, args)
>   File "/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line 1018, in parse_args
>     rest = Command.parse_args(self, ctx, args)
>   File "/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line 880, in parse_args
>     value, args = param.handle_parse_result(ctx, opts, args)
>   File "/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line 1404, in handle_parse_result
>     self.callback, ctx, self, value)
>   File "/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line 78, in invoke_param_callback
>     return callback(ctx, param, value)
>   File "/home/amanda/.local/lib/python3.5/site-packages/khal/cli.py", line 126, in config_callback
>     prepare_context(ctx, config)
>   File "/home/amanda/.local/lib/python3.5/site-packages/khal/cli.py", line 207, in prepare_context
>     conf = get_config(config)
>   File "/home/amanda/.local/lib/python3.5/site-packages/khal/settings/settings.py", line 154, in get_config
>     config_checks(user_config, _get_color_from_vdir, _get_vdir_type)
>   File "/home/amanda/.local/lib/python3.5/site-packages/khal/settings/utils.py", line 192, in config_checks
>     if config['calendars'][calendar]['type'] == 'discover':
> TypeError: string indices must be integers

I'm not quite sure how to troubleshoot this.

**Comment by geier** [comment]
Hmm. Not really sure what this is either. Can you paste the [calendars] section of your config file? 

Am 18. Dezember 2017 22:00:54 MEZ schrieb Amanda Hickman <notifications@github.com>:
>I installed `khal` with `python3 -m pip install khal`, but when I try
>to run it (with `python3 -m khal`) I get the following:
>
>> 
>> Traceback (most recent call last):
>>   File "/usr/lib/python3.5/runpy.py", line 184, in
>_run_module_as_main
>>     "__main__", mod_spec)
>>   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
>>     exec(code, run_globals)
>>   File
>"/home/amanda/.local/lib/python3.5/site-packages/khal/__main__.py",
>line 25, in <module>
>>     main_khal()
>>   File
>"/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line
>722, in __call__
>>     return self.main(*args, **kwargs)
>>   File
>"/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line
>696, in main
>>     with self.make_context(prog_name, args, **extra) as ctx:
>>   File
>"/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line
>621, in make_context
>>     self.parse_args(ctx, args)
>>   File
>"/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line
>1018, in parse_args
>>     rest = Command.parse_args(self, ctx, args)
>>   File
>"/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line
>880, in parse_args
>>     value, args = param.handle_parse_result(ctx, opts, args)
>>   File
>"/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line
>1404, in handle_parse_result
>>     self.callback, ctx, self, value)
>>   File
>"/home/amanda/.local/lib/python3.5/site-packages/click/core.py", line
>78, in invoke_param_callback
>>     return callback(ctx, param, value)
>>   File "/home/amanda/.local/lib/python3.5/site-packages/khal/cli.py",
>line 126, in config_callback
>>     prepare_context(ctx, config)
>>   File "/home/amanda/.local/lib/python3.5/site-packages/khal/cli.py",
>line 207, in prepare_context
>>     conf = get_config(config)
>>   File
>"/home/amanda/.local/lib/python3.5/site-packages/khal/settings/settings.py",
>line 154, in get_config
>>     config_checks(user_config, _get_color_from_vdir, _get_vdir_type)
>>   File
>"/home/amanda/.local/lib/python3.5/site-packages/khal/settings/utils.py",
>line 192, in config_checks
>>     if config['calendars'][calendar]['type'] == 'discover':
>> TypeError: string indices must be integers
>
>I'm not quite sure how to troubleshoot this. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/issues/744

-- 
Sent from my phone. Please excuse my brevity.

**Comment by amandabee** [comment]
I'm using `vdirsync` to sync with a Nextcloud CalDav server. My config was this: 

> [calendars]
> path = "/home/amanda/.nextcloud/"
> type = "discover"

Before coming back here to post it, however, I did take a closer look a the documentation and come with this: 

> [[calendars]]
> path = /home/amanda/.nextcloud/*
> type = discover

and my error changed to this:

> critical: parsing the config file with the following error: Section too nested at line 1.
> critical: if you recently updated khal, the config file format might have changed, in that case please consult the CHANGELOG or other documentation
> If your configuration file used to work, please have a  look at the Changelog to see what changed.

I can troubleshoot the configuration syntax (I think) but it seems like at that first pass `khal` could/should have identified the problem as a config syntax issue, no?

**Comment by geier** [comment]
Try this:

>  [[calendars]]
>  [mycalendar]
>  path = /home/amanda/.nextcloud/*
>  type = discover

I agree that the config format is not ideal (because you are adding more than one calendar if type is set to discover) and the error message is a complete mess (I would have hoped that the library we are using for parsing the configuration file would have caught errors like this; I'll investigate how this error came about and, at the very least, add a better error message).
