### ISSUE TITLE
'NoneType' object has no attribute 'localize' on khal import

### ISSUE THREAD

**Issue by jbrea** [pimutils/khal#748]
khal, version 0.9.6

khal import event.ics
```
Traceback (most recent call last):
  File "/usr/bin/khal", line 5, in <module>
    main_khal()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/khal/cli.py", line 449, in import_ics
    env={"calendars": ctx.obj['conf']['calendars']},
  File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 546, in import_ics
    vevents = utils.split_ics(ics, random_uid, conf['locale']['default_timezone'])
  File "/usr/lib/python3.6/site-packages/khal/utils.py", line 622, in split_ics
    sorted(events_grouped.items())]
  File "/usr/lib/python3.6/site-packages/khal/utils.py", line 621, in <listcomp>
    return [ics_from_list(events, tzs, random_uid) for uid, events in
  File "/usr/lib/python3.6/site-packages/khal/utils.py", line 646, in ics_from_list
    sub_event = sanitize(sub_event, default_timezone=default_timezone)
  File "/usr/lib/python3.6/site-packages/khal/khalendar/utils.py", line 173, in sanitize
    value = default_timezone.localize(vevent.pop(prop).dt)
AttributeError: 'NoneType' object has no attribute 'localize'
```

content of event.ics
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//École - ECPv4.6.6//NONSGML v1.0//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:École 
X-ORIGINAL-URL:http://www.ecole.ch
X-WR-CALDESC:Events for École
BEGIN:VEVENT
DTSTART;TZID=UTC+1:20180112T203000
DTEND;TZID=UTC+1:20180112T220000
DTSTAMP:20180103T194913
CREATED:20150102T205413Z
LAST-MODIFIED:20171204T203751Z
UID:1216-1515789000-1515794400@www.ecole.ch
SUMMARY:Soirée d’information
DESCRIPTION:Vendredi 12 janvier\, 20h30\. \n
URL:http://www.ecole.ch
ATTACH;FMTTYPE=image/jpeg:http://www.ecole.ch/evenement-soiree-parents.jpg
END:VEVENT
END:VCALENDAR
```

config file
```
[calendars]

[[private]]
path = /home/j/.local/share/khal/calendars/private
type = calendar

[locale]
timeformat = %H:%M
dateformat = %d.%m.
longdateformat = %d.%m.%Y.
datetimeformat = %d.%m.%Y %H:%M
longdatetimeformat = %d.%m.%Y %H:%M

[default]
timedelta = 7d
```

**Comment by geier** [comment]
Can you please paste your config file? 

Am 3. Januar 2018 21:08:02 MEZ schrieb jbrea <notifications@github.com>:
>khal, version 0.9.6
>
>khal import event.ics
>
>Traceback (most recent call last):
>  File "/usr/bin/khal", line 5, in <module>
>    main_khal()
>File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in
>__call__
>    return self.main(*args, **kwargs)
>File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in
>main
>    rv = self.invoke(ctx)
>File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in
>invoke
>    return _process_result(sub_ctx.command.invoke(sub_ctx))
>File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in
>invoke
>    return ctx.invoke(self.callback, **ctx.params)
>File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in
>invoke
>    return callback(*args, **kwargs)
>File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17,
>in new_func
>    return f(get_current_context(), *args, **kwargs)
>File "/usr/lib/python3.6/site-packages/khal/cli.py", line 449, in
>import_ics
>    env={"calendars": ctx.obj['conf']['calendars']},
>File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 546,
>in import_ics
>vevents = utils.split_ics(ics, random_uid,
>conf['locale']['default_timezone'])
>File "/usr/lib/python3.6/site-packages/khal/utils.py", line 622, in
>split_ics
>    sorted(events_grouped.items())]
>File "/usr/lib/python3.6/site-packages/khal/utils.py", line 621, in
><listcomp>
>    return [ics_from_list(events, tzs, random_uid) for uid, events in
>File "/usr/lib/python3.6/site-packages/khal/utils.py", line 646, in
>ics_from_list
>    sub_event = sanitize(sub_event, default_timezone=default_timezone)
>File "/usr/lib/python3.6/site-packages/khal/khalendar/utils.py", line
>173, in sanitize
>    value = default_timezone.localize(vevent.pop(prop).dt)
>AttributeError: 'NoneType' object has no attribute 'localize'
>
>content of event.ics
>
>BEGIN:VCALENDAR
>VERSION:2.0
>PRODID:-//École - ECPv4.6.6//NONSGML v1.0//EN
>CALSCALE:GREGORIAN
>METHOD:PUBLISH
>X-WR-CALNAME:École 
>X-ORIGINAL-URL:http://www.ecole.ch
>X-WR-CALDESC:Events for École
>BEGIN:VEVENT
>DTSTART;TZID=UTC+1:20180112T203000
>DTEND;TZID=UTC+1:20180112T220000
>DTSTAMP:20180103T194913
>CREATED:20150102T205413Z
>LAST-MODIFIED:20171204T203751Z
>UID:1216-1515789000-1515794400@www.ecole.ch
>SUMMARY:Soirée d’information
>DESCRIPTION:Vendredi 12 janvier\, 20h30\. \n
>URL:http://www.ecole.ch
>ATTACH;FMTTYPE=image/jpeg:http://www.ecole.ch/evenement-soiree-parents.jpg
>END:VEVENT
>END:VCALENDAR
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/issues/748

-- 
Sent from my phone. Please excuse my brevity.

**Comment by geier** [comment]
The error happens because the specified TZID is not actually part of the .ics file, while this means it is in invalid .ics file, it really shouldn't crash khal.

This error has been In the master branch this is fixed (with obviously doesn't help you, but you could upgrade to master if you know how to do it).
Alternatively, remove `;TZID=UTC+1` from the lines starting with DTSTART and DTEND.
