### ISSUE TITLE
leaking colors on long description events

### ISSUE THREAD

**Issue by aleprovencio** [pimutils/khal#757]
Hello,
when calling khal from a terminal with reduced column numbers, the colors of events with long descriptions will leak to the calendar week near to it. Maybe the following screenshot will better describe:

First khal's output was generated when terminal was 191 columns wide, the second (and problematic) one with 95.
![teste](https://user-images.githubusercontent.com/1352683/36387173-f6861052-1576-11e8-8c19-cff26c04e743.png)

**Comment by geier** [comment]
Hi, which version of khal are you running? (I believe I fixed this some time ago...)

**Comment by aleprovencio** [comment]
this is khal 0.9.1 on Arch.
