### ISSUE TITLE
fix tests on python 3.7

### ISSUE THREAD

**Issue by geier** [pimutils/khal#758]
the tests are currently failing on python 3.7 because of an issue with freezegun https://github.com/spulec/freezegun/issues/225

Solutions:
 * [ ] xfail if using python 3.7 (bad)
 * [ ] fix freezegun (good)

**Comment by mrshu** [comment]
@geier Given the status of  spulec/freezegun#225 it seems that this can be closed as your second proposed solution should be doable.

**Comment by geier** [comment]
@mrshu Thanks for the information!
