### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by HanaO00** [pimutils/khal#759]
Hello, I do not know why with the option "new", or "-a", it puts me: no such option

**Comment by untitaker** [comment]
Please clarify what you are trying to do, and what command you enter. Note that "new" is not an option, it is a command. "-a" is an option of that command.

**Comment by amandabee** [comment]
In general the more complete you can be in your issue, the faster you can get a complete answer. 

I _think_ I've hit at least one of the walls you're hitting, which is that the `-a` flag fails if you don't specify a command first. Intuitively, I think that's unexpected behavior -- if `calendar` is my default command, meaning that the output of `khal` is the same as the output of `khal calendar` I instinctively expect `khal` to accept the same flags as `khal calendar`.  Unfortunately it doesn't. So if you want to use the `-a` flag you have to specify a command first: `khal list -a example` works, as does `khal calendar -a example`, but `khal -a example` does not: 

```
amanda@mona:~$ khal list -a logistics
No events
amanda@mona:~$ khal calendar -a logistics
    Mo Tu We Th Fr Sa Su     No events
May 30  1  2  3  4  5  6     
     7  8  9 10 11 12 13     
    14 15 16 17 18 19 20     
    21 22 23 24 25 26 27     
Jun 28 29 30 31  1  2  3     
     4  5  6  7  8  9 10     
    11 12 13 14 15 16 17     
    18 19 20 21 22 23 24     
Jul 25 26 27 28 29 30  1     
     2  3  4  5  6  7  8     
     9 10 11 12 13 14 15     
    16 17 18 19 20 21 22     
    23 24 25 26 27 28 29     
Aug 30 31  1  2  3  4  5     
amanda@mona:~$ khal -a logistics
Error: no such option: -a
```

But I'm not sure where you're getting tripped up with `khal new`. Can you clarify?
