### ISSUE TITLE
Not showing events from Office365 HTTP calendar

### ISSUE THREAD

**Issue by kamikazejoe** [pimutils/khal#770]
Khal stopped showing the majority of events from my Outlook calendar.  

I import it in as an "http" type calendar through vdirsyncer.  Vdirsyncer seems to be syncing fine, as it generates the .ics files in my calendars folder.

However, Khal doesn't seem to be reading them.  The only ones showing up are all day events, but anything with a specific time doesn't show up.  This started a couple of weeks ago.

**Comment by untitaker** [comment]
To be clear, you can find the missing event files using `grep` or similar?

Try deleting khal's sqlite database, maybe it helps

**Comment by kamikazejoe** [comment]
I was browsing through them with ranger, but yes.

Just tried removing the khal.db file.  The issue persists.  Also recently setup a new laptop, so it happened on a fresh install as well.  That's where I first noticed it.

**Comment by geier** [comment]
Can you post an example of an event which doesn't show up? (Feel free to remove any personal details).

**Comment by kamikazejoe** [comment]
Here's an example of a weekly repeating event :

```
VERSION:2.0
X-WR-CALNAME:Calendar
BEGIN:VEVENT
DESCRIPTION:To join the meeting:\n\n\n\n***REDACTED***
RRULE:FREQ=WEEKLY;UNTIL=20181024T150000Z;INTERVAL=1;BYDAY=WE;WKST=SU
SUMMARY:CAB Meeting
DTSTART;TZID=Central Standard Time:20180131T100000
DTEND;TZID=Central Standard Time:20180131T120000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20180425T232034Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:***REDACTED***
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
UID:1c5d13115049cf82475af78191bc57927362ff096d19c9e6b0f91486fe51e533
END:VEVENT
BEGIN:VTIMEZONE
TZID:Central Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0500
TZOFFSETTO:-0600
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0600
TZOFFSETTO:-0500
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
END:VCALENDAR
```

**Comment by geier** [comment]
This is probably due to khal not yet supporting the latest dateutil 2.7+, have a look at this [issue](https://github.com/pimutils/khal/issues/780) for a workaround until we support the latest dateutil again.

Could you verify that you are using dateutil 2.7+? (run `pip freeze | grep dateutil`) Thanks!

**Comment by kamikazejoe** [comment]
Probably.  Yes, I am running dateutil 2.7.3 at this time.

**Comment by kamikazejoe** [comment]
At first glance, the 0.9.10 release seems to have fixed the issue.

**Comment by geier** [comment]
Great, thanks for letting us now!
