### ISSUE TITLE
khal.khalendar.exceptions.UnsupportedRecurrence

### ISSUE THREAD

**Issue by dario23** [pimutils/khal#771]
i have a recurring event in one of my calendars, that both http://ical-validator.herokuapp.com/validate/ and https://icalendar.org/component/com_icalvalidator/ say is basically valid (first one complains about line ending style, but i don't think that's an issue here).

khal fails to parse it with this backtrace:

> Unknown exception happened.
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/khal/khalendar/khalendar.py", line 303, in _update_vevent
>     update(event.raw, href=href, etag=etag, calendar=calendar)
>   File "/usr/lib/python3/dist-packages/khal/khalendar/backend.py", line 262, in update
>     self._update_impl(vevent, href, calendar)
>   File "/usr/lib/python3/dist-packages/khal/khalendar/backend.py", line 355, in _update_impl
>     dtstartend = utils.expand(vevent, href)
>   File "/usr/lib/python3/dist-packages/khal/khalendar/utils.py", line 112, in expand
>     raise UnsupportedRecurrence()
> khal.khalendar.exceptions.UnsupportedRecurrence
> warning: Skipping cip
> warning: /f25edc51-fac1-4b55-9bdb-78b7207b1d1d.1476835067135.ics: 
> warning: This event will not be available in khal.

as far as i managed to read [RFC 5545](https://tools.ietf.org/html/rfc5545), the RRULE

> RRULE:FREQ=WEEKLY;UNTIL=20161017T095959Z;BYDAY=MO,TU,WE,TH,FR

and those in the VTIMEZONE element

> RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
> RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10

seem to be valid in terms of the rfc.

[ics.txt](https://github.com/pimutils/khal/files/1894674/ics.txt)

**Comment by bronzehedwick** [comment]
I have the same issue. Here's my error output:

```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/local/Cellar/khal/0.9.10/libexec/lib/python3.7/site-packages/khal/khalendar/khalendar.py", line 303,
in _update_vevent
    update(event.raw, href=href, etag=etag, calendar=calendar)
  File "/usr/local/Cellar/khal/0.9.10/libexec/lib/python3.7/site-packages/khal/khalendar/backend.py", line 262, in
 update
    self._update_impl(vevent, href, calendar)
  File "/usr/local/Cellar/khal/0.9.10/libexec/lib/python3.7/site-packages/khal/khalendar/backend.py", line 355, in
 _update_impl
    dtstartend = utils.expand(vevent, href)
  File "/usr/local/Cellar/khal/0.9.10/libexec/lib/python3.7/site-packages/khal/khalendar/utils.py", line 124, in e
xpand
    raise UnsupportedRecurrence()
khal.khalendar.exceptions.UnsupportedRecurrence
```

And here's the `ics` file:

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//FastMail/1.0/EN
BEGIN:VTIMEZONE
TZID:America/New_York
BEGIN:STANDARD
DTSTART:19700101T000000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700101T000000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20100917T150116Z
DTEND;TZID=America/New_York:20100920T130000
DTSTAMP:20110219T062531Z
DTSTART;TZID=America/New_York:20100920T080000
LOCATION:Hackensack University Medical Center
RRULE:FREQ=WEEKLY;UNTIL=20100913T035959Z;INTERVAL=2;BYDAY=MO,TU
SEQUENCE:1
SUMMARY:Photo
TRANSP:OPAQUE
UID:434464i-r1n0im3u0ppao1dj32qrerj1c4@google.com
END:VEVENT
END:VCALENDAR
```

**Comment by david-caro** [comment]
Might be fixed in #972

**Comment by d7415** [comment]
What are you expecting to happen with that event?

The ics says it starts on the 20th September 2010 (a Monday) and happens every 2 weeks on a Monday and Tuesday until the 13th September 2010, 1 week earlier.

**Comment by d7415** [comment]
Added a separate warning in #978. Closing this, at least until someone can explain what the broken recurrence should do.
