### ISSUE TITLE
Compatibiltiy with dateutil 2.7

### ISSUE THREAD

**Issue by geier** [pimutils/khal#780]
khal is currently not compatible with the latest version of dateutil.

The latest version of dateutil khal supports currently (as of 2018-05-10) is dateutil 2.6.1.

If you have systemwide already updated to dateutil 2.7+, I suggest you use [pipsi](https://github.com/mitsuhiko/pipsi) for installing khal right now.

**Comment by geier** [comment]
Sorry, I needed to publish a new version of khal (wich I did just now, khal 0.9.9) which includes the updated dependency. Can you try to reinstall with pipsi? (Or from github's master branch)

**Comment by dvzrv** [comment]
@geier what is the specific upstream issue for this?
It seems not only khal suffers from an incompatibility issue with dateutil atm

**Comment by dvzrv** [comment]
@geier is [this](
https://github.com/dateutil/dateutil/issues/652) related?
If so, would this be fixed in dateutil [2.7.3](https://github.com/dateutil/dateutil/releases/tag/2.7.3)?

**Comment by Holzhaus** [comment]
Can somebody elaborate what causes the problem? I'd try to fix this and contribute a patch, but I'm not really familiar with `RRULE` parsing or the khal codebase.

**Comment by dvzrv** [comment]
@geier well, I'll stop updating khal in Arch Linux [community] in the meantime then, until this is resolved...

**Comment by Holzhaus** [comment]
@geier did you make any progress? Is there anything I can do to help? This bug makes khal unusable for me.

**Comment by dotlambda** [comment]
Vobject version 0.9.6 was just released. Does this fix the issues?

**Comment by ludenticus** [comment]
Why was this issue closed? khal 0.9.10 and dateutil 2.7.5 are still producing this bug

**Comment by potuz** [comment]
> Why was this issue closed? khal 0.9.10 and dateutil 2.7.5 are still producing this bug

Not here 
```
 $ equery l python-dateutil
 * Searching for python-dateutil ...
[IP-] [  ] dev-python/python-dateutil-2.7.5:0
$ khal --version
khal, version 0.9.10
```

**Comment by ludenticus** [comment]
My experience is different. When I run ikhal and I get past some date, it ends with the following result: https://pastebin.com/gC0KJxcu

khal version 0.9.10
python-dateutil 2.7.5-1
Arch distro

**Comment by geier** [comment]
You are right, there is another issue with python-dateutil. But I'm not sure it's in the khal, I believe it is in icalendar.

```
  File "/usr/lib/python3.7/site-packages/khal/khalendar/event.py", line 151, in fromString
    calendar_collection = icalendar.Calendar.from_ical(event_str)
  File "/usr/lib/python3.7/site-packages/icalendar/cal.py", line 369, in from_ical
    _timezone_cache[component['TZID']] = component.to_tz()
```

Can you find out which event is causing the issues? If so, please remove private details and post it here, so I can have a look.

**Comment by jonassmedegaard** [comment]
According to https://github.com/collective/icalendar/issues/260 python-icalendar 4.0.3 is needed.

@ludenticus and @geier can you confirm that updating python-icalendar works for you?

**Comment by fosBHY** [comment]
re open this issue? For me its also not woring with pipsi, as I still have python-dateutil 2.8 afterwards, I guess. Normal install not working at all. khal with pipsi shows a calendar at the moment. when using interactive, I get the same 
RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware
