### ISSUE TITLE
Descriptions not showing

### ISSUE THREAD

**Issue by szarroug3** [pimutils/khal#785]
I have some items in my calendar that don't show descriptions even though they do have them. I've noticed that the ones that don't show them differ from the ones that do in the description field.

The ones showing them look like this:
DESCRIPTION:Hey, \n\nJust setting aside some dedicated time to talk about *redacted*.

The ones not showing them look like this:
DESCRIPTION;LANG=en_US:Hey, \n\nJust setting aside some dedicated time to talk about *redacted*.

Note: I did remove the LANG=en_US and then it started working so I'm pretty certain this was the problem. My workaround isn't really feasible though because it sends back updates to everyone on the invite when my calendar syncing program syncs because it recognizes a difference.

**Comment by geier** [comment]
Thank you for reporting this error, I'll have a look ASAP.
