### ISSUE TITLE
RRULE with UNTIL, again?

### ISSUE THREAD

**Issue by sciurius** [pimutils/khal#790]
Using the git version, the attached importfail.ics crashes with UnsupportedRecurrenceException.
Attached importok.ics imports with a warning.
The difference is that in importfail.ics, one of the EXDATE exceptions falls after the RRULE UNTIL.

It is my understanding that this was fixed (issue #591). Am I overlooking something?

[importfail.ics](https://github.com/pimutils/khal/files/2042350/importfail.txt)
[importok.ics](https://github.com/pimutils/khal/files/2042351/importok.txt)

**Comment by david-caro** [comment]
Might be fixed in #972

**Comment by ephase** [comment]
Hi,

Is it correct to have an EXDATE after the event end of he event? I don't find any information about that in RFC5545 but this case seem a bit bizarre.

**Comment by sciurius** [comment]
I think such a situation can result from the following scenario:
1. Create an event that repeats until the end of the year (2020-12-31)
2. Cancel one of the future occurrences (e.g. 2020-12-04). This adds an EXDATE.
3. Change the end date to before the cancelled event (e.g. 2020-11-27). RRULE UNTIL is now set before the EXDATE.

This is the resultant ics from the Nextcloud calendar client:
````
BEGIN:VCALENDAR
PRODID:-//IDN nextcloud.com//Calendar app 2.1.2//EN
CALSCALE:GREGORIAN
VERSION:2.0
BEGIN:VEVENT
CREATED:20201105T083243Z
DTSTAMP:20201105T083648Z
LAST-MODIFIED:20201105T083648Z
SEQUENCE:4
UID:f3ad5798-1461-4dab-a728-e6ea0a979712
DTSTART;TZID=Europe/Amsterdam:20201106T100000
DTEND;TZID=Europe/Amsterdam:20201106T110000
RRULE:FREQ=WEEKLY;BYDAY=FR;UNTIL=20201127T000000
EXDATE;TZID=Europe/Amsterdam:20201204T100000
END:VEVENT
BEGIN:VTIMEZONE
...
END:VTIMEZONE
END:VCALENDAR
````

Given that there is no clear information on what to do in this case (i.e. it is not strictly forbidden) I assume most clients just leave it as is.

**Comment by ephase** [comment]
Thank you, that's clear now. As you said there is not information about this special case in the RFC.

**Comment by d7415** [comment]
Looking at your importok and importfail examples, in importfail the UNTIL is before DTSTART. for importok they're the same. As far as I can see, that's *technically* legal in RFC5545, but I think we can agree is dumb.

The example [above](#issuecomment-722231683) actually imports successfully, with the warning:

> warning: In event f3ad5798-1461-4dab-a728-e6ea0a979712.ics, excluded instance starting at 2020-12-04 10:00:00+01:00 not found, event might be invalid.

I'm going to close this, but I'm happy to reopen if someone can explain the logic behind recurrences that stop before they start.
