### ISSUE TITLE
[PATCH] Add event uid to formattable attributes

### ISSUE THREAD

**Issue by sciurius** [pimutils/khal#791]
This patch adds the event uid to the formattable attributes. Very handy for debugging.
For example:
khal list --format "{bold}{calendar-color}{cancelled}{start-end-time-style} {title}{repeat-symbol}{description-separator}{description}({calendar}:{uid}){reset}"

[0001-Add-uid-to-formattable-attributes.patch](https://github.com/pimutils/khal/files/2045361/0001-Add-uid-to-formattable-attributes.patch.txt)

**Comment by geier** [comment]
Sorry, @sciurius  that your patch got list. This has been implemented independently with aadce9175a5ac9a14f4d39d1b7ea79e068974143 .
