### ISSUE TITLE
Failing tests with khal 0.9.9 and dateutil >= 2.7.3

### ISSUE THREAD

**Issue by dvzrv** [pimutils/khal#801]
Due to the python 3.7 rebuilds on Arch Linux, I'm currently faced with the need to upgrade the khal package to 0.9.9 and rebuilding against python3.7.
For this I have explicitely removed the dateutil pinning, as I can't build the package without doing that.

I would like to document the (12) failing tests here, that I disabled.
They are most likely due to dateutil on Arch being at 2.7.3 by now.
As we're rolling release, this will not get downgraded either, so it would be super great, if there would be a fix for dateutil >= 2.7 any time soon!

[khal_tests.log](https://github.com/pimutils/khal/files/2236414/khal_tests.log)

**Comment by sthen** [comment]
This is pretty much a dup of #780 / #798 - the commit which was just merged into master closed these.

**Comment by geier** [comment]
Agreed, thanks for pointing it out!
