### ISSUE TITLE
Ability to define default duration

### ISSUE THREAD

**Issue by madduck** [pimutils/khal#805]
Creating an event and specifying only a single timestamp results in an event with a default duration of 1 hour. My default timeslot is actually 50 minutes, and I'd really like to be able to override this. Could this please be exported to the configuration file?

Thank you!

**Comment by Jikhai** [comment]
Hi, we have two possible fixes for this issue, one adds a variable in the config file that sets the default duration of all events, the other allows to define a different default duration for each calendar. We however have yet to complete the unit tests. Which of the two options would be preferable ?

links to our fixes are respectively :
https://github.com/Khalzone/khal/tree/issue805
https://github.com/Khalzone/khal/tree/issue805b

**Comment by madduck** [comment]
Hey @Jikhai, the simpler solution (config file) will do just fine for me. I am not sure I can fathom a use-case where the additional complexity would be worthwhile.

**Comment by Jikhai** [comment]
Right now, we're waiting for @geier  's opinion on the matter before making a pull request.
We're also considering merging our two fixes so that both options can be used.
However, we'd like to know if you need this option only in `khal`  (command line) or in `ikhal` too (interface).

We've got most of it ready on hand, implementing it properly for `ikhal` will take just a bit more work, though.

**Comment by madduck** [comment]
Sounds good, @Jikhai. I am personally a fan of small steps, so merging the config file option first, then creating a pull request for per-calendar, and then one for `ikhal` would be my preferred way forward, especially if I was the project maintainer. It's just easier to work through chunks at a time, rather than one big convult.

**Comment by Jikhai** [comment]
Hey @madduck just a heads up,following your advice, and after going through all the testing, we made a pull request with just the config file fix ready, last Friday.
It is now pending for reviews.
