### ISSUE TITLE
ikhal: navigation issue

### ISSUE THREAD

**Issue by lenerd** [pimutils/khal#807]
Hi everyone,

I notices the following issue in `ikhal` which occurs when `ikhal` is run in a narrow terminal:

Consider a date in the right column s.t.
* there are no events on that day
* the date description "Monday, 01.01.1970 (~some years ago)" is wrapped into the next line (event titles are never wrapped)

Then the navigation downwards via `j` or the arrow key over such a date does not work, i.e., the cursor is stuck at the position above. Navigation upwards, however, is no problem.

**Comment by geier** [comment]
Thank you for reporting this, I'll have a look.

**Comment by lenerd** [comment]
Thanks. Let me know in case you need more information.
