### ISSUE TITLE
Events that start after beginning of DST contain no STANDARD or DAYLIGHT information in VTIMEZONE field

### ISSUE THREAD

**Issue by Pieter1024** [pimutils/khal#817]
I am using khal 0.9.10. When I create an event that starts after the start of DST in 2019, I run into problems when syncing it to CalDAVd via vdirsyncer. CalDAVd reports that the calendar data has unfixable problems: "[VTIMEZONE] At least one component must be present: STANDARD or DAYLIGHT".

I can reproduce this by creating one event right before the start of DST (say, the evening of 30 March 2019) and one right after the start of DST (say, the evening of 31 March 2019).

These are the .ics files that ikhal creates (also occurs with khal):

before start of DST:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PIMUTILS.ORG//NONSGML khal / icalendar //EN
BEGIN:VTIMEZONE
TZID:Europe/Amsterdam
BEGIN:STANDARD
DTSTART;VALUE=DATE-TIME:20181028T020000
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:abc123
DTSTART;TZID=Europe/Amsterdam;VALUE=DATE-TIME:20190330T190000
DTEND;TZID=Europe/Amsterdam;VALUE=DATE-TIME:20190330T200000
DTSTAMP;VALUE=DATE-TIME:20181020T194957Z
UID:S1RCXZ00XWW6YED07S7S9Z1LM2Q63DD88SQE
SEQUENCE:0
END:VEVENT
END:VCALENDAR
```

after start of DST:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PIMUTILS.ORG//NONSGML khal / icalendar //EN
BEGIN:VTIMEZONE
TZID:Europe/Amsterdam
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:abc123
DTSTART;TZID=Europe/Amsterdam;VALUE=DATE-TIME:20190331T190000
DTEND;TZID=Europe/Amsterdam;VALUE=DATE-TIME:20190331T200000
DTSTAMP;VALUE=DATE-TIME:20181020T195008Z
UID:07H39ZOVC4AIOGGY0VSE71Q7SMKT5MDALSX0
SEQUENCE:0
END:VEVENT
END:VCALENDAR
```

**Comment by geier** [comment]
Thank you for reporting this, will have a look ASAP.

**Comment by Pieter1024** [comment]
Thank you!

Please note that DST for 2018 has ended since I created this issue. The 
original instructions for reproducing it no longer work. Instead, to 
reproduce the issue now you have to create two events in October 2019.  
One in the evening of 26 October 2019 and one in the evening of 27 
October 2019 should work to reproduce the bug (it does for me).

It seems that the bug arises when the event you create is at least two 
DST switches into the future.

**Comment by himmelbuerger** [comment]
I'm new to khal and I think I run into the same problem. I'm not able to add events which are too far into the future. I can add them to khal but not sync. So at the moment I can't use khal to add events which are more than 2019-04-xx .
