### ISSUE TITLE
"pip unzip pytz" in FAQ not working anymore

### ISSUE THREAD

**Issue by heiderich** [pimutils/khal#822]
The [FAQ](https://khal.readthedocs.io/en/latest/faq.html) suggest to `pip unzip pytz` in order to speed up the start of khal and ikhal. However the `zip` and `unzip` commands of `pip` are deprecated as of pip version 7.0.0 (see https://pip.pypa.io/en/stable/news/). So I think this should no longer be a recommendation.

**Comment by geier** [comment]
Agree.
