### ISSUE TITLE
Are alarms a nonexistent feature?

### ISSUE THREAD

**Issue by hugbubby** [pimutils/khal#832]
I've been trying to look for anything related to the alarm section in your tutorials, docs, configuration guide, but I can't find out how to configure alarms or get them to alarm me at all about anything. How do I make it so that the alarm triggers some kind of notification mechanism?

**Comment by geier** [comment]
Sadly khal cannot actually alarm you at this time, it can only store information on when something else should alarm you. Sorry.

See https://github.com/pimutils/khal/issues/148
