### ISSUE TITLE
pip3 was needed to install khal on a system with python 3.4

### ISSUE THREAD

**Issue by RonCam** [pimutils/khal#833]
Installation attempts resulted in repeated failures (when using pip) as follows:
`    khal only supports python version 3.3+. Please Upgrade.`
But, python v3.4 was installed on the system.
With the following command, however, the installation went to completion.
`sudo pip3 install khal`
as indicated by:
```
Successfully installed khal click icalendar pytz tzlocal configobj atomicwrites
Cleaning up...
```
This was with Linux Mint 17.3 / Trusty.  If installing with pip3 is in the documentation, perhaps it could be given more prominence.  I only saw mention of using pip.

**Comment by vistad** [comment]
Thank you!
