### ISSUE TITLE
In interactive mode, typing w in input field exits editing

### ISSUE THREAD

**Issue by wirew0rm** [pimutils/khal#834]
Steps to reproduce:
In interactive mode, press n to add a new event. In any of the free text input fields (Name/Location/Description) type a small w and observe how the event is being saved and the view is back to the initial calendar view.
I did not test extensively, but maybe other keys might also be misinterpreted.

Version information:
khal, version 0.9.10
OS: nixOS unstable (19.03pre166449.be445a9074f)

**Comment by geier** [comment]
Sorry for my late reply, but I can't reproduce this behaviour at all. Could you perhaps update khal (and it's dependencies) and see if the issue is still there?

**Comment by geier** [comment]
Is this still an issue? (I still cannot reproduce this)

**Comment by wirew0rm** [comment]
Hey, thanks for coming back to this and for you patience, I mostly use the calendar on my phone, but yes, now and then I still stumble upon this.
I now investigated again and there was this section in the config: 
```
[keybindings]
save = w
```
After removing this everything works as inteded. I guess it makes sense that the keybinding listener is also active inside of input fields, as the default binding is "meta+enter" (which opens a new terminal with the default i3wm bindings, so that's probably why i reconfigured it in the first place, usually I stick with the default bindings).

For me "just don't use a single key without any modifier for this key" is good enough, I don't know what other options the TUI toolkit you used allows. I'll close this and feel a little bit embarrassed how trivial the problem was in the end.
