### ISSUE TITLE
khal --format does not print format correctly

### ISSUE THREAD

**Issue by lasers** [pimutils/khal#847]
`khal --no-color list --day-format "" --format "{start-time}|SEPARATOR|{title}"` does not print format correctly (imo) making it impossible for scripts to match values with the event properties.

* Expected `16:30|SEPARATOR|Coffee Break`
* Got `|SEPARATOR|16:30 Coffee Break`

EDIT: `khal, version 0.9.7.dev136+g46b4b3e`

**Comment by sciurius** [comment]
Are you sure the event has been entered correctly? It looks it was entered as a whole-day event and title "16:30 Coffee Break".

**Comment by lasers** [comment]
Yup, you're right. Thanks.
```bash
$ khal new 1:00 3:00 Summary :: Description
$ khal --no-color list --day-format "" --format "{start-time}|1SEP|{title}|2SEP|{end-time}"
01:00|1SEP|Summary|2SEP|03:00
```

The problem is caused by choosing `12 hour clock` in `khal configure`. Keep it open or close?

**Comment by sciurius** [comment]
You can close this one, but I suggest to create a new issue that it may be worth to add a warning to khal for the case a whole-day entry is made with a description that looks like it starts with a time.
