### ISSUE TITLE
Sort searches by date

### ISSUE THREAD

**Issue by bepolymathe** [pimutils/khal#852]
When I search for an event, I would like to be able to see the results sorted by date. At the moment, everything is in disorder. Here is an example with the word "réunion" (meeting in French). 

![image](https://user-images.githubusercontent.com/29939805/54940694-9005d480-4f2b-11e9-9cc1-aba3d2e2b447.png)

Is there a configuration solution for this?

**Comment by geier** [comment]
No, but I probably makes sense to order them by default.

**Comment by geier** [comment]
`khal search` results are ordered, too, so I'll treat this as a bug.

**Comment by geier** [comment]
fixed and released v0.10.1

**Comment by bepolymathe** [comment]
That's great ! Thanks @geier
