### ISSUE TITLE
calendar discovery glob doesn't handle recursion

### ISSUE THREAD

**Issue by samdmarshall** [pimutils/khal#864]
When using a glob'd directory path, I'm encountering an exception with getting it to parse nessted vdirs correctly.

This is the layout of the directory that `vdirsyncer` currently syncs all my calendars to:
```
/home/demi/Calendars/fastmail/
├── Cocoaheads 
│   └── Boston                      # vdir
│
├── Games 
│   ├── General 
│   │   └── Events                  # vdir
│   ├── Splatoon2 
│   │    ├── Salmon-Run             # vdir
│   │    └── Festivals              # vdir
│   └── The100                      # vdir
│
├── Holidays
│   ├── Japan                       # vdir
│   ├── UK                          # vdir
│   └── USA                         # vdir
│
├── Medical
│   └── Reminders                   # vdir
│
├── Personal
│   ├── Deliveries                  # vdir
│   └── Schedule                    # vdir
│
└── Work
    └── Events                      # vdir
```

The problem occurs when I try to specify a search path for one of these top-level directories (`Cocoaheads`/`Games`/`Holidays`/`Medical`/`Personal`/`Work`) where the level of nesting that the vdirs have is not all the same. so in this case the top-level directory `Games` has vdirs at depths of 1 and 2, so when I specify a glob to accommodate that:
```
[[Games]]
path = ~/Calendars/fastmail/Games/*/*
type = discover
readonly = True
```
then `khal` tries to treat everything at a depth of 2 to be a vdir, regardless if it is a file or directory. thus at startup I get an exception thrown because the `ics` files in the highest vdir are trying to be parsed as a vdir. I guess this isn't technically a bug in that regular because i'm telling `khal` that is where the vdirs are, but I don't know how to write the path so that `khal` will search the given path for vdirs and then classify the contents of the found vdirs under one calendar name in the application. if the special glob pattern `**` could be used to do this, or however to denote that kind of behavior, that would be awesome, but thus far I cannot figure out how to do that.

---
Version: `khal v0.10.1`

**Comment by geier** [comment]
Thank you for reporting this bug. As you can see from my late response to this and other bugs, I don't have as much time for khal as I would like to, but I hope I'll get to this one some time.

**Comment by samdmarshall** [comment]
@geier thank you very much! There isn't much I can do at the moment, but I would like to do what I can to help assist in resolving this issue. Please let me know if there is anything else I could provide or do to help with the further triage and resolution to this bug.

**Comment by geier** [comment]
I finally had a look at this issue. 

We currently support globbing, but without recursion (so no expansion of `**`). This means, all file vdirs must have the same depth from the original directory.

One solution would be to add `recursion=True` to the [glob.glob() call](https://github.com/pimutils/khal/blob/403a72dd22fb504a1ebd012208432a01b14f31b3/khal/settings/utils.py#L196) and then clean out all "intermediate" directories.
