### ISSUE TITLE
What happened to the --color switch, and default_command options ?

### ISSUE THREAD

**Issue by MaximeWack** [pimutils/khal#867]
Hi,

First of all, thank you for **khal**, I love it and use it as my primary calendar.

I'm using khal as an interactive calendar using `ikhal`, and with `khal --color` as a way to pass the current calendar to conky, *with the colors*.

Why does 0.10 remove the *default_command* option? Simply calling `khal` doesn't work anymore, you have to call `khal calendar` to simply display the calendar! (it's a point of detail, as I call the command from a script, but it's a matter of convenience and I don't see the rationale behind deleting this option altogether).

**More importantly**, why getting rid of the _--color_ switch?!
It allowed the secondary use of the output from `khal`, with the full information brought by the colors, but that switch is also deprecated so calling `khal calendar > /tmp/calendar` yields a boring monochrome calendar! (there would be a solution using `script` but this is way more cumbersome than keeping the _--color_ switch, used by many standard tools)

As a side note, you shouldn't deprecate functionalities when doing only a _minor version_ bump, and at least advertise the deprecation to your users in advance.

Anyway, thanks again for your time and effort on this software, it is greatly appreciated, and sorry for asking for things.

**Comment by MaximeWack** [comment]
Apparently, this is not a feature deprecation as the **click** code for the *--color/--no-color* option seems to still be there, and is still present in the docs and in *--help*. Might be considered a bug then?

In **khal version >0.10**, calling `khal --color` yields
> Error: Missing command.

**Comment by Konfekt** [comment]
Running `ikhal` yields
```
warning: unknown key or subsection "default_command" in section "[default]"
```
but the setting `default_command` in section `[default]` is amply documented everywhere.

**Comment by Konfekt** [comment]
Oh well, this is explained in https://github.com/pimutils/khal/commit/f8d9135bb51d3cd86f517ba0de0ef02670a92387 and https://github.com/pimutils/khal/issues/648

**Comment by Konfekt** [comment]
Since this setting is still documented in many places, a warning that this key was deprecated by https://github.com/pimutils/khal/commit/f8d9135bb51d3cd86f517ba0de0ef02670a92387 would be more helpful.

**Comment by geier** [comment]
Thank you for pointing this out. We'll need to get that sorted out ASAP. Help with the documentation is very much appreciated.

**Comment by Konfekt** [comment]
Regarding documenting the removal, https://github.com/pimutils/khal/pull/874 adds an FAQ entry. 

To find the entry  the warning message when `default_command` is found in the `khal` configuration file should hint to it.

**Comment by Konfekt** [comment]
Perhaps https://github.com/pimutils/khal/blob/fc5c2bfe8f8ea54e665d83d484f00cea0a6777c3/khal/settings/settings.py#L146 could simply check if the unknown key equals one of the deprecated ones and refer to the FAQ?

**Comment by geier** [comment]
Good idea, feel free to send another PR.

**Comment by geier** [comment]
Do you think this is now documented sufficiently?

**Comment by MaximeWack** [comment]
There is still the problem of the *--color* switch.
Is it also a deprecated option, as default_command?

**Comment by geier** [comment]
No, it isn't and `khal --color calendar > test.out` works for me and does have the color codes in `test.out`.  Can you paste the error message you are getting?

**Comment by MaximeWack** [comment]
Oooooh, right, I didn't think of the interplay between those two!  
I only tried `khal --color > out` and, as I thought of the deprecation of default_command as a separate problem, I didn't realize I had to call `khal --color calendar`. Or I might have tried `khal calendar --color`, which doesn't work, with the following error:

```
$ khal calendar --color                                                                             INSERT
Usage: khal calendar [OPTIONS] [DATERANGE]...
Try "khal calendar --help" for help.

Error: no such option: --color
```

**Comment by geier** [comment]
This might be a documentation problem as well. I'll close this issue now, but feel free to open a new one for the documentation problem.
