### ISSUE TITLE
Published documentation seems outdated

### ISSUE THREAD

**Issue by WhyNotHugo** [pimutils/khal#868]
Looks like the documentation at https://khal.readthedocs.io/en/stable/configure.html is outdated. See, for example, `timeformat`:

- https://khal.readthedocs.io/en/stable/configure.html#locale-timeformat
- https://github.com/pimutils/khal/blob/v0.10.0/khal/settings/khal.spec#L101

**Comment by geier** [comment]
I can't figure out the issue and opened an issue with readthedocs: https://github.com/rtfd/readthedocs.org/issues/5766

**Comment by geier** [comment]
fixed with  f355e5d
