### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by abc1324** [pimutils/khal#869]
Because I just signed up, I cannot post many different issues over a small time frame. Please, can some moderator help?

I'm currently on 0.8.4

* When importing an ics, please allow the user to specify from which and to which day to import: some ics's that I wanted to import contain events dating back to 2013 and which I'm not interested about!

* When importing an ics, why make it mandatory to specify in the first place which calendar I want to import to?

* When specifying which calendar I want to import an ics to, if the names that I've given to my calendars are numbers, then there's confusion when choosing an option because khal assigns a number to every possible choice and it might coincide with the number that I have called some of my calendars by.

* When importing an ics, given that it's mandatory to specify which calendar I want to import to, why does khal prompt me to choosing which calendar I want to import to?

* When importing an ics, after I specified my calendar, after being prompted with the list of my calendars, there's no option to cancel the operation (I need to specify one of my calendars and then hit 'no' for every event, but I cannot cancel the whole thing).

* When importing an ics with many events, please give the use the possibility to edit the events while adding them to one of the calendars.

* Sometimes, when changing a whole-day event to some starting time and ending time, ikhal quits throwing AttributeError: 'datetime.date' object has no attribute 'date'.

Thanks!

**Comment by geier** [comment]
Thank you for taking all the time to write down your issues. Sadly, I'm currently very time constraint and cannot support old releases any more (I don't even have the time needed to fix the issues in the latest version). Please upgrade to the latest released version and see if your issues are gone and report them again if they are not.
