### ISSUE TITLE
import all events

### ISSUE THREAD

**Issue by brunoschroeder** [pimutils/khal#881]
Dear khal community.

I love your application! Use it everywhere!

I have been downloading and importing .ics that come from (sic) Microsoft Outlook O356 server. It works perfectly, but it is anoying because it asks me one million times:
Do you want to import this event into `Default`? [y/N]:

Can we have an import all option?

Thank you very much in advance!

Kind regards,

Bruno

**Comment by brunoschroeder** [comment]
Bash is beautiful and saves us all:
while true; do echo y; done | <command>

**Comment by geier** [comment]
`khal import --batch` should also work.

**Comment by brunoschroeder** [comment]
UnboundLocalError: local variable 'cal' referenced before assignment

**Comment by geier** [comment]
Could you paste the stack trace please?

**Comment by brunoschroeder** [comment]
It worked now!
I could not reproduce the error...

Seems both ways work and I got a good way to curl the ics files I need. Happy to use this tool! Prompt makes me happy.

**Comment by brunoschroeder** [comment]
One interesting problem is: I am always adding everything from the ics file. We could have an --update flag.
