### ISSUE TITLE
Error: no such option: --alarm  Did you mean --alarms?

### ISSUE THREAD

**Issue by laur89** [pimutils/khal#886]
Following command causes `Error: no such option: --alarm  Did you mean --alarms?` error:

    khal new -a work --alarm 15m --location 'my location' '01/10/2019' '13:55' '01/10/2019' '15:54' 'title' '::' 'waddup event body'

According to man pages, `--alarm` is a valid option.

    khal --version
    khal, version 0.9.10

**Comment by polyzen** [comment]
https://github.com/pimutils/khal/commit/90319597ebaa09bfcd19cc52b2962fe97e49eac0 

There just hasn't been a release yet.
