### ISSUE TITLE
Manjaro pacman install - ModuleNotFoundError

### ISSUE THREAD

**Issue by Ginner** [pimutils/khal#887]
I've installed `khal` with `sudo pacman -S khal` and the install proceeded without problem. This installed `khal-0.10.1-1`.

Right after, I tried to run khal and received the following Traceback:
```
    Traceback (most recent call last):
      File "/usr/bin/khal", line 2, in <module>
        from khal.cli import main_khal
    ModuleNotFoundError: No module named 'khal'
```

I've tried reinstalling.

I'm on 4.19.69-1-MANJARO, pacman v5.1.3

Any help is appreciated, thank you.

**Comment by Ginner** [comment]
I've installed with `pip` as instructed on the 'Installation' page and it works fine. I'd have liked if I could install through my package manager and manage updates and the likes through there however.

**Comment by quentin-ag** [comment]
I faced the same issue when I was in a Python virtual environment, and had forgotten about it. I hope this will help someone else who will land here for the same problem.
