### ISSUE TITLE
Status of dateutil 2.7 support

### ISSUE THREAD

**Issue by s-hamann** [pimutils/khal#888]
Judging from the open and closed issues, I believe >=khal-0.10 works with dateutil 2.7. Is that correct?
The changelog has a quite prominent note stating that only older version are supported. I believe this is not correct any more and was simply forgotten when unpinning dateutil in 985fd5c13f63111c0a9f265c8de06b2e5a8427ad.
This may confuse package maintainers who try to figure out the correct dependencies for khal.

**Comment by geier** [comment]
You are right, thanks for pointing this out, I'll add another note in the changelog.
