### ISSUE TITLE
incorrect parameter name in khal.ui.widgets

### ISSUE THREAD

**Issue by pizzacoca** [pimutils/khal#895]
In khal/ui/widgets.py

 self._original_widget = urwid.AttrMap(EditWidget(*args, **kwargs), 'edit', '**editf**')

There is no  parameter of that name in khal/ui/colors.py
Maybe it should be **edifc** or **edit focused**

Also, having one parameter "edit focused"  would be more understandable
![khal_editf](https://user-images.githubusercontent.com/3603774/68324473-ba299280-00c7-11ea-9cb9-e331e384114a.png)

**Comment by geier** [comment]
fixed with #896
