### ISSUE TITLE
ikhal: frame around leftpane breaks indent

### ISSUE THREAD

**Issue by palb91** [pimutils/khal#897]
Hi!

I'm using `khal, version 0.10.1`.

It seems that `ikhal` suffers from a ui bug on the left pane, when I go to the
right the current line loses its left indentation. This can be repeated with
the following lines. I think that a picture could help ;)

![ikhal_frame_bug](https://user-images.githubusercontent.com/29063375/68372476-3ad8a500-0141-11ea-9dd9-628e4d08eea3.png)

- First I'm on the day "déc. 30" (any day on the last column);
- Then I press `right` or `l` or `space` and… the entire line go to the left;
- `right`, `down`, `right`, `down`… repeat this on several lines.

When I go to the left, the line appears correctly.

I tried some configurations, the bug is related to the `[view]` frame options
when set to `width` or `color`. Globally when there is a complete frame around
the calendar.

**Comment by ephase** [comment]
Hi!

I tried to reproduce the bug but all work like a charm here . Can you give more details about your configuration :
 - your distribution
 - versions of python installed
 - your terminal emulator

**Comment by palb91** [comment]
Well:
- I'm on Arch Linux (up-to-date) ;
- I installed khal from community (0.10.1-1) ;
- Python version is 3.7.4 ;
- I use urxvt (v9.22).

After reading your message, I tried ikhal on xterm, alacritty and kitty and have the same behavior… only with `width` and `color`.

**Comment by ephase** [comment]
Ok I reproduced the issue, I'm going to investigate, thank you.

**Comment by ephase** [comment]
I submit a fix for it, can you try it and tell me if the bug is resolved? 

Thank you.

**Comment by palb91** [comment]
That was fast!
I'd never have noticed the missing sunday…
I just checked with all frame options, the fix is perfect.

**Comment by ephase** [comment]
This bug seems quite easy by the way the patch is. My PR need some review by maintainers because I'm a newbie in Python and work on khal since few. But thank you for testing it.

**Comment by ephase** [comment]
This bug occurs on a special condition : on french locale, this is why I've got this bug too on one of my machine. This is because abbreviated month name is longer with french locale.

**Comment by palb91** [comment]
Nice :+1:
