### ISSUE TITLE
Here come a new maintainer?

### ISSUE THREAD

**Issue by ephase** [pimutils/khal#908]
Since I have some time, love khal and read the message on the website, I propose myself for becoming a maintainer. I'm a beginner at developing Python application but motivated, I can help for bugs triage, code review and propose PR for beginning.

I work on #906 with #907 PR (which need some improvement), #904, on PR #902  ..

**Comment by d7415** [comment]
I'll hijack this to say that I'm happy to do some triage/ticket work and maybe occasional bug squashing. I'm not going to pretend I have enough time to fully maintain the project though.

**Comment by ephase** [comment]
I don't have enough time to fully maintain khal alone too but i can contribute, this is the idea behind my demand.

**Comment by geier** [comment]
Thanks to you two for stepping up. Remember, with great power comes great responsibility ;-) 

@amandabee You have also been active some time ago, are you interested in helping maintain khal?

**Comment by amandabee** [comment]
I think my skill set leans distinctly towards identifying potential improvements to UX and Documentation (rather than, say, implementing those UX improvements ... documentation I can do.)
