### ISSUE TITLE
How to insert a newline into "khal list ... --format"{start} {end}" 

### ISSUE THREAD

**Issue by wehkah** [pimutils/khal#909]
Hallo,

I'd like to put in a newline between start and end, but a simple 

`--format"{start}\n{end}" `

does not work. What is the correct way of doing this? 

I know I could do two queries:

```
khal list ... --format "{start}" 
khal list ... --format "{end}" 

```
But I think two callings for one event should not be necessary.

**Comment by ephase** [comment]
Hi, you can add a nl character with `{nl}` for example :

```
khal list --format {start}{nl}{end}
```

**Comment by wehkah** [comment]
That does not work either:

```
~$ khal list -a private 2020-02-14 2020-02-14 --format "{start}{nl}{end}" 
critical: 'nl'
```

**Comment by ephase** [comment]
This work for me :
```
khal list -a Boulot 18.02.2020 18.02.2020 --format "{start}{nl}{end}"
Tuesday, 18.02.2020
18.02. 08:00
18.02. 12:00
```

Can you give me the return of `khal printformats`

**Comment by wehkah** [comment]
Certainly:

```
$ khal printformats
longdatetimeformat: 2013-12-21 10:09
datetimeformat: 2013-12-21 10:09
longdateformat: 2013-12-21
dateformat: 2013-12-21
timeformat: 10:09

```

**Comment by ephase** [comment]
I can reproduce the bug by downgrading my khal version to 0.9.10, unfortunately, if your distribution is Debian, 0.9.10 is the version packaged by Debian team.

**Comment by wehkah** [comment]
Thank you for your effort! 

Yes, the machine that is to use khal is running Debian Buster. 

But at least now I know that it's possible to get what I want. ;) 

I think I will try a manual update. I guess that should not be that hard, should it?

**Comment by wehkah** [comment]
Ooops! I spoke to soon:


```
Collecting khal
  Downloading https://files.pythonhosted.org/packages/f7/45/555398810c14f572ea9ff8e92cd4f6e492ba8c50da1241fad58e58234463/khal-0.10.1.tar.gz (173kB)
    100% |████████████████████████████████| 174kB 642kB/s 
    Complete output from command python setup.py egg_info:
    ########################################################
    khal only supports python version 3.4+. Please Upgrade.
    ########################################################
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-52xAfw/khal/

# python --version
Python 2.7.16

```

So I will have to stick with the slightly outdated version 9.1 and simply do make two calls instead of one.

**Comment by d7415** [comment]
Try `pip3 install...`

**Comment by ephase** [comment]
@wehkah yes khal is incompatible with python 2, try with `pip3 install khal`, if it doesn't work I can try it on a container at home.

**Comment by wehkah** [comment]
Thank you for the hint! That worked! At first glance I had not noticed that both python version were installed. "pip3" installed the latest version of "khal" in /usr/local/bin, and it works perfectly.

Thanks again! :)

**Comment by d7415** [comment]
@wehkah Could you close this issue please now that it's resolved?
