### ISSUE TITLE
Version 0.10.1: complaining about multiple UID in ics file

### ISSUE THREAD

**Issue by wehkah** [pimutils/khal#912]
I think I found a bug:

```
:~# khal list --format "{start-time} {start-date} {end-time} {end-date}" --day-format ""
warning: The .ics file at test/test.ics contains multiple UIDs.
warning: This should not occur in vdir .ics files.
warning: If you didn't edit the file by hand, please report a bug at https://github.com/pimutils/khal/issues .
warning: If you want to import it, please use `khal import FILE`.
warning: Skipping test/test.ics: 
warning: This event will not be available in khal.
No events

```

Steps to reproduce:

- create an new calendar with your favourite calendar program/app, like Thunderbird/Lightning
- insert two new events
- export that calendar to a local ics file
- let khal use it
- watch above error message

Version 0.9.10 does not complain about the calendar file.

The ics file that was "faulty" according to khal looks like this:

```
:~# cat /tmp/test.ics 
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20200216T094216Z
LAST-MODIFIED:20200216T094228Z
DTSTAMP:20200216T094228Z
UID:310d7e8a-b714-4c20-95d7-d5b2c6f10eb3
SUMMARY:Neuer Termin
DTSTART;TZID=Europe/Berlin:20200216T110000
DTEND;TZID=Europe/Berlin:20200216T120000
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT45M
DESCRIPTION:Mozilla Standardbeschreibung
END:VALARM
END:VEVENT
BEGIN:VEVENT
CREATED:20200216T094250Z
LAST-MODIFIED:20200216T094255Z
DTSTAMP:20200216T094255Z
UID:0e73ac32-d793-47e9-8b5e-f0540b9ada53
SUMMARY:Neuer Termin
DTSTART;TZID=Europe/Berlin:20200217T110000
DTEND;TZID=Europe/Berlin:20200217T120000
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT45M
DESCRIPTION:Mozilla Standardbeschreibung
END:VALARM
END:VEVENT
END:VCALENDAR

```

**Comment by d7415** [comment]
Hi. This isn't a bug, but deliberate behaviour - the `vdir` format should only have one event per .ics file. Multiple events should be multiple files within a single folder (calendar).

The [change](https://khal.readthedocs.io/en/latest/changelog.html#id3) you've noticed is listed as `FIX Check for multi_uid .ics files in vdirs and don’t import those events (All .ics files in vdirs should only contain VEVENTS with the same UID.)`

**Comment by wehkah** [comment]
I understand what you're saying, but I don't see any sense in ical files containing only one event at a time. For one event only, nobody would need a complete calendar file, would they? Furthermore, I don't know any calendar program or app, that will split a calendar into zillions of single ical files when exporting that calendar.

I don't blame khal for this, but restricting an ical file to one event only, while every calendar app exports a complete calendar to one single file that contains all events, does render tools like khal nearly useless.

**Comment by d7415** [comment]
khal is explicitly designed to work in `vdir` format, which is strongly implied if not outright stated in the README and is further mentioned in the configuration page of the docs.

There are advantages to having a file per event rather than per calendar, similar to using Maildir instead of mbox storage for emails.

In general, as is made fairly clear, khal is intended to be used with [vdirsyncer](https://github.com/pimutils/vdirsyncer), which can synchronise this format with, for example, a CalDAV server.

If khal does not support the behaviour you're after, I suggest you look at alternatives, or try forking khal to suit your needs. Unfortunately those in the [alternatives](https://github.com/pimutils/khal#alternatives) section probably won't be of any use to you in this case.

**Comment by wehkah** [comment]
I do know that there are advantages having one event per file, but the question remains: how do you spit a calendar into single events, when every calendar app, especially those usable only with a GUI, are exporting one complete calendar to one single file?

Wherever I choose to export a calendar, whether in Lightning, in NextCloud, in Evolution, or on my Android devices, I never get an option to create one file per event. No offence meant, but according to your word above, all these programs have to be considered "faulty", because they don't export calendars correctly, do they?

**Comment by d7415** [comment]
They're not faulty - they're designed differently. I haven't used NextCloud, but my understanding is that it's used as a DAV server rather than manually exporting as you describe. The recommended workflow in such an instance would therefore be something like

```
(Lightning|Evolution|Android|etc) <-CalDAV-> NextCloud <-CalDAV-> vdirsyncer <-shared directory structure-> khal
```

So that DAV is used to communicate between NextCloud's centralised storage and other apps, and vdirsyncer used as middleware to connect khal to the DAV resource.

**Comment by piater** [comment]
> restricting an ical file to one event only, while every calendar app exports a complete calendar to one single file that contains all events, does render tools like khal nearly useless.

FWIW, `khal import` correctly handles `.ics` files containing multiple VEVENTs.

**Comment by geier** [comment]
as @piater pointed out, the intended usage is to use `khal import` for one time imports of .ics files. If you want to one-way sync from .ics files to khal, use vdirsyncer.  The vdir folders are supposed to be the `backend` of khal that are not modified by hand (unless something went very wrong).

**Comment by Vinfall** [comment]
`khal import` still import events in .ics files one by one. For large files (I have a file full with events from 1901 to 2100...), one have to use:

```sh
cd ~/.local/share/khal/calendars/somewhere
khal import --batch *.ics
```
