### ISSUE TITLE
khal list: multiline calendar entries should not line wrap

### ISSUE THREAD

**Issue by m1027** [pimutils/khal#918]
Calling khal list is sweet and short for daily use.

However, when (non-console) people add long calendar entries (like when
accepting long events e.g. coming in by email) these entries get hard
to read on a console due to line wrapping.

Workaround: When using the interactive ikhal, then each long content is merged
into a single line, and *not* wrapped but cropped. So, there is one entry per
line.  This is easy to read.

Could we have a behaviour for khal list like for ikhal? E.g. khal list
--no-wrap.  Or maybe even the other way round: Make no-wrap the default and
add --wrap or so optionally?

Thanks a lot.
khal is awesome.

**Comment by d7415** [comment]
I can see some benefit to this. I'd be reluctant to change the default behaviour though - in `ikhai`, the full entry is only a couple of keypresses away, whereas in `khal` it's a whole new command.

**Comment by m1027** [comment]
Okay, maybe some more from the workflow I mean:

- I have a small standard console open.
- I want to check new calender events.
- I type: khal list
- I cannot use what khal list outputs because I get several screens full of crap since other users with graphical calendars like thunderbird add (accept) events and have not even a chance to shorten the content.
- I call ikhal then as a workaround
- ikhal erases my previous console content (because it's ncurses)
- I see the calendar events as desired...
- ...but the left half of the console is filled with the day selection and thus even less to see
- I quit ikhal and get dropped into an unclean console becaue ikhal does not wipe the screen
- I call clear or so to wipe
- I scroll upwards to see what I did in the console before calling ikhal

Instead it would be cool to have something like:

- I have a small standard console open.
- I want to check new calender events.
- I type: khal list --no-wrap
- I get the entries listed, long lines cropped

Hope that makes it clearer a bit.
Thanks

**Comment by d7415** [comment]
Yeah, that's roughly what I was thinking.

**Comment by d7415** [comment]
As another point, when I run `ikhal` and quit, there is no trace of it left in the console (aside from the `$ ikhal` line)

**Comment by m1027** [comment]
I am closing the ticket because there seems to be no interest in changing the behaviour.
