### ISSUE TITLE
Khal crashes with KeyError: 'PROTO', but does not tell on which entry

### ISSUE THREAD

**Issue by tfinke** [pimutils/khal#927]
Dear Maintainers, 

khal keeps crashing with KeyError: 'PROTO'. We tried to find the reason. We assume an antry that might contain problematic data. But khal does not tell, on which entry the error occurs. How could we find out? 

Thanks for your great project and best regards

Torsten

[khal-crash-proto.txt](https://github.com/pimutils/khal/files/4348945/khal-crash-proto.txt)

**Comment by ephase** [comment]
Hi @tfinke, 
Can you give us more information about your system : 

 - Which distribution and version
 - khal installed with packet or by hand (pip for example)
 - type of your calendar server (Nextclou, Baïkal, Radicale ...)

Thanks

**Comment by tfinke** [comment]
Dear Ephase

sorry, that I have missed to give that important informations:
- OpenLeap 42.2 
- khal, version 0.10.1, khal and all it's dependecies installed via pip3.4
- davical server (1.1.5 from git)

We have experienced several problems from entries that were generated by the evolution mail program. Normally has khal the showed the very entry. 

Thanks and best regards

Torsten

**Comment by ephase** [comment]
Can you give me an example of `ics` file created by Evolution please? I'll try to test it with my dev environment.

I'll try to install Opensuse Leap 42.2 as soon as i have some time to do more tests. But this distribution is noted EOL on OpenSuse website.

**Comment by tfinke** [comment]
Dear ephase

please find an example attached. It is the same which caused khal to crash mentioned in my issue #923. There khal had reported the entry. 

In the case of this issue #927 khal had crashed without an information about the entry, that might have caused the crash. So I cannot confirm that an evolution created entry was the reason of crash.

I do not believe that the behaviour depends on the distribution. We have installed khal by pip3.4 as well as all it's prerequisites. You are right: the Leap 42.2 is EOL. But that system is highly maintained by ourselves. 

Thanks and best regards
[ae55af91f70151247d69fd4afbb3d6ee4f090b9e.txt](https://github.com/pimutils/khal/files/4408535/ae55af91f70151247d69fd4afbb3d6ee4f090b9e.txt)

**Comment by ephase** [comment]
So I made somes test and found a issue that is linked to yours https://github.com/collective/icalendar/issues/303 and lonked to yours #923. 

I created a `virtualenv` and integrate this repo  https://github.com/simon-budig/icalendar/commit/c42e8220dd2911c8a0203cebb59e6c50370bf006 for iCalendar and khal work.

Do you aware of `venv` creation with python to made some tests? I can help you if you want.

By the way I could not reproduce the bug you're mention here with `keyerror PROTO`, maybe i need to test it with python 3.4

**Comment by tfinke** [comment]
Dear Ephase,

thanks for your effort in investiogations on our issue.

We could try to build a virtual environment, but I am not optimistic, that this would help to analyze the problem. We (many users) use khal against a davical server which serves tenthousands of items. The problem occurs only at some of our users although they are subscribed to almost identical calendars. I suppose that the problem is caused by an entry, but how could one find out which one? 

Could we - for debugging - add some diagnostic code to "khal/khalendar/event.py"? I have tried to understand what's going on there, but that is very tricky.

Best regards

Torsten

**Comment by ephase** [comment]
Hi @tfinke,

A `virtualenv` (python one) is for installink khal only on your machine, i could be useful to test your calendars with simonPR on icalendar project, For example on my machine I did : 

```
mkdir -p khal\test && cd khal
cd khal
virtualenv ./venv
source ./venv/bin/activate
git clone https://github.com/simon-budig/icalendar
pip install -e ./icalendar
pip install khal
ikhal
```

The command above create a python virtualenv separate from your system, then you can install the Simon's version of icalendar with his patch. Then you can start ikalendat from the venv you activated with the command `source ./venv/bin/activate`

**Comment by geier** [comment]
I really don't understand how this can happen at the moment, but hopefully improved the error message so that the event causing this can be identified.
