### ISSUE TITLE
The .ics file contains multiple UIDs.

### ISSUE THREAD

**Issue by tororsteen** [pimutils/khal#933]
Syncing Googel calendar with vdirsyncer 
From terminal:
warning: The .ics file at felles/xxxx@gmail.com.ics contains multiple UIDs.
warning: This should not occur in vdir .ics files.

**Comment by d7415** [comment]
Hi. The [vdir](https://vdirsyncer.readthedocs.io/en/stable/vdir.html#the-vdir-storage-format) format should only have one event per .ics file. Multiple events should be multiple files within a single folder (calendar).
