### ISSUE TITLE
Why is neccesary a database for cache?

### ISSUE THREAD

**Issue by pqks** [pimutils/khal#934]
Hi Khal developers. 
Can you explain me cuz khal has a database for caching? Why don't have only plain text data? I've looking the config and data files from calcurse and I look that all data from it is only plain text files.

Thank you for you hard work.
Bye.

**Comment by WhyNotHugo** [comment]
Reading and parsing all the files each time you run khal is way too slow, especially for a cli app (in the order of several seconds for many users).

The cache makes sure we only have to do that huge reading+parsing once (and then just read new/updated files).
