### ISSUE TITLE
First time configuration did not set up a 'default' section.

### ISSUE THREAD

**Issue by ciminobo** [pimutils/khal#935]
This was on version 0.9.10 installed on Ubuntu 20.04
`khal configure` did not create a default section the first time I ran it. This produced a very confusing error saying
```
    user@user-desktop:~$ khal new dentist
    Usage: khal new [OPTIONS] [START [END | DELTA] [TIMEZONE] [SUMMARY] [::
                                DESCRIPTION]]

    Error: Invalid value: No default calendar is configured, please provide one explicitly.
```

It's not a good user experience that the calendar is not ready to add new events after initial configuration.
One would expect that the default_calendar should be set to (at the moment of initial configuration) the only calendar listed in the config, or some other comment be created in the config file indicating how to set it up.

**Comment by ephase** [comment]
Hi @ciminobo 

`configure` doesn't seems to configure default calendar. This is en enhancement that could be done.

**Comment by ciminobo** [comment]
Thanks for responding. I have one more suggestion to add auto-completion as a feature. I develop a python cli tool as my day job and there's an argcomplete module that, when combined with argparse, allows for easy and complete argument completion. Is this issue board a good place for feature requests? I don't want to spam.

**Comment by ephase** [comment]
You can open an other issue, but khal use `click` instead of `argparse`.

**Comment by d7415** [comment]
> It's not a good user experience that the calendar is not ready to add new events after initial configuration.

Agreed, though in general `khal new` is used with the `-a` flag to set a calendar, which is much more important if you have multiple calendars.

> One would expect that the default_calendar should be set to (at the moment of initial configuration) the only calendar listed in the config, or some other comment be created in the config file indicating how to set it up.

A comment might make sense. Setting default if there's only one calendar (or even choosing the only calendar for `khal new` etc if there is only one) could be useful enhancements. Bear in mind that this won't work for any users with multiple calendars though. Potentially `khal configure` could ask about defaults if there are multiple calendars, but there would need to be the option to not set one.

**Comment by d7415** [comment]
> Thanks for responding. I have one more suggestion to add auto-completion as a feature. I develop a python cli tool as my day job and there's an argcomplete module that, when combined with argparse, allows for easy and complete argument completion. Is this issue board a good place for feature requests? I don't want to spam.

#937 :+1:
