### ISSUE TITLE
Add auto-completion for other shells

### ISSUE THREAD

**Issue by d7415** [pimutils/khal#937]
Thanks for responding. I have one more suggestion to add auto-completion as a feature. I develop a python cli tool as my day job and there's an argcomplete module that, when combined with argparse, allows for easy and complete argument completion. Is this issue board a good place for feature requests? I don't want to spam.

_Originally posted by @ciminobo in https://github.com/pimutils/khal/issues/935#issuecomment-629563251_

@ephase [responded](https://github.com/pimutils/khal/issues/935#issuecomment-629632311):
> ... khal use click instead of argparse. I know there is auto-completion for zsh because I use it everyday.

**Comment by d7415** [comment]
The zsh completion is [here](https://github.com/pimutils/khal/blob/master/misc/__khal)

**Comment by geier** [comment]
closed with #1141
