### ISSUE TITLE
Sensible default for printics

### ISSUE THREAD

**Issue by kaiec** [pimutils/khal#941]
printics currently uses agenda_event_format as default:

https://github.com/pimutils/khal/blob/a401ef28076954779cc66885a05dd1fa7da46fe3/khal/controllers.py#L625

Therefore, the date of the event is missing, when it is used to quickly check the contents of an ICS file, kind of missing its purpose. If I do not miss another use case where a date context is somehow given, I suggest to use event_format as format.

Or - in my opinion even better - define an own config value for printics_format that is used and can be tweaked for own purposes without affecting other parts of khal.

**Comment by ephase** [comment]
Hi @kaiec, in my opinion use the event_format is a better idea, you can add a curtom output with `-f | --format` options
