### ISSUE TITLE
Error with mypy event in master branch

### ISSUE THREAD

**Issue by ephase** [pimutils/khal#942]
When I try to run mypy on khal project I've got this error 
```
tests/ui/test_calendarwidget.py:6: error: Need type annotation for 'on_press' (hint: "on_press: Dict[<type>, <type>] = ...")
khal/khalendar/backend.py:190: error: Incompatible default for argument "stuple" (default has type "object", argument has type "Tuple[Any, ...]")
tests/cli_test.py:405: error: Not all arguments converted during string formatting
```

For the `backend.py` file, the source of problem is `sql_ex()`, the `stuple: tuple=Union[tuple, str]` parameter. Removing the `tuple=` part avoid the problem.

**Comment by d7415** [comment]
This seems to work too:
```py
def sql_ex(self, statement: str, stuple: tuple=(tuple, str)) -> List:
```

I haven't looked properly at expected syntax though to check what we need.

**Comment by ephase** [comment]
Error on `backend.py` occurs with new version of `mypy` (tested here with some venvs). Others are older but not tested in CI.

**Comment by ephase** [comment]
@d7415 Your version work too (with py.test and mypy) I can modify my PR in that way.

**Comment by d7415** [comment]
I'm just reading the docs now...

**Comment by d7415** [comment]
I think your solution is better (I misread what you wrote the first time through). I do wonder whether `stuple` is ever specified as a `str` though. I'm not sure what that syntax was supposed to indicate.

**Comment by d7415** [comment]
It looks like `sql_ex()` is only ever called with `stuple` as a tuple, so we could have `stuple: tuple` or `stuple: Tuple`

**Comment by ephase** [comment]
In any situation I tested, `sql_ex()` does not work with str for stuple... I can test with your solution if it work.

**Comment by d7415** [comment]
> In any situation I tested, `sql_ex()` does not work with str for stuple... I can test with your solution if it work, but tomorrow, kids are just sleeping, and I need it too :).

Your solution allows for `stuple` to be a `str` - that's what the `Union` does. Otherwise we can just use `stuple: tuple`.

**Comment by ephase** [comment]
So, I found a solution that work

```python
    def sql_ex(self, statement: str, stuple: Union[tuple, str]) -> List:
        """wrapper for sql statements, does a "fetchall" """

        if isinstance(stuple, str):
            stuple = (stuple,)

```
Then you can use `str` or `tuple` and it work, but `str` seems to be useless, maybe the simplest solution is enough :

```python
def sql_ex(self, statement: str, stuple: Union[tuple, str]) -> List:
```

**Comment by d7415** [comment]
Yeah, adding an `isinstance` wrapper for a use case we don't have seems silly. I think we go for the `stuple: tuple` option.

**Comment by ephase** [comment]
I think so too
