### ISSUE TITLE
URL field support

### ISSUE THREAD

**Issue by mat813** [pimutils/khal#946]
At work, we often end up creating calendar events for planned tasks we have to do, and we put the URL to the tasks in our ticketing system in the event, so that we can easily get to the details.  The thing is, it ends up in a URL field that khal does not seem to either display or allow editing

Looking at an event, it has a line with:

```
URL;VALUE=URI:https://ticket.url/here?id
```

It would be great if khal could display it, and get a new field to edit it.

**Comment by ephase** [comment]
Hi @mat813,
This is a good idea in my opinion, There is some work to do but i think we could add it to khal first.

**Comment by ephase** [comment]
I'm working on it you can check my test repository [here](https://github.com/Khalzone/khal/tree/feature/946) if you want to test it.

**Comment by pkrog** [comment]
With my iPhone I get the following line for URL field:
```
URL:https://webconf.cea.fr/chokri.mraidha/K6HDK63W
```
Would your implementation be compatible ? If yes I will test the branch you mentioned.

**Comment by ephase** [comment]
Hi @pkrog,

For now, my URL field implementation didn't verify URI validity, then yours should work. You must go with [this repo](https://github.com/ephase/khal/tree/feature/946) instead (more up to date)

If you have any problem, comment on this thread,

**Comment by pkrog** [comment]
I got the repos and branch, but cannot run the tests.
When I run `tox` I get:
```
...
E       assert 0 == 1
E        +  where 0 = len([])

tests/khalendar_test.py:390: AssertionError
_____________________________________________________________________________________________________ test_birthdays_29feb ______________________________________________________________________________________________________
...
ERROR:   py38-tests-pytz201702: commands failed
ERROR:   py38-tests-pytz201610: commands failed
ERROR:   py38-tests-pytz_latest: commands failed
ERROR:   py38-style-pytz201702: commands failed
ERROR:   py38-style-pytz201610: commands failed
ERROR:   py38-style-pytz_latest: commands failed
ERROR:   py38-mypy-pytz201702: commands failed
ERROR:   py38-mypy-pytz201610: commands failed
ERROR:   py38-mypy-pytz_latest: commands failed
```

**Comment by ephase** [comment]
@pkrog what is your system? I've got the same errors on the master branch on my Archlinux system, but not on my Debian.

**Comment by pkrog** [comment]
I'm on ArchLinux. Have you an idea of the reason?

**Comment by d7415** [comment]
> I'm on ArchLinux. Have you an idea of the reason?

Not really. It's mostly discussed in #860.
