### ISSUE TITLE
is there a way to customize keybindings?

### ISSUE THREAD

**Issue by ahillio** [pimutils/khal#948]
I just started using khal (thank you <3) and quickly ran into this problem that I'm not able to edit an event from ikhal mode because I apparently don't have a meta key.  Can that keybinding be customized?  I'd love `e` to edit and `ctrl+e` (instead of meta) to export.  Is this possible?

**Comment by ahillio** [comment]
Oh... I just found https://github.com/pimutils/khal/issues/462 which sounds like the answer is "no" :(
But maybe there's some other solution to work around my lack of meta key so I can edit events from ikhal?

**Comment by geier** [comment]
Yes, you can do this. Check the documenation section on [keybindings](https://khal.readthedocs.io/en/latest/configure.html#the-keybindings-section). 

Something like 

```
[keybindings]
external_edit = e
export = ctrl e
```
in your khal.conf should work

**Comment by d7415** [comment]
@ahillio "meta" is usually labelled "alt" on PC keyboards (I can't remember the Apple equivalent), in case that helps. It's rare to find a keyboard without one, though I suppose it could happen. It's worth noting that the default keybinding for external editing is `meta E`, so alt+shift+e.

That said, you should be able to customise them to your liking anyway, as @geier explained :)

**Comment by ahillio** [comment]
Awesome thanks so much!
