### ISSUE TITLE
external_edit freezes ikhal

### ISSUE THREAD

**Issue by ahillio** [pimutils/khal#949]
After saving and quitting vim to modify the temporary file during the `external_edit` operation, upon returning to the ikhal screen, ikhal is frozen.  I can't `q` to quite or move the cursor or add a new event or anything else, I have to `ctrl c` to terminate the process.  Anyone else experience anything like this?

khal version 0.10.1 with pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7).

**Comment by d7415** [comment]
Yes. #827. This has been fixed in master but not yet released.

**Comment by ahillio** [comment]
Thanks!!!

**Comment by d7415** [comment]
0.10.2 has just been released with this fix :)

**Comment by ahillio** [comment]
Oh Sweet!  A `pip install khal --upgrade` and I'm all set :)
