### ISSUE TITLE
How to get colors like the screenshot shows?

### ISSUE THREAD

**Issue by ahillio** [pimutils/khal#961]
I'm trying to get some color but it's still just white text on my dark terminal background.  I have :

```
[default]
highlight_event_days = true
```
and
```
[highlight_days]
multiple = yellow
```
But multiple-day calendar items are still white in both `khal list` and `khal interactive`.  I'm not sure why that doesn't work.  If I changed "yellow" to "blue" it'd get the error `critical: in [highlight_days] multiple: the value "blue" is unacceptable.`.  And I don't know how to apply other colors (for example, the screenshot on the readme page looks like there are categories of events (perhaps importance levels?) that get different colors).

Is there an example config file that provides the colorscheme in the https://github.com/pimutils/khal screenshot?

**Comment by geier** [comment]
You'll need to configure the colors in your config file like here: https://khal.readthedocs.io/en/latest/configure.html#the-calendars-section .

**Comment by ahillio** [comment]
I was reading that...

**Comment by ahillio** [comment]
I was reading that before posting my question here.  My question remains.  How can a colorscheme like what's presented in the screenshot be achieved?

**Comment by geier** [comment]
Under each calendar entry, you can specify a color in one of the allowed formats (e.g. named colors like `light blue`). If you are using autodiscovery for vdir folders, it's best to put a `color` file in the vdir.

**Comment by geier** [comment]
E.g. see my config here: https://github.com/geier/dotfiles/blob/master/.config/khal/config

**Comment by ahillio** [comment]
oh, so the colors are per-calendar???  I just have one calendar.  If I wanted to color-code the events I'd need to create separate calendars to put the events into?

**Comment by christiangeier** [comment]
Yes, each calendar has one color. Sorry if that wasn't clear.

**Comment by ahillio** [comment]
is there a way to get a list of the available colors?  (for example "blue" results in the error I posted but your config includes "dark blue").

**Comment by ahillio** [comment]
Is it using some standard color package that python provides for example?  (I don't know if those exist, just guessing).  It doesn't look like terminal color codes like `\e[6;32;40m` can be used.  What colors are available?

Also: is there a way to color the "other" text, so if the event gets dark green, the "Tomorrow, 2020-10-03" above it is not colored... is there a config to control that color?

**Comment by geier** [comment]
Yes, it's using urwid for ikhal and something else for khal, this should be explained in the documentation:

> khal will use this color for coloring this calendar’s event. The following color names are supported: black, white, brown, yellow, dark gray, dark green, dark blue, light gray, light green, light blue, dark magenta, dark cyan, dark red, light magenta, light cyan, light red. Depending on your terminal emulator’s settings, they might look different than what their name implies. In addition to the 16 named colors an index from the 256-color palette or a 24-bit color code can be used, if your terminal supports this. The 256-color palette index is simply a number between 0 and 255. The 24-bit color must be given as #RRGGBB, where RR, GG, BB is the hexadecimal value of the red, green and blue component, respectively. When using a 24-bit color, make sure to enclose the color value in ‘ or “

The colors of everything but the calendars are only minimally controllable at the moment (search for `theme` in the documenation).

**Comment by ahillio** [comment]
Oh, I see that now.  Thanks for explaining!

**Comment by geier** [comment]
You are welcome!
