### ISSUE TITLE
specifying calendar in interactive mode

### ISSUE THREAD

**Issue by ahillio** [pimutils/khal#966]
Is there a way to do this with the keyboard?  I had given up, thought I ran into a bug, couldn't find any documentation on this.... and then I unintentionally clicked on the calendar name and a selection menu appeared.  So apparently I can select a calendar when editing/creating an event by using the mouse but is there a mouse-free way?

**Comment by d7415** [comment]
Tab or down arrow to the calendar field, press enter or space and the menu will appear.

**Comment by ahillio** [comment]
@d7415 THANK YOU!!!
