### ISSUE TITLE
Can it be integrated with Conky for desktop calendar?

### ISSUE THREAD

**Issue by Usodiariom** [pimutils/khal#970]
A calendar on the linux desktop is possible using **conky and Khal**, which uses the **CalDAV URLs**, such as the **Radicale** URL or the **Nextcloud calendar** URL.

Is it possible with Khal?

**Comment by d7415** [comment]
I see no reason why that wouldn't work. There's no integration, but conky has a number of `exec` options to call external programs like khal.
