### ISSUE TITLE
`khal interactive` does not honor filtering with -a and -d (`ikhal` does)

### ISSUE THREAD

**Issue by kourtbailey** [pimutils/khal#974]
I have discovered that `khal interactive` does not honor the  `-a calendar` and `-d calendar` options.  Thanks to [Issue #713](https://github.com/pimutils/khal/issues/713), I learned that `ikhal -a calendar` and `ikhal -d calendar` work as expected.

I think it would be more helpful for new users if `khal interactive` honored all the options that `ikhal` honors.

**Comment by d7415** [comment]
Confirmed. Found where to fix it. I just need to check for any unintended consequences.

**Comment by d7415** [comment]
It looks like this was missed in d13994a9. Fix incoming.
