### ISSUE TITLE
khal interactive allday events at bottom of day. 

### ISSUE THREAD

**Issue by fullstopslash** [pimutils/khal#976]
`khal list` will show an agenda with  any  all  day events  at the  top  of the day (which seems right), while `khal interactive` shows events listed at the bottom of  the day (which seems counter intuitive to me) . Tried poking around the docs to see if there was some setting I missed and I couldn't seem to find one.

**Comment by d7415** [comment]
Good spot. I don't know how I hadn't noticed this before.

**Comment by d7415** [comment]
This will hopefully be fixed in #980, but I'm going to wait a week or so before merging in case I've missed something.
