### ISSUE TITLE
Just a Quick Thanks!

### ISSUE THREAD

**Issue by TomGranot** [pimutils/khal#984]
I've started playing around with all sorts of Calendar tools for the CLI and have yet to find one that I like.
`khal` seems like gold - will give it a spin this weekend.

Thank you for writing the tool and for making sure the messaging around it pushed it to the top of HN:)

Feel free to close afterwards.

**Comment by d7415** [comment]
I left this open for a bit to let people see it.

I wasn't aware of the HN thing, so can't take credit for that :)

Thanks for the note!

**Comment by TomGranot** [comment]
@d7415 :) Have a great day!
