### ISSUE TITLE
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'localize'

### ISSUE THREAD

**Issue by bjne** [pimutils/khal#985]
Traceback (most recent call last):
  File "/usr/local/bin/khal", line 11, in <module>
    load_entry_point('khal==0.10.3.dev20+g0ab5247', 'console_scripts', 'khal')()
  File "/home/bjornar/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/bjornar/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/bjornar/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bjornar/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bjornar/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/bjornar/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/khal-0.10.3.dev20+g0ab5247-py3.8.egg/khal/cli.py", line 313, in klist
    event_column = controllers.khal_list(
  File "/usr/local/lib/python3.8/dist-packages/khal-0.10.3.dev20+g0ab5247-py3.8.egg/khal/controllers.py", line 256, in khal_list
    original_start = conf['locale']['local_timezone'].localize(start)
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'localize'

**Comment by hastinbe** [comment]
Had the same issue on a new install. I can't seem to find which versions had a `localize()` method, it seems to be a specific to a datetime objects from `pytz`. I replaced `localize()` calls with `dt.replace(tzinfo=...)` to fix the issue here. There are a lot these calls, a method similar to `utils.is_aware()` is probably necessary. Don't really care to make a patch since I only fixed it in areas that gave me issues. Hope that helps

**Comment by geier** [comment]
@bjne  Thank you for the report, and sorry for the long delay.

Can you tell us a bit more about the system you are running this? How did you install khal? And what is the output of `pip freeze`? 

help would be really apreciated!

**Comment by polyzen** [comment]
@geier, ran into this error after updating tzlocal to version 3 (released today). They switched to zoneinfo from pytz:
https://github.com/regebro/tzlocal/pull/92

**Comment by ECon87** [comment]
Same issue here! Any quick and easy way to fix it?

**Comment by G-071** [comment]
I just encountered the same issue when installing khal via pip on a new machine! As a short-term workaround: Downgrading tzlocal to 2.1 fixed it for me, though a proper fix would be better of course!

**Comment by WhyNotHugo** [comment]
I'd love to be able to transition to `zoneinfo` and drop the external dependency for `pytz`, especially considering there's a backport for older pythons.

However, `icalendar` still uses pytz. I've opened [a PR](https://github.com/collective/icalendar/pull/327) laying some groundwork to do the upgrade there, but haven't gotten much feedback. I don't see any merges there in over a year, so I'm not sure of the state of `icalendar`.

**Comment by geier** [comment]
@WhyNotHugo  I'm a maintainer of icalendar (well, I have commit access, haven't done much maintaining lately). Moving icalendar completely to `zoneinfo` will be quite a task, but perhaps it's also a chance to clean up some of the mess of timezone building. 

On the other hand, the plone community is very conservative, I'm not sure how easily they would accept a move to `zoneinfo`. 

But I'll see if I find the time to give a hand.

**Comment by geier** [comment]
Regarding this issue:

For now it's probably easiest, to detect if `tzlocal()` returns a `zoneinfo` zone and convert it to a `pytz` zone.

**Comment by albert-ying** [comment]
I have this error when running `khal calendar` in `tmux`, but not in the regular terminal.

**Comment by regebro** [comment]
It has become obvious to me lately that the tzlocal 3.0 changes was a mistake. The question is how to fix it.
Since you were affected by this, I'd appreaciate any input.

Discussion: https://github.com/regebro/tzlocal/issues/117

**Comment by geier** [comment]
This should also be fixed with #1126 (which is not released yet), please re-open or comment if the issue persists.

@regebro thank you for tzlocal and also for keeping us informed here! Sorry for not coming back to you in time.

Our "fix" is a bit more brutal (`pytz.timezone(str(get_localzone()))`), but as we currently rely on private attributes from pytz timezones to contruct VTIMEZONEs, even the shim wasn't good enough.
