### ISSUE TITLE
configobj does no longer ship `validate` as module

### ISSUE THREAD

**Issue by jelly** [pimutils/khal#992]
In configobj master validator is no longer installed by setup.py, so this project should add a dependency on [python-validate](https://pypi.org/project/validate/)

See also https://github.com/DiffSK/configobj/issues/204

**Comment by nim65s** [comment]
Hi,

I also have a `validate` issue on Arch:

```python
╰─>$ khal
Traceback (most recent call last):
  File "/usr/bin/khal", line 2, in <module>
    from khal.cli import main_khal
  File "/usr/lib/python3.9/site-packages/khal/cli.py", line 35, in <module>
    from .settings import InvalidSettingsError, get_config
  File "/usr/lib/python3.9/site-packages/khal/settings/__init__.py", line 1, in <module>
    from .settings import get_config  # noqa
  File "/usr/lib/python3.9/site-packages/khal/settings/settings.py", line 30, in <module>
    from validate import Validator
ModuleNotFoundError: No module named 'validate'
```

But your solution doesn't work for me in python 3:

```python
╰─>$ pip install --user validate
Collecting validate
  Downloading validate-1.0.1.tar.gz (32 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dy5dqlea/validate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dy5dqlea/validate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-krszn_d5
         cwd: /tmp/pip-install-dy5dqlea/validate/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dy5dqlea/validate/setup.py", line 13, in <module>
        from configobj import __version__ as VERSION
      File "/tmp/pip-install-dy5dqlea/validate/configobj.py", line 1632
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by piater** [comment]
As I understand it, [this commit](https://github.com/DiffSK/configobj/commit/0cfca0c60b96402c8a508b5930ba7065190cbc62#diff-58b7fc05c0526d9a9b3c0b50dda416fcbf0a654e696da4b6df82cbb5a6b2dcfc) moved the `validate` module into `configobj` and added a shim to keep existing code working, but the shim does not appear to be shipped with the latest Arch package. On my Arch system, I got khard working again by replacing `import validate` by `import configobj.validate as validate` in `/usr/lib/python3.9/site-packages/khard/config.py`. See also [Arch bug 69057](https://bugs.archlinux.org/task/69057?project=5&string=configobj).

**Comment by Ahacad** [comment]
Same problem, solved by replacing `from validate import Validator` with `from configobj.validate import Validator` in `/usr/lib/python3.9/site-packages/khal/settings/settings.py` and `from validate import VdtValueError` with `from configobj.validate import VdtValueError` in `/usr/lib/python3.9/site-packages/khal/settings/utils.py`. I am using Arch Linux with `python-configobj-5.0.6-10` and `python-3.9.1-1`.

**Comment by diego-rapoport** [comment]
The changing @Ahacad did also worked here.

I'm using ArchLabs with configobj 5.1.0 and python 3.9.1

**Comment by polyzen** [comment]
A fix has been applied to the Arch package:
https://github.com/archlinux/svntogit-community/commit/f31a20ad9c0ed2254d5db8fadf06c61106eb0ede

**Comment by d7415** [comment]
I will patch khal to support the new configobj at some point soon, but for now it looks like Arch broke it and Arch have fixed it. I'll open a new issue to track the upgrade as for now khal isn't broken by this due to the shim.
