### ISSUE TITLE
Migrate to new configobj validate

### ISSUE THREAD

**Issue by d7415** [pimutils/khal#993]
[`configobj` 5.1.0+](https://github.com/DiffSK/configobj/blob/master/CHANGES.rst#release-510) has integrated `validate` and will eventually want a new syntax. 5.1.0 has a shim to allow the old syntax to work for now. Until we set a minimum version of `configobj` we'll have to cover both imports.

**Comment by GideonWolfe** [comment]
Is there something I as a user am supposed to do to work around this? running `ikhal` gives me

```python
Traceback (most recent call last):
  File "/usr/bin/ikhal", line 2, in <module>
    from khal.cli import main_ikhal
  File "/usr/lib/python3.9/site-packages/khal/cli.py", line 35, in <module>
    from .settings import InvalidSettingsError, get_config
  File "/usr/lib/python3.9/site-packages/khal/settings/__init__.py", line 1, in <module>
    from .settings import get_config  # noqa
  File "/usr/lib/python3.9/site-packages/khal/settings/settings.py", line 30, in <module>
    from validate import Validator
ModuleNotFoundError: No module named 'validate'
```

and trying to install `validate` throws 

```bash
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4hsai61b/validate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4hsai61b/validate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7k4fo32_
         cwd: /tmp/pip-install-4hsai61b/validate/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4hsai61b/validate/setup.py", line 13, in <module>
        from configobj import __version__ as VERSION
      File "/tmp/pip-install-4hsai61b/validate/configobj.py", line 1632
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
because of python2 syntax I believe.

**Comment by polyzen** [comment]
Update your system -- a shim that provides the `validate` import has been included in the `python-configobj` package.

**Comment by deafmute1** [comment]
It should be an easy enough fix to cover both imports just a
```python
try:
    from validate import Validator
except ModuleNotFoundError:
    from configobj.validate import Validator`
```
where necessary, no?



> Update your system -- a shim that provides the `validate` import has been included in the `python-configobj` package.

Unfortunately its not so simple to do so. The shim in is the currently unpackaged (in pypi and my distro (arch)) as it is the upcoming release v5.1.0 which has been the upcoming release since 2016. The only way to get it is to build from source.

**Comment by deafmute1** [comment]
Oh, I misread the changelog, it seems that it is "released" even if the maintainers hasn't packaged it for pypi yet. Guess I'll chase up the arch maintainer.
